# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.update_case_batch import UpdateCaseBatch

class TestUpdateCaseBatch(unittest.TestCase):
    """UpdateCaseBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCaseBatch:
        """Test UpdateCaseBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCaseBatch`
        """
        model = UpdateCaseBatch()
        if include_optional:
            return UpdateCaseBatch(
                analysis_code = '',
                category_code = 'prenatal',
                diagnostic_lab_code = '',
                note = '',
                ordering_organization_code = '',
                ordering_physician = '',
                patients = [
                    radiant_python.models.case_patient_batch.CasePatientBatch(
                        affected_status_code = 'affected', 
                        family_history = [
                            radiant_python.models.family_history_batch.FamilyHistoryBatch(
                                condition = '', 
                                family_member_code = '', )
                            ], 
                        observations_categorical = [
                            radiant_python.models.observation_categorical_batch.ObservationCategoricalBatch(
                                code = '', 
                                interpretation_code = 'positive', 
                                note = '', 
                                onset_code = '', 
                                system = '', 
                                value = '', )
                            ], 
                        observations_text = [
                            radiant_python.models.observation_text_batch.ObservationTextBatch(
                                code = '', 
                                value = '', )
                            ], 
                        patient_organization_code = '', 
                        relation_to_proband_code = 'mother', 
                        submitter_patient_id = '', )
                    ],
                primary_condition_code_system = '',
                primary_condition_value = '',
                priority_code = '',
                project_code = '',
                resolution_status_code = '',
                status_code = '',
                submitter_case_id = '',
                type = 'germline'
            )
        else:
            return UpdateCaseBatch(
                analysis_code = '',
                category_code = 'prenatal',
                diagnostic_lab_code = '',
                ordering_organization_code = '',
                patients = [
                    radiant_python.models.case_patient_batch.CasePatientBatch(
                        affected_status_code = 'affected', 
                        family_history = [
                            radiant_python.models.family_history_batch.FamilyHistoryBatch(
                                condition = '', 
                                family_member_code = '', )
                            ], 
                        observations_categorical = [
                            radiant_python.models.observation_categorical_batch.ObservationCategoricalBatch(
                                code = '', 
                                interpretation_code = 'positive', 
                                note = '', 
                                onset_code = '', 
                                system = '', 
                                value = '', )
                            ], 
                        observations_text = [
                            radiant_python.models.observation_text_batch.ObservationTextBatch(
                                code = '', 
                                value = '', )
                            ], 
                        patient_organization_code = '', 
                        relation_to_proband_code = 'mother', 
                        submitter_patient_id = '', )
                    ],
                project_code = '',
                status_code = '',
                submitter_case_id = '',
                type = 'germline',
        )
        """

    def testUpdateCaseBatch(self):
        """Test UpdateCaseBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
