# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant-python.models.igv_track_enriched import IGVTrackEnriched

class TestIGVTrackEnriched(unittest.TestCase):
    """IGVTrackEnriched unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IGVTrackEnriched:
        """Test IGVTrackEnriched
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IGVTrackEnriched`
        """
        model = IGVTrackEnriched()
        if include_optional:
            return IGVTrackEnriched(
                family_role = '',
                format = '',
                index_url = '',
                index_url_expire_at = 56,
                name = '',
                patient_id = 56,
                sex = '',
                type = '',
                url = '',
                url_expire_at = 56
            )
        else:
            return IGVTrackEnriched(
        )
        """

    def testIGVTrackEnriched(self):
        """Test IGVTrackEnriched"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
