# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.update_case_status_input import UpdateCaseStatusInput

class TestUpdateCaseStatusInput(unittest.TestCase):
    """UpdateCaseStatusInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCaseStatusInput:
        """Test UpdateCaseStatusInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCaseStatusInput`
        """
        model = UpdateCaseStatusInput()
        if include_optional:
            return UpdateCaseStatusInput(
                status_code = 'in_review'
            )
        else:
            return UpdateCaseStatusInput(
        )
        """

    def testUpdateCaseStatusInput(self):
        """Test UpdateCaseStatusInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
