# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.occurrence_flag_type import OccurrenceFlagType

class TestOccurrenceFlagType(unittest.TestCase):
    """OccurrenceFlagType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOccurrenceFlagType(self):
        """Test OccurrenceFlagType"""
        # inst = OccurrenceFlagType()

if __name__ == '__main__':
    unittest.main()
