# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.variant_cases_filters import VariantCasesFilters

class TestVariantCasesFilters(unittest.TestCase):
    """VariantCasesFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantCasesFilters:
        """Test VariantCasesFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantCasesFilters`
        """
        model = VariantCasesFilters()
        if include_optional:
            return VariantCasesFilters(
                case_analysis = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ],
                classification = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ],
                diagnosis_lab = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ]
            )
        else:
            return VariantCasesFilters(
                case_analysis = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ],
                classification = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ],
                diagnosis_lab = [
                    openapi_client.models.aggregation.Aggregation(
                        count = 56, 
                        key = '', 
                        label = '', )
                    ],
        )
        """

    def testVariantCasesFilters(self):
        """Test VariantCasesFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
