# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.assay import Assay

class TestAssay(unittest.TestCase):
    """Assay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Assay:
        """Test Assay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Assay`
        """
        model = Assay()
        if include_optional:
            return Assay(
                aliquot = '',
                capture_kit = '',
                created_on = '',
                experimental_strategy_code = '',
                experimental_strategy_name = '',
                histology_code = '',
                platform_code = '',
                run_alias = '',
                run_date = '',
                run_name = '',
                sample_id = 56,
                sample_type_code = '',
                seq_id = 56,
                sequencing_lab_code = '',
                sequencing_lab_name = '',
                sequencing_read_technology_code = '',
                sequencing_read_technology_name = '',
                status_code = '',
                submitter_sample_id = '',
                tissue_site = '',
                updated_on = ''
            )
        else:
            return Assay(
        )
        """

    def testAssay(self):
        """Test Assay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
