# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.case_entity import CaseEntity

class TestCaseEntity(unittest.TestCase):
    """CaseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseEntity:
        """Test CaseEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseEntity`
        """
        model = CaseEntity()
        if include_optional:
            return CaseEntity(
                analysis_catalog_code = '',
                analysis_catalog_name = '',
                assays = [
                    openapi_client.models.case_assay.CaseAssay(
                        affected_status_code = '', 
                        experimental_strategy_code = '', 
                        has_variants = True, 
                        histology_code = '', 
                        patient_id = 56, 
                        relationship_to_proband = '', 
                        sample_id = 56, 
                        sample_submitter_id = '', 
                        sample_type_code = '', 
                        seq_id = 56, 
                        status_code = '', 
                        updated_on = '', )
                    ],
                case_id = 56,
                case_type = '',
                created_on = '',
                diagnosis_lab_code = '',
                diagnosis_lab_name = '',
                members = [
                    openapi_client.models.case_patient_clinical_information.CasePatientClinicalInformation(
                        affected_status_code = '', 
                        date_of_birth = '', 
                        ethnicity_codes = [
                            ''
                            ], 
                        non_observed_phenotypes = [
                            openapi_client.models.term.Term(
                                id = '', 
                                name = '', 
                                onset_code = '', 
                                term = '', )
                            ], 
                        observed_phenotypes = [
                            openapi_client.models.term.Term(
                                id = '', 
                                name = '', 
                                onset_code = '', 
                                term = '', )
                            ], 
                        organization_code = '', 
                        organization_name = '', 
                        patient_id = 56, 
                        relationship_to_proband = '', 
                        sex_code = '', 
                        submitter_patient_id = '', )
                    ],
                note = '',
                ordering_organization_code = '',
                ordering_organization_name = '',
                prescriber = '',
                primary_condition_id = '',
                primary_condition_name = '',
                priority_code = '',
                project_code = '',
                project_name = '',
                status_code = '',
                tasks = [
                    openapi_client.models.case_task.CaseTask(
                        created_on = '', 
                        id = 56, 
                        patients = [
                            ''
                            ], 
                        type_code = '', 
                        type_name = '', )
                    ],
                updated_on = ''
            )
        else:
            return CaseEntity(
                assays = [
                    openapi_client.models.case_assay.CaseAssay(
                        affected_status_code = '', 
                        experimental_strategy_code = '', 
                        has_variants = True, 
                        histology_code = '', 
                        patient_id = 56, 
                        relationship_to_proband = '', 
                        sample_id = 56, 
                        sample_submitter_id = '', 
                        sample_type_code = '', 
                        seq_id = 56, 
                        status_code = '', 
                        updated_on = '', )
                    ],
                case_id = 56,
                created_on = '',
                members = [
                    openapi_client.models.case_patient_clinical_information.CasePatientClinicalInformation(
                        affected_status_code = '', 
                        date_of_birth = '', 
                        ethnicity_codes = [
                            ''
                            ], 
                        non_observed_phenotypes = [
                            openapi_client.models.term.Term(
                                id = '', 
                                name = '', 
                                onset_code = '', 
                                term = '', )
                            ], 
                        observed_phenotypes = [
                            openapi_client.models.term.Term(
                                id = '', 
                                name = '', 
                                onset_code = '', 
                                term = '', )
                            ], 
                        organization_code = '', 
                        organization_name = '', 
                        patient_id = 56, 
                        relationship_to_proband = '', 
                        sex_code = '', 
                        submitter_patient_id = '', )
                    ],
                status_code = '',
                tasks = [
                    openapi_client.models.case_task.CaseTask(
                        created_on = '', 
                        id = 56, 
                        patients = [
                            ''
                            ], 
                        type_code = '', 
                        type_name = '', )
                    ],
                updated_on = '',
        )
        """

    def testCaseEntity(self):
        """Test CaseEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
