# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.beacon_configuration import BeaconConfiguration

class TestBeaconConfiguration(unittest.TestCase):
    """BeaconConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeaconConfiguration:
        """Test BeaconConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeaconConfiguration`
        """
        model = BeaconConfiguration()
        if include_optional:
            return BeaconConfiguration(
                var_schema = '',
                entry_types = {
                    'key' : radiant_python.models.beacon_entry_type.BeaconEntryType(
                        default_schema = radiant_python.models.beacon_schema_def.BeaconSchemaDef(
                            id = '', 
                            name = '', 
                            reference_to_schema_definition = '', 
                            schema_version = '', ), 
                        description = '', 
                        id = '', 
                        name = '', 
                        non_filtered_queries_allowed = True, 
                        ontology_term_for_this_type = radiant_python.models.beacon_ontology_term.BeaconOntologyTerm(
                            id = '', 
                            label = '', ), 
                        part_of_specification = '', )
                    },
                maturity_attributes = radiant_python.models.beacon_maturity_attributes.BeaconMaturityAttributes(
                    production_status = '', ),
                security_attributes = radiant_python.models.beacon_security_attributes.BeaconSecurityAttributes(
                    default_granularity = '', 
                    description = '', 
                    security_levels = [
                        ''
                        ], )
            )
        else:
            return BeaconConfiguration(
        )
        """

    def testBeaconConfiguration(self):
        """Test BeaconConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
