# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hpo_api import HpoApi


class TestHpoApi(unittest.TestCase):
    """HpoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HpoApi()

    def tearDown(self) -> None:
        pass

    def test_hpo_term_auto_complete(self) -> None:
        """Test case for hpo_term_auto_complete

        Get AutoCompleteTerm list of matching input string with highlighted
        """
        pass


if __name__ == '__main__':
    unittest.main()
