# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.patient_radiation import PatientRadiation

class TestPatientRadiation(unittest.TestCase):
    """PatientRadiation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatientRadiation:
        """Test PatientRadiation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatientRadiation`
        """
        model = PatientRadiation()
        if include_optional:
            return PatientRadiation(
                craniospinal_dose = radiant_python.models.patient_dose.PatientDose(
                    unit = '', 
                    value = '', ),
                focal_dose = radiant_python.models.patient_dose.PatientDose(
                    unit = '', 
                    value = '', ),
                site = '',
                site_other = '',
                start = radiant_python.models.patient_day_date.PatientDayDate(
                    date = '2020-01-31', 
                    day = 56, ),
                stop = radiant_python.models.patient_day_date.PatientDayDate(
                    date = '2020-01-31', 
                    day = 56, ),
                type = '',
                type_other = ''
            )
        else:
            return PatientRadiation(
                craniospinal_dose = radiant_python.models.patient_dose.PatientDose(
                    unit = '', 
                    value = '', ),
                focal_dose = radiant_python.models.patient_dose.PatientDose(
                    unit = '', 
                    value = '', ),
                start = radiant_python.models.patient_day_date.PatientDayDate(
                    date = '2020-01-31', 
                    day = 56, ),
                stop = radiant_python.models.patient_day_date.PatientDayDate(
                    date = '2020-01-31', 
                    day = 56, ),
        )
        """

    def testPatientRadiation(self):
        """Test PatientRadiation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
