# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.cnv_gene_overlap import CNVGeneOverlap

class TestCNVGeneOverlap(unittest.TestCase):
    """CNVGeneOverlap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CNVGeneOverlap:
        """Test CNVGeneOverlap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CNVGeneOverlap`
        """
        model = CNVGeneOverlap()
        if include_optional:
            return CNVGeneOverlap(
                cytoband = [
                    ''
                    ],
                gene_id = '',
                gene_length = 56,
                nb_exons = 56,
                nb_overlap_bases = 56,
                overlap_type = '',
                overlapping_cnv_percent = 1.337,
                overlapping_gene_percent = 1.337,
                symbol = ''
            )
        else:
            return CNVGeneOverlap(
                cytoband = [
                    ''
                    ],
                gene_id = '',
                gene_length = 56,
                nb_exons = 56,
                nb_overlap_bases = 56,
                overlap_type = '',
                overlapping_cnv_percent = 1.337,
                overlapping_gene_percent = 1.337,
                symbol = '',
        )
        """

    def testCNVGeneOverlap(self):
        """Test CNVGeneOverlap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
