# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.list_assignment_candidates_body import ListAssignmentCandidatesBody

class TestListAssignmentCandidatesBody(unittest.TestCase):
    """ListAssignmentCandidatesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAssignmentCandidatesBody:
        """Test ListAssignmentCandidatesBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAssignmentCandidatesBody`
        """
        model = ListAssignmentCandidatesBody()
        if include_optional:
            return ListAssignmentCandidatesBody(
                case_ids = [
                    56
                    ],
                limit = 56,
                offset = 56,
                page_index = 56,
                search = ''
            )
        else:
            return ListAssignmentCandidatesBody(
        )
        """

    def testListAssignmentCandidatesBody(self):
        """Test ListAssignmentCandidatesBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
