# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.api.gene_panels_api import GenePanelsApi


class TestGenePanelsApi(unittest.TestCase):
    """GenePanelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenePanelsApi()

    def tearDown(self) -> None:
        pass

    def test_put_gene_panels(self) -> None:
        """Test case for put_gene_panels

        Replace the tenant's gene panels
        """
        pass


if __name__ == '__main__':
    unittest.main()
