# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.api.interpretations_api import InterpretationsApi


class TestInterpretationsApi(unittest.TestCase):
    """InterpretationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InterpretationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_interpretation_germline(self) -> None:
        """Test case for get_interpretation_germline

        Get interpretation germline
        """
        pass

    def test_get_interpretation_germline_deprecated(self) -> None:
        """Test case for get_interpretation_germline_deprecated

        Get interpretation germline
        """
        pass

    def test_get_interpretation_somatic(self) -> None:
        """Test case for get_interpretation_somatic

        Get interpretation somatic
        """
        pass

    def test_get_interpretation_somatic_deprecated(self) -> None:
        """Test case for get_interpretation_somatic_deprecated

        Get interpretation somatic
        """
        pass

    def test_get_pubmed_citation(self) -> None:
        """Test case for get_pubmed_citation

        Get pubmed citation by ID
        """
        pass

    def test_post_interpretation_germline(self) -> None:
        """Test case for post_interpretation_germline

        Create or Update interpretation germline
        """
        pass

    def test_post_interpretation_germline_deprecated(self) -> None:
        """Test case for post_interpretation_germline_deprecated

        Create or Update interpretation germline
        """
        pass

    def test_post_interpretation_somatic(self) -> None:
        """Test case for post_interpretation_somatic

        Create or Update interpretation somatic
        """
        pass

    def test_post_interpretation_somatic_deprecated(self) -> None:
        """Test case for post_interpretation_somatic_deprecated

        Create or Update interpretation somatic
        """
        pass

    def test_search_interpretation_germline(self) -> None:
        """Test case for search_interpretation_germline

        Search interpretation germline
        """
        pass

    def test_search_interpretation_somatic(self) -> None:
        """Test case for search_interpretation_somatic

        Search interpretation somatic
        """
        pass


if __name__ == '__main__':
    unittest.main()
