# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.case_sequencing_request_batch import CaseSequencingRequestBatch

class TestCaseSequencingRequestBatch(unittest.TestCase):
    """CaseSequencingRequestBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseSequencingRequestBatch:
        """Test CaseSequencingRequestBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseSequencingRequestBatch`
        """
        model = CaseSequencingRequestBatch()
        if include_optional:
            return CaseSequencingRequestBatch(
                patient_organization_code = '',
                service_code = '',
                status_code = '',
                submitter_patient_id = '',
                submitter_sequencing_request_id = ''
            )
        else:
            return CaseSequencingRequestBatch(
                patient_organization_code = '',
                service_code = '',
                status_code = '',
                submitter_patient_id = '',
                submitter_sequencing_request_id = '',
        )
        """

    def testCaseSequencingRequestBatch(self):
        """Test CaseSequencingRequestBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
