# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.variant_overview import VariantOverview

class TestVariantOverview(unittest.TestCase):
    """VariantOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantOverview:
        """Test VariantOverview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantOverview`
        """
        model = VariantOverview()
        if include_optional:
            return VariantOverview(
                aa_change = '',
                cadd_phred = 1.337,
                cadd_score = 1.337,
                clinvar = [
                    ''
                    ],
                clinvar_name = '',
                dann_score = 1.337,
                dna_change = '',
                exomiser_acmg_classification_counts = {
                    'key' : 56
                    },
                exon_rank = 56,
                exon_total = 56,
                fathmm_pred = '',
                fathmm_score = 1.337,
                gnomad_loeuf = 1.337,
                gnomad_pli = 1.337,
                gnomad_v3_af = 1.337,
                interpretation_classification_counts = {
                    'key' : 56
                    },
                is_canonical = True,
                is_mane_plus = True,
                is_mane_select = True,
                locus = '',
                lrt_pred = '',
                lrt_score = 1.337,
                omim_conditions = [
                    radiant_python.models.omim_gene_panel.OmimGenePanel(
                        inheritance_code = [
                            ''
                            ], 
                        omim_phenotype_id = '', 
                        panel = '', )
                    ],
                pc_wgs = 56,
                pf_wgs = 1.337,
                phylo_p17way_primate = 1.337,
                picked_consequences = [
                    ''
                    ],
                pn_wgs = 56,
                polyphen2_hvar_pred = '',
                polyphen2_hvar_score = 1.337,
                revel_score = 1.337,
                rsnumber = '',
                sift_pred = '',
                sift_score = 1.337,
                spliceai_ds = 1.337,
                spliceai_type = [
                    ''
                    ],
                symbol = '',
                transcript_id = '',
                vep_impact = 'MODIFIER'
            )
        else:
            return VariantOverview(
                gnomad_v3_af = 1.337,
                is_canonical = True,
                is_mane_plus = True,
                is_mane_select = True,
                locus = '',
                pf_wgs = 1.337,
                picked_consequences = [
                    ''
                    ],
        )
        """

    def testVariantOverview(self):
        """Test VariantOverview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
