# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.beacon_configuration_response import BeaconConfigurationResponse

class TestBeaconConfigurationResponse(unittest.TestCase):
    """BeaconConfigurationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeaconConfigurationResponse:
        """Test BeaconConfigurationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeaconConfigurationResponse`
        """
        model = BeaconConfigurationResponse()
        if include_optional:
            return BeaconConfigurationResponse(
                meta = radiant_python.models.beacon_meta.BeaconMeta(
                    api_version = '', 
                    beacon_id = '', 
                    received_request_summary = radiant_python.models.beacon_received_request_summary.BeaconReceivedRequestSummary(
                        api_version = '', 
                        filters = [
                            ''
                            ], 
                        include_resultset_responses = '', 
                        pagination = radiant_python.models.beacon_pagination.BeaconPagination(
                            limit = 56, 
                            skip = 56, ), 
                        request_parameters = {
                            'key' : null
                            }, 
                        requested_granularity = '', 
                        requested_schemas = [
                            radiant_python.models.beacon_schema_reference.BeaconSchemaReference(
                                entity_type = '', 
                                schema = '', )
                            ], 
                        test_mode = True, ), 
                    returned_granularity = '', 
                    returned_schemas = [
                        radiant_python.models.beacon_schema_reference.BeaconSchemaReference(
                            entity_type = '', 
                            schema = '', )
                        ], ),
                response = radiant_python.models.beacon_configuration.BeaconConfiguration(
                    __schema = '', 
                    entry_types = {
                        'key' : radiant_python.models.beacon_entry_type.BeaconEntryType(
                            default_schema = radiant_python.models.beacon_schema_def.BeaconSchemaDef(
                                id = '', 
                                name = '', 
                                reference_to_schema_definition = '', 
                                schema_version = '', ), 
                            description = '', 
                            id = '', 
                            name = '', 
                            non_filtered_queries_allowed = True, 
                            ontology_term_for_this_type = radiant_python.models.beacon_ontology_term.BeaconOntologyTerm(
                                id = '', 
                                label = '', ), 
                            part_of_specification = '', )
                        }, 
                    maturity_attributes = radiant_python.models.beacon_maturity_attributes.BeaconMaturityAttributes(
                        production_status = '', ), 
                    security_attributes = radiant_python.models.beacon_security_attributes.BeaconSecurityAttributes(
                        default_granularity = '', 
                        description = '', 
                        security_levels = [
                            ''
                            ], ), )
            )
        else:
            return BeaconConfigurationResponse(
        )
        """

    def testBeaconConfigurationResponse(self):
        """Test BeaconConfigurationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
