# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant-python.models.saved_filter import SavedFilter

class TestSavedFilter(unittest.TestCase):
    """SavedFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavedFilter:
        """Test SavedFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavedFilter`
        """
        model = SavedFilter()
        if include_optional:
            return SavedFilter(
                created_on = '',
                favorite = True,
                id = '',
                name = '',
                queries = [
                    radiant-python.models.sqon.Sqon(
                        content = null, 
                        id = '', 
                        op = 'in', )
                    ],
                type = 'germline_snv_occurrence',
                updated_on = '',
                user_id = ''
            )
        else:
            return SavedFilter(
                created_on = '',
                favorite = True,
                id = '',
                name = '',
                queries = [
                    radiant-python.models.sqon.Sqon(
                        content = null, 
                        id = '', 
                        op = 'in', )
                    ],
                type = 'germline_snv_occurrence',
                updated_on = '',
                user_id = '',
        )
        """

    def testSavedFilter(self):
        """Test SavedFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
