# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.variant_internal_frequencies import VariantInternalFrequencies

class TestVariantInternalFrequencies(unittest.TestCase):
    """VariantInternalFrequencies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantInternalFrequencies:
        """Test VariantInternalFrequencies
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantInternalFrequencies`
        """
        model = VariantInternalFrequencies()
        if include_optional:
            return VariantInternalFrequencies(
                split_rows = [
                    radiant_python.models.internal_frequencies_split_by.InternalFrequenciesSplitBy(
                        frequencies = radiant_python.models.internal_frequencies.InternalFrequencies(
                            hom_affected = 56, 
                            hom_all = 56, 
                            hom_non_affected = 56, 
                            pc_affected = 56, 
                            pc_all = 56, 
                            pc_non_affected = 56, 
                            pf_affected = 1.337, 
                            pf_all = 1.337, 
                            pf_non_affected = 1.337, 
                            pn_affected = 56, 
                            pn_all = 56, 
                            pn_non_affected = 56, ), 
                        split_value = '', )
                    ],
                total_frequencies = radiant_python.models.internal_frequencies.InternalFrequencies(
                    hom_affected = 56, 
                    hom_all = 56, 
                    hom_non_affected = 56, 
                    pc_affected = 56, 
                    pc_all = 56, 
                    pc_non_affected = 56, 
                    pf_affected = 1.337, 
                    pf_all = 1.337, 
                    pf_non_affected = 1.337, 
                    pn_affected = 56, 
                    pn_all = 56, 
                    pn_non_affected = 56, )
            )
        else:
            return VariantInternalFrequencies(
                split_rows = [
                    radiant_python.models.internal_frequencies_split_by.InternalFrequenciesSplitBy(
                        frequencies = radiant_python.models.internal_frequencies.InternalFrequencies(
                            hom_affected = 56, 
                            hom_all = 56, 
                            hom_non_affected = 56, 
                            pc_affected = 56, 
                            pc_all = 56, 
                            pc_non_affected = 56, 
                            pf_affected = 1.337, 
                            pf_all = 1.337, 
                            pf_non_affected = 1.337, 
                            pn_affected = 56, 
                            pn_all = 56, 
                            pn_non_affected = 56, ), 
                        split_value = '', )
                    ],
                total_frequencies = radiant_python.models.internal_frequencies.InternalFrequencies(
                    hom_affected = 56, 
                    hom_all = 56, 
                    hom_non_affected = 56, 
                    pc_affected = 56, 
                    pc_all = 56, 
                    pc_non_affected = 56, 
                    pf_affected = 1.337, 
                    pf_all = 1.337, 
                    pf_non_affected = 1.337, 
                    pn_affected = 56, 
                    pn_all = 56, 
                    pn_non_affected = 56, ),
        )
        """

    def testVariantInternalFrequencies(self):
        """Test VariantInternalFrequencies"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
