# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.somatic_cnv_occurrence import SomaticCNVOccurrence

class TestSomaticCNVOccurrence(unittest.TestCase):
    """SomaticCNVOccurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SomaticCNVOccurrence:
        """Test SomaticCNVOccurrence
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SomaticCNVOccurrence`
        """
        model = SomaticCNVOccurrence()
        if include_optional:
            return SomaticCNVOccurrence(
                aliquot = '',
                ascn_as = 56,
                bc = 56,
                calls = [
                    56
                    ],
                chromosome = '',
                ciend = [
                    56
                    ],
                cipos = [
                    56
                    ],
                cn = 56,
                cnf = 1.337,
                cnq = 1.337,
                cnv_id = '',
                cytoband = [
                    ''
                    ],
                end = 56,
                filter = '',
                flag_type = 'flag',
                gnomad_sc = 56,
                gnomad_sf = 1.337,
                gnomad_sn = 56,
                has_note = True,
                length = 56,
                maf = 1.337,
                mcn = 56,
                mcnf = 1.337,
                mcnq = 1.337,
                name = '',
                nb_genes = 56,
                nb_snv = 56,
                pe = [
                    56
                    ],
                quality = 1.337,
                reflen = 56,
                sd = 1.337,
                seq_id = 56,
                sm = 1.337,
                start = 56,
                svlen = 56,
                svtype = '',
                symbol = [
                    ''
                    ],
                task_id = 56,
                type = 'GAIN'
            )
        else:
            return SomaticCNVOccurrence(
                chromosome = '',
                cnv_id = '',
                end = 56,
                has_note = True,
                length = 56,
                name = '',
                seq_id = 56,
                start = 56,
                task_id = 56,
                type = 'GAIN',
        )
        """

    def testSomaticCNVOccurrence(self):
        """Test SomaticCNVOccurrence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
