# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.table_config import TableConfig

class TestTableConfig(unittest.TestCase):
    """TableConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableConfig:
        """Test TableConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableConfig`
        """
        model = TableConfig()
        if include_optional:
            return TableConfig(
                column_order = [
                    ''
                    ],
                column_pinning = radiant_python.models.column_pinning_config.ColumnPinningConfig(
                    left = [
                        ''
                        ], 
                    right = [
                        ''
                        ], ),
                column_sizing = {
                    'key' : 56
                    },
                column_visibility = {
                    'key' : True
                    },
                pagination = radiant_python.models.pagination_config.PaginationConfig(
                    page_size = 56, )
            )
        else:
            return TableConfig(
        )
        """

    def testTableConfig(self):
        """Test TableConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
