# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.api.case_groups_api import CaseGroupsApi


class TestCaseGroupsApi(unittest.TestCase):
    """CaseGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_case_group(self) -> None:
        """Test case for create_case_group

        Create or overwrite a case group
        """
        pass

    def test_get_case_group(self) -> None:
        """Test case for get_case_group

        Get a case group
        """
        pass


if __name__ == '__main__':
    unittest.main()
