# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.task_occurrence_type import TaskOccurrenceType

class TestTaskOccurrenceType(unittest.TestCase):
    """TaskOccurrenceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskOccurrenceType:
        """Test TaskOccurrenceType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskOccurrenceType`
        """
        model = TaskOccurrenceType()
        if include_optional:
            return TaskOccurrenceType(
                created_on = '',
                genome_build = '',
                id = 56,
                pipeline_name = '',
                pipeline_version = '',
                task_type_code = '',
                task_type_name = ''
            )
        else:
            return TaskOccurrenceType(
        )
        """

    def testTaskOccurrenceType(self):
        """Test TaskOccurrenceType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
