# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.gene_panel_upload_warning import GenePanelUploadWarning

class TestGenePanelUploadWarning(unittest.TestCase):
    """GenePanelUploadWarning unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenePanelUploadWarning:
        """Test GenePanelUploadWarning
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenePanelUploadWarning`
        """
        model = GenePanelUploadWarning()
        if include_optional:
            return GenePanelUploadWarning(
                line = 56,
                message = '',
                panel_code = '',
                symbol = ''
            )
        else:
            return GenePanelUploadWarning(
        )
        """

    def testGenePanelUploadWarning(self):
        """Test GenePanelUploadWarning"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
