# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant-python.models.filters_body_with_criteria import FiltersBodyWithCriteria

class TestFiltersBodyWithCriteria(unittest.TestCase):
    """FiltersBodyWithCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiltersBodyWithCriteria:
        """Test FiltersBodyWithCriteria
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiltersBodyWithCriteria`
        """
        model = FiltersBodyWithCriteria()
        if include_optional:
            return FiltersBodyWithCriteria(
                search_criteria = [
                    radiant-python.models.search_criterion.SearchCriterion(
                        field = '', 
                        operator = '', 
                        value = [
                            null
                            ], )
                    ]
            )
        else:
            return FiltersBodyWithCriteria(
        )
        """

    def testFiltersBodyWithCriteria(self):
        """Test FiltersBodyWithCriteria"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
