# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.api.mondo_api import MondoApi


class TestMondoApi(unittest.TestCase):
    """MondoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MondoApi()

    def tearDown(self) -> None:
        pass

    def test_mondo_term_auto_complete(self) -> None:
        """Test case for mondo_term_auto_complete

        Get AutoCompleteTerm list of matching input string with highlighted
        """
        pass


if __name__ == '__main__':
    unittest.main()
