# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.case_fetus_batch import CaseFetusBatch

class TestCaseFetusBatch(unittest.TestCase):
    """CaseFetusBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseFetusBatch:
        """Test CaseFetusBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseFetusBatch`
        """
        model = CaseFetusBatch()
        if include_optional:
            return CaseFetusBatch(
                affected_status_code = 'affected',
                estimated_due_date = '2026-11-08',
                last_menstrual_period = '2026-02-01',
                life_status_code = 'alive',
                observations_categorical = [
                    radiant_python.models.observation_categorical_batch.ObservationCategoricalBatch(
                        code = '', 
                        exam_code = '', 
                        interpretation_code = 'positive', 
                        note = '', 
                        onset_code = '', 
                        system = '', 
                        value = '', )
                    ],
                observations_text = [
                    radiant_python.models.observation_text_batch.ObservationTextBatch(
                        code = '', 
                        exam_code = '', 
                        interpretation_code = 'positive', 
                        value = '', )
                    ],
                sex_code = 'male'
            )
        else:
            return CaseFetusBatch(
                affected_status_code = 'affected',
                life_status_code = 'alive',
                sex_code = 'male',
        )
        """

    def testCaseFetusBatch(self):
        """Test CaseFetusBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
