# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from radiant_python.models.create_occurrence_note_input import CreateOccurrenceNoteInput

class TestCreateOccurrenceNoteInput(unittest.TestCase):
    """CreateOccurrenceNoteInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOccurrenceNoteInput:
        """Test CreateOccurrenceNoteInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOccurrenceNoteInput`
        """
        model = CreateOccurrenceNoteInput()
        if include_optional:
            return CreateOccurrenceNoteInput(
                case_id = 56,
                content = '',
                occurrence_id = 56,
                seq_id = 56,
                task_id = 56
            )
        else:
            return CreateOccurrenceNoteInput(
                case_id = 56,
                content = '',
                occurrence_id = 56,
                seq_id = 56,
                task_id = 56,
        )
        """

    def testCreateOccurrenceNoteInput(self):
        """Test CreateOccurrenceNoteInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
