# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ClinvarRCV(BaseModel):
    """
    ClinvarRCV represents a Reference ClinVar record - data aggregated by variant-condition pair
    """ # noqa: E501
    accession: Optional[StrictStr] = None
    clinical_significance: Optional[List[StrictStr]] = None
    clinvar_id: StrictStr
    date_last_evaluated: Optional[StrictStr] = None
    locus_id: StrictStr
    origins: Optional[List[StrictStr]] = None
    review_status: Optional[StrictStr] = None
    review_status_stars: Optional[StrictInt] = None
    submission_count: Optional[StrictInt] = None
    traits: Optional[List[StrictStr]] = None
    version: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["accession", "clinical_significance", "clinvar_id", "date_last_evaluated", "locus_id", "origins", "review_status", "review_status_stars", "submission_count", "traits", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClinvarRCV from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClinvarRCV from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accession": obj.get("accession"),
            "clinical_significance": obj.get("clinical_significance"),
            "clinvar_id": obj.get("clinvar_id"),
            "date_last_evaluated": obj.get("date_last_evaluated"),
            "locus_id": obj.get("locus_id"),
            "origins": obj.get("origins"),
            "review_status": obj.get("review_status"),
            "review_status_stars": obj.get("review_status_stars"),
            "submission_count": obj.get("submission_count"),
            "traits": obj.get("traits"),
            "version": obj.get("version")
        })
        return _obj


