# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.batch_report import BatchReport
from openapi_client.models.batch_summary import BatchSummary
from typing import Optional, Set
from typing_extensions import Self

class GetBatchResponse(BaseModel):
    """
    GetBatchResponse represents the response returned when retrieving a batch
    """ # noqa: E501
    batch_type: Optional[StrictStr] = None
    created_on: Optional[StrictStr] = None
    dry_run: Optional[StrictBool] = None
    finished_on: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    report: Optional[BatchReport] = None
    started_on: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    summary: Optional[BatchSummary] = None
    username: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["batch_type", "created_on", "dry_run", "finished_on", "id", "report", "started_on", "status", "summary", "username"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBatchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of report
        if self.report:
            _dict['report'] = self.report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBatchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batch_type": obj.get("batch_type"),
            "created_on": obj.get("created_on"),
            "dry_run": obj.get("dry_run"),
            "finished_on": obj.get("finished_on"),
            "id": obj.get("id"),
            "report": BatchReport.from_dict(obj["report"]) if obj.get("report") is not None else None,
            "started_on": obj.get("started_on"),
            "status": obj.get("status"),
            "summary": BatchSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "username": obj.get("username")
        })
        return _obj


