# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.interpretation_metadata import InterpretationMetadata
from openapi_client.models.interpretation_pubmed import InterpretationPubmed
from typing import Optional, Set
from typing_extensions import Self

class InterpretationGermline(BaseModel):
    """
    InterpretationGermline
    """ # noqa: E501
    case_id: Optional[StrictStr] = None
    classification: Optional[StrictStr] = None
    classification_criterias: Optional[List[StrictStr]] = None
    condition: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    created_by: Optional[StrictStr] = None
    created_by_name: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    interpretation: Optional[StrictStr] = None
    locus_id: Optional[StrictStr] = None
    metadata: Optional[InterpretationMetadata] = None
    pubmed: Optional[List[InterpretationPubmed]] = None
    sequencing_id: Optional[StrictStr] = None
    transcript_id: Optional[StrictStr] = None
    transmission_modes: Optional[List[StrictStr]] = None
    updated_at: Optional[StrictStr] = None
    updated_by: Optional[StrictStr] = None
    updated_by_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["case_id", "classification", "classification_criterias", "condition", "created_at", "created_by", "created_by_name", "id", "interpretation", "locus_id", "metadata", "pubmed", "sequencing_id", "transcript_id", "transmission_modes", "updated_at", "updated_by", "updated_by_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InterpretationGermline from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pubmed (list)
        _items = []
        if self.pubmed:
            for _item_pubmed in self.pubmed:
                if _item_pubmed:
                    _items.append(_item_pubmed.to_dict())
            _dict['pubmed'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InterpretationGermline from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "case_id": obj.get("case_id"),
            "classification": obj.get("classification"),
            "classification_criterias": obj.get("classification_criterias"),
            "condition": obj.get("condition"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "created_by_name": obj.get("created_by_name"),
            "id": obj.get("id"),
            "interpretation": obj.get("interpretation"),
            "locus_id": obj.get("locus_id"),
            "metadata": InterpretationMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "pubmed": [InterpretationPubmed.from_dict(_item) for _item in obj["pubmed"]] if obj.get("pubmed") is not None else None,
            "sequencing_id": obj.get("sequencing_id"),
            "transcript_id": obj.get("transcript_id"),
            "transmission_modes": obj.get("transmission_modes"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "updated_by_name": obj.get("updated_by_name")
        })
        return _obj


