# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SavedFilterType(str, Enum):
    """
    SavedFilterType
    """

    """
    allowed enum values
    """
    GERMLINE_SNV_OCCURRENCE = 'germline_snv_occurrence'
    GERMLINE_CNV_OCCURRENCE = 'germline_cnv_occurrence'
    SOMATIC_SNV_OCCURRENCE = 'somatic_snv_occurrence'
    SOMATIC_CNV_OCCURRENCE = 'somatic_cnv_occurrence'
    GERMLINE_SNV_VARIANT = 'germline_snv_variant'
    GERMLINE_CNV_VARIANT = 'germline_cnv_variant'
    SOMATIC_SNV_VARIANT = 'somatic_snv_variant'
    SOMATIC_CNV_VARIANT = 'somatic_cnv_variant'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SavedFilterType from a JSON string"""
        return cls(json.loads(json_str))


