# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing_extensions import Annotated

from radiant_python.api_client import ApiClient, RequestSerialized
from radiant_python.api_response import ApiResponse
from radiant_python.rest import RESTResponseType


class OccurrenceFlagsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def upsert_occurrence_flag(
        self,
        case_id: Annotated[StrictInt, Field(description="Case ID")],
        seq_id: Annotated[StrictInt, Field(description="Seq ID")],
        task_id: Annotated[StrictInt, Field(description="Task ID")],
        occurrence_id: Annotated[StrictStr, Field(description="Occurrence ID")],
        flag_type: Annotated[StrictStr, Field(description="Flag to set")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Set or change the flag on an occurrence

        Upserts the flag for a given (case_id, occurrence_id, seq_id, task_id). An occurrence has at most one flag per case.

        :param case_id: Case ID (required)
        :type case_id: int
        :param seq_id: Seq ID (required)
        :type seq_id: int
        :param task_id: Task ID (required)
        :type task_id: int
        :param occurrence_id: Occurrence ID (required)
        :type occurrence_id: str
        :param flag_type: Flag to set (required)
        :type flag_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._upsert_occurrence_flag_serialize(
            case_id=case_id,
            seq_id=seq_id,
            task_id=task_id,
            occurrence_id=occurrence_id,
            flag_type=flag_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ApiError",
            '401': "ApiError",
            '500': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def upsert_occurrence_flag_with_http_info(
        self,
        case_id: Annotated[StrictInt, Field(description="Case ID")],
        seq_id: Annotated[StrictInt, Field(description="Seq ID")],
        task_id: Annotated[StrictInt, Field(description="Task ID")],
        occurrence_id: Annotated[StrictStr, Field(description="Occurrence ID")],
        flag_type: Annotated[StrictStr, Field(description="Flag to set")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Set or change the flag on an occurrence

        Upserts the flag for a given (case_id, occurrence_id, seq_id, task_id). An occurrence has at most one flag per case.

        :param case_id: Case ID (required)
        :type case_id: int
        :param seq_id: Seq ID (required)
        :type seq_id: int
        :param task_id: Task ID (required)
        :type task_id: int
        :param occurrence_id: Occurrence ID (required)
        :type occurrence_id: str
        :param flag_type: Flag to set (required)
        :type flag_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._upsert_occurrence_flag_serialize(
            case_id=case_id,
            seq_id=seq_id,
            task_id=task_id,
            occurrence_id=occurrence_id,
            flag_type=flag_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ApiError",
            '401': "ApiError",
            '500': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def upsert_occurrence_flag_without_preload_content(
        self,
        case_id: Annotated[StrictInt, Field(description="Case ID")],
        seq_id: Annotated[StrictInt, Field(description="Seq ID")],
        task_id: Annotated[StrictInt, Field(description="Task ID")],
        occurrence_id: Annotated[StrictStr, Field(description="Occurrence ID")],
        flag_type: Annotated[StrictStr, Field(description="Flag to set")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Set or change the flag on an occurrence

        Upserts the flag for a given (case_id, occurrence_id, seq_id, task_id). An occurrence has at most one flag per case.

        :param case_id: Case ID (required)
        :type case_id: int
        :param seq_id: Seq ID (required)
        :type seq_id: int
        :param task_id: Task ID (required)
        :type task_id: int
        :param occurrence_id: Occurrence ID (required)
        :type occurrence_id: str
        :param flag_type: Flag to set (required)
        :type flag_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._upsert_occurrence_flag_serialize(
            case_id=case_id,
            seq_id=seq_id,
            task_id=task_id,
            occurrence_id=occurrence_id,
            flag_type=flag_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "ApiError",
            '401': "ApiError",
            '500': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _upsert_occurrence_flag_serialize(
        self,
        case_id,
        seq_id,
        task_id,
        occurrence_id,
        flag_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if case_id is not None:
            _path_params['case_id'] = case_id
        if seq_id is not None:
            _path_params['seq_id'] = seq_id
        if task_id is not None:
            _path_params['task_id'] = task_id
        if occurrence_id is not None:
            _path_params['occurrence_id'] = occurrence_id
        # process the query parameters
        if flag_type is not None:
            
            _query_params.append(('flag_type', flag_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerauth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/occurrences/flags/{case_id}/{seq_id}/{task_id}/{occurrence_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


