import { HttpResponse } from 'msw';

import { BASE_URL } from './constant';

export const caseFiltersApi = `${BASE_URL}api/cases/filters`;
export const caseSearchApi = `${BASE_URL}api/cases/search`;
export const caseAutocomplete = `${BASE_URL}api/cases/autocomplete`;

export async function httpCaseSearchApiResponse() {
  return HttpResponse.json({
    list: [
      {
        case_id: 1,
        proband_id: 3,
        submitter_proband_id: 'MRN-283775',
        priority_code: 'routine',
        status_code: 'in_progress',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Felix Laflamme',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: true,
      },
      {
        case_id: 2,
        proband_id: 4,
        submitter_proband_id: 'MRN-283776',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Melissa Lopez',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 3,
        proband_id: 8,
        submitter_proband_id: 'MRN-283780',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Christopher Watson',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 4,
        proband_id: 10,
        submitter_proband_id: 'MRN-283782',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Victoria Breton',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 5,
        proband_id: 15,
        submitter_proband_id: 'MRN-283787',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Antoine Paré',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 6,
        proband_id: 16,
        submitter_proband_id: 'MRN-283788',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Jonathan Frye',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 7,
        proband_id: 20,
        submitter_proband_id: 'MRN-283792',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Dawn Taylor',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 8,
        proband_id: 22,
        submitter_proband_id: 'MRN-283794',
        priority_code: 'routine',
        status_code: 'completed',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Lauren Maxwell',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: true,
      },
      {
        case_id: 9,
        proband_id: 23,
        submitter_proband_id: 'MRN-283795',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Elliot Duchesne',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 10,
        proband_id: 27,
        submitter_proband_id: 'MRN-283799',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Alex Williams',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 11,
        proband_id: 30,
        submitter_proband_id: 'MRN-283802',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Arthur Séguin',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 12,
        proband_id: 34,
        submitter_proband_id: 'MRN-283806',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Raphaelle Veilleux',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 13,
        proband_id: 37,
        submitter_proband_id: 'MRN-283809',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Louis Stevens',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 14,
        proband_id: 39,
        submitter_proband_id: 'MRN-283811',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Sarah Gervais',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 15,
        proband_id: 42,
        submitter_proband_id: 'MRN-283814',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Xavier Peterson',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 16,
        proband_id: 44,
        submitter_proband_id: 'MRN-283816',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Jeanne Laroche',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 17,
        proband_id: 47,
        submitter_proband_id: 'MRN-283819',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Arnaud Morissette',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 18,
        proband_id: 50,
        submitter_proband_id: 'MRN-283822',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Sophia Charron',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 19,
        proband_id: 55,
        submitter_proband_id: 'MRN-283827',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Ethan Reid',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 20,
        proband_id: 58,
        submitter_proband_id: 'MRN-283830',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Leonie Laplante',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
    ],
    count: 21,
  });
}

export async function httpCaseFiltersApiResponse() {
  return HttpResponse.json({
    status_code: [
      {
        key: 'completed',
        label: 'Completed',
        count: 0,
      },
      {
        key: 'draft',
        label: 'Draft',
        count: 0,
      },
      {
        key: 'in_progress',
        label: 'In Progress',
        count: 0,
      },
      {
        key: 'incomplete',
        label: 'Incomplete',
        count: 0,
      },
      {
        key: 'revoke',
        label: 'Revoke',
        count: 0,
      },
      {
        key: 'submitted',
        label: 'Submitted',
        count: 0,
      },
      {
        key: 'unknown',
        label: 'Unknown',
        count: 0,
      },
    ],
    priority_code: [
      {
        key: 'asap',
        label: 'Asap',
        count: 0,
      },
      {
        key: 'routine',
        label: 'Routine',
        count: 0,
      },
      {
        key: 'stat',
        label: 'Stat',
        count: 0,
      },
      {
        key: 'urgent',
        label: 'Urgent',
        count: 0,
      },
    ],
    analysis_catalog_code: [
      {
        key: 'HYPM',
        label: 'Malignant Hyperthermia',
        count: 0,
      },
      {
        key: 'IDGD',
        label: 'Intellectual Deficiency and Global Developmental Delay',
        count: 0,
      },
      {
        key: 'MYOC',
        label: 'Congenital Myopathies',
        count: 0,
      },
      {
        key: 'WGA',
        label: 'Whole Genome Analysis',
        count: 0,
      },
    ],
    project_code: [
      {
        key: 'N1',
        label: 'NeuroDev Phase I',
        count: 0,
      },
      {
        key: 'N2',
        label: 'NeuroDev Phase II',
        count: 0,
      },
    ],
    diagnosis_lab_code: [
      {
        key: 'LDM-CHOP',
        label: 'Molecular Diagnostic Laboratory, CHOP',
        count: 0,
      },
      {
        key: 'LDM-CHUSJ',
        label: 'Laboratoire de diagnostic moléculaire, CHU Sainte-Justine',
        count: 0,
      },
    ],
    ordering_organization_code: [
      {
        key: 'CHOP',
        label: 'Children Hospital of Philadelphia',
        count: 0,
      },
      {
        key: 'CHUSJ',
        label: 'Centre hospitalier universitaire Sainte-Justine',
        count: 0,
      },
      {
        key: 'CQGC',
        label: 'Quebec Clinical Genomic Center',
        count: 0,
      },
      {
        key: 'LDM-CHOP',
        label: 'Molecular Diagnostic Laboratory, CHOP',
        count: 0,
      },
      {
        key: 'LDM-CHUSJ',
        label: 'Laboratoire de diagnostic moléculaire, CHU Sainte-Justine',
        count: 0,
      },
      {
        key: 'UCSF',
        label: 'University of California San-Francisco',
        count: 0,
      },
    ],
    resolution_status_code: [
      {
        key: 'inconclusive',
        label: 'Inconclusive',
        count: 0,
      },
      {
        key: 'solved',
        label: 'Solved',
        count: 0,
      },
      {
        key: 'unsolved',
        label: 'Unsolved',
        count: 0,
      },
    ],
    panel_code: [],
    life_status_code: [
      {
        key: 'alive',
        label: 'Alive',
        count: 0,
      },
      {
        key: 'deceased',
        label: 'Deceased',
        count: 0,
      },
      {
        key: 'unknown',
        label: 'Unknown',
        count: 0,
      },
    ],
    case_category_code: [
      {
        key: 'postnatal',
        label: 'Postnatal',
        count: 0,
      },
      {
        key: 'prenatal',
        label: 'Prenatal',
        count: 0,
      },
    ],
    case_type_code: [
      {
        key: 'germline',
        label: 'Germline',
        count: 0,
      },
      {
        key: 'somatic',
        label: 'Somatic',
        count: 0,
      },
    ],
  });
}

export async function httpCaseAutocompleteResponse() {
  return HttpResponse.json([
    {
      type: 'case_id',
      value: '1',
    },
    {
      type: 'case_id',
      value: '10',
    },
    {
      type: 'patient_id',
      value: '10',
    },
    {
      type: 'case_id',
      value: '11',
    },
    {
      type: 'case_id',
      value: '12',
    },
    {
      type: 'case_id',
      value: '13',
    },
    {
      type: 'case_id',
      value: '14',
    },
    {
      type: 'case_id',
      value: '15',
    },
    {
      type: 'patient_id',
      value: '15',
    },
    {
      type: 'case_id',
      value: '16',
    },
  ]);
}
