import { HttpResponse } from 'msw';

export const caseFiltersApi = '/api/cases/filters';
export const caseSearchApi = '/api/cases/search';
export const caseAutocomplete = 'api/cases/autocomplete';

export async function httpCaseSearchApiResponse() {
  return HttpResponse.json({
    list: [
      {
        case_id: 1,
        proband_id: 3,
        proband_organization_id: 'MRN-283775',
        priority_code: 'routine',
        status_code: 'in_progress',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Felix Laflamme',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 1,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: true,
      },
      {
        case_id: 2,
        proband_id: 4,
        proband_organization_id: 'MRN-283776',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Melissa Lopez',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 2,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 3,
        proband_id: 8,
        proband_organization_id: 'MRN-283780',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Christopher Watson',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 3,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 4,
        proband_id: 10,
        proband_organization_id: 'MRN-283782',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Victoria Breton',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 4,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 5,
        proband_id: 15,
        proband_organization_id: 'MRN-283787',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Antoine Paré',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 5,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 6,
        proband_id: 16,
        proband_organization_id: 'MRN-283788',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Jonathan Frye',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 6,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 7,
        proband_id: 20,
        proband_organization_id: 'MRN-283792',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Dawn Taylor',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 7,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 8,
        proband_id: 22,
        proband_organization_id: 'MRN-283794',
        priority_code: 'routine',
        status_code: 'completed',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Lauren Maxwell',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 8,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: true,
      },
      {
        case_id: 9,
        proband_id: 23,
        proband_organization_id: 'MRN-283795',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N1',
        project_name: 'NeuroDev Phase I',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Elliot Duchesne',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 9,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 10,
        proband_id: 27,
        proband_organization_id: 'MRN-283799',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Alex Williams',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 10,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 11,
        proband_id: 30,
        proband_organization_id: 'MRN-283802',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Arthur Séguin',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 11,
        organization_code: 'CHUSJ',
        organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        has_variants: false,
      },
      {
        case_id: 12,
        proband_id: 34,
        proband_organization_id: 'MRN-283806',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Raphaelle Veilleux',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 12,
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 13,
        proband_id: 37,
        proband_organization_id: 'MRN-283809',
        priority_code: 'routine',
        status_code: 'incomplete',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Louis Stevens',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 13,
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 14,
        proband_id: 39,
        proband_organization_id: 'MRN-283811',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Sarah Gervais',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 14,
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 15,
        proband_id: 42,
        proband_organization_id: 'MRN-283814',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Xavier Peterson',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 15,
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 16,
        proband_id: 44,
        proband_organization_id: 'MRN-283816',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'WGA',
        analysis_catalog_name: 'Whole Genome Analysis',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Jeanne Laroche',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 16,
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 17,
        proband_id: 47,
        proband_organization_id: 'MRN-283819',
        priority_code: 'routine',
        status_code: 'draft',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Arnaud Morissette',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 17,
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 18,
        proband_id: 50,
        proband_organization_id: 'MRN-283822',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Sophia Charron',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 18,
        organization_code: 'CHOP',
        organization_name: 'Children Hospital of Philadelphia',
        has_variants: false,
      },
      {
        case_id: 19,
        proband_id: 55,
        proband_organization_id: 'MRN-283827',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Ethan Reid',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 19,
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
      {
        case_id: 20,
        proband_id: 58,
        proband_organization_id: 'MRN-283830',
        priority_code: 'routine',
        status_code: 'revoke',
        analysis_catalog_code: 'IDGD',
        analysis_catalog_name: 'Intellectual Deficiency and Global Developmental Delay',
        case_type: 'germline_family',
        primary_condition_id: 'MONDO:0700092',
        primary_condition_name: 'neurodevelopmental disorder',
        ordering_organization_code: 'CHUSJ',
        ordering_organization_name: 'Centre hospitalier universitaire Sainte-Justine',
        project_code: 'N2',
        project_name: 'NeuroDev Phase II',
        created_on: '2021-09-12T13:08:00Z',
        updated_on: '2021-09-12T13:08:00Z',
        prescriber: 'Leonie Laplante',
        diagnosis_lab_code: 'CQGC',
        diagnosis_lab_name: 'Quebec Clinical Genomic Center',
        request_id: 20,
        organization_code: 'UCSF',
        organization_name: 'University of California San-Francisco',
        has_variants: false,
      },
    ],
    count: 21,
  });
}

export async function httpCaseFiltersApiResponse() {
  return HttpResponse.json({
    status: [
      {
        key: 'incomplete',
        label: 'Incomplete',
        count: 10,
      },
      {
        key: 'draft',
        label: 'Draft',
        count: 5,
      },
      {
        key: 'revoke',
        label: 'Revoke',
        count: 4,
      },
      {
        key: 'completed',
        label: 'Completed',
        count: 1,
      },
      {
        key: 'in_progress',
        label: 'In Progress',
        count: 1,
      },
      {
        key: 'submitted',
        label: 'Submitted',
        count: 0,
      },
      {
        key: 'unknown',
        label: 'Unknown',
        count: 0,
      },
    ],
    priority: [
      {
        key: 'routine',
        label: 'Routine',
        count: 21,
      },
      {
        key: 'asap',
        label: 'Asap',
        count: 0,
      },
      {
        key: 'stat',
        label: 'Stat',
        count: 0,
      },
      {
        key: 'urgent',
        label: 'Urgent',
        count: 0,
      },
    ],
    case_analysis: [
      {
        key: 'WGA',
        label: 'Whole Genome Analysis',
        count: 13,
      },
      {
        key: 'IDGD',
        label: 'Intellectual Deficiency and Global Developmental Delay',
        count: 8,
      },
      {
        key: 'HYPM',
        label: 'Malignant Hyperthermia',
        count: 0,
      },
      {
        key: 'MYOC',
        label: 'Congenital Myopathies',
        count: 0,
      },
    ],
    project: [
      {
        key: 'N2',
        label: 'NeuroDev Phase II',
        count: 12,
      },
      {
        key: 'N1',
        label: 'NeuroDev Phase I',
        count: 9,
      },
    ],
    diagnosis_lab: [
      {
        key: 'CQGC',
        label: 'Quebec Clinical Genomic Center',
        count: 21,
      },
      {
        key: 'CHOP',
        label: 'Children Hospital of Philadelphia',
        count: 0,
      },
      {
        key: 'CHUSJ',
        label: 'Centre hospitalier universitaire Sainte-Justine',
        count: 0,
      },
      {
        key: 'LDM-CHOP',
        label: 'Molecular Diagnostic Laboratory, CHOP',
        count: 0,
      },
      {
        key: 'LDM-CHUSJ',
        label: 'Laboratoire de diagnostic moléculaire, CHU Sainte-Justine',
        count: 0,
      },
      {
        key: 'UCSF',
        label: 'University of California San-Francisco',
        count: 0,
      },
    ],
    ordering_organization: [
      {
        key: 'CHUSJ',
        label: 'Centre hospitalier universitaire Sainte-Justine',
        count: 21,
      },
      {
        key: 'CHOP',
        label: 'Children Hospital of Philadelphia',
        count: 0,
      },
      {
        key: 'CQGC',
        label: 'Quebec Clinical Genomic Center',
        count: 0,
      },
      {
        key: 'LDM-CHOP',
        label: 'Molecular Diagnostic Laboratory, CHOP',
        count: 0,
      },
      {
        key: 'LDM-CHUSJ',
        label: 'Laboratoire de diagnostic moléculaire, CHU Sainte-Justine',
        count: 0,
      },
      {
        key: 'UCSF',
        label: 'University of California San-Francisco',
        count: 0,
      },
    ],
  });
}

export async function httpCaseAutocompleteResponse() {
  return HttpResponse.json([
    {
      type: 'case_id',
      value: '1',
    },
    {
      type: 'case_id',
      value: '10',
    },
    {
      type: 'patient_id',
      value: '10',
    },
    {
      type: 'case_id',
      value: '11',
    },
    {
      type: 'case_id',
      value: '12',
    },
    {
      type: 'case_id',
      value: '13',
    },
    {
      type: 'case_id',
      value: '14',
    },
    {
      type: 'case_id',
      value: '15',
    },
    {
      type: 'patient_id',
      value: '15',
    },
    {
      type: 'case_id',
      value: '16',
    },
  ]);
}
