const globalData = {
  Authorization: {
    token: null, // Will be set by initializeGlobalData
  },
  BatchesId: {
    patientSuccess: '2c9ccf0e-cbc9-45b1-9eab-87d023bffd00',
    patientNotFound: '00000000-0000-0000-0000-000000000000',
  },
  Count: {
    //occurrences/germline/snv/{case_id}/{seq_id}/{task_id}/count
    //TODO: Waiting for stable data to restore the counts
    case_id: 1,
    seq_id: 1,
    snv: {
      task_id: 63,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: /\d{1}/,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'exomiser_gene_combined_score',
          value: '2.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'exomiser_acmg_classification',
          value: 'uncertain_significance',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'exomiser_acmg_evidence',
          value: 'BP4',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: /\d{1}/,
        },
      ],
      Frequency: [
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Occurrence: [
        {
          field: 'zygosity',
          value: 'HET',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'mother_zygosity',
          value: 'HET',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'father_zygosity',
          value: 'HET',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'parental_origin',
          value: 'BOTH',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'transmission_mode',
          value: 'autosomal_dominant',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'info_qd',
          value: '20',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'genotype_quality',
          value: '50',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: /\d{1}/,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: /\d{1}/,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: /\d{1}/,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: /\d{1}/,
          countAnd: /\d{1}/,
        },
      },
    },
    cnv: {
      task_id: 1,
      Variant: [
        {
          field: 'type',
          value: 'LOSS',
          op: 'in',
          count: 546,
        },
        {
          field: 'cn',
          value: '100',
          op: '<',
          count: 648,
        },
        {
          field: 'length',
          value: '100000',
          op: '<',
          count: 617,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 56,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'end',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'nb_snv',
          value: '10000',
          op: '<',
          count: 521,
        },
      ],
      Gene: [
        {
          field: 'cytoband',
          value: 'p11.2',
          op: 'in',
          count: 33,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 33,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Retinitis pigmentosa',
          op: 'in',
          count: 3,
        },
        {
          field: 'omim_gene_panel',
          value: 'Albinism, oculocutaneous, type VII',
          op: 'in',
          count: 2,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 2,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'leukaemia',
          op: 'in',
          count: 0,
        },
      ],
      Frequency: [
        {
          field: 'gnomad_sf',
          value: '0.5',
          op: '<',
          count: 153,
        },
        {
          field: 'gnomad_sc',
          value: '10000',
          op: '<',
          count: 66,
        },
      ],
      'Metric QC': [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 138,
        },
        {
          field: 'quality',
          value: '50',
          op: '<',
          count: 432,
        },
        {
          field: 'pe',
          value: '10000',
          op: '<',
          count: 648,
        },
        {
          field: 'sm',
          value: '50',
          op: '<',
          count: 648,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 49,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 553,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 593,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          countOr: 553,
          countAnd: 49,
        },
      },
    },
    somatic: {
    //TODO: Waiting for stable data to restore the counts
      case_id: 1008,
      seq_id: 1011,
      task_id: 1018,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: /\d{1}/,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: /\d{1}/,
        },
      ],
      Frequency: [
        {
          field: 'somatic_pf_tn_wgs',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Occurrence: [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: /\d{1}/,
        },
        {
          field: 'info_qd',
          value: '0',
          op: '>',
          count: 0,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: /\d{1}/,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: /\d{1}/,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: /\d{1}/,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: /\d{1}/,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: /\d{1}/,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: /\d{1}/,
          countAnd: /\d{1}/,
        },
      },
    },
  },
};

function getGlobalData() {
  return globalData;
}

export default {
  getGlobalData,
  globalData,
};
