const globalData = {
  Authorization: {
    token: null, // Will be set by initializeGlobalData
  },
  BatchesId: {
    patientSuccess: '2c9ccf0e-cbc9-45b1-9eab-87d023bffd00',
    patientNotFound: '00000000-0000-0000-0000-000000000000',
  },
  Count: {
    //occurrences/germline/snv/{case_id}/{seq_id}/{task_id}/count
    case_id: 1,
    seq_id: 1,
    snv: {
      task_id: 63,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: 4000762,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: 2737460,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 389286,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 2591,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: 2148441,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: 1246473,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: 1345816,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: 381289,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 425423,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: 17565,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: 6562,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 8434,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: 1835,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: 41346,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: 4968294,
        },
        {
          field: 'exomiser_gene_combined_score',
          value: '2.5',
          op: '<',
          count: 16109,
        },
        {
          field: 'exomiser_acmg_classification',
          value: 'uncertain_significance',
          op: 'in',
          count: 12036,
        },
        {
          field: 'exomiser_acmg_evidence',
          value: 'BP4',
          op: 'in',
          count: 7455,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: 12003,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: 12564,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: 3796,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: 9498,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: 6813,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: 8265,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: 10600,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: 3199,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: 8821,
        },
      ],
      Frequency: [
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: /(2073057|2180139)/,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: /(2006606|2298376)/,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: /(1866517|2473724)/,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: 2825011,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: 2873043,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: 48017,
        },
      ],
      Occurrence: [
        {
          field: 'zygosity',
          value: 'HET',
          op: 'in',
          count: 3155641,
        },
        {
          field: 'mother_zygosity',
          value: 'HET',
          op: 'in',
          count: 2122449,
        },
        {
          field: 'father_zygosity',
          value: 'HET',
          op: 'in',
          count: 2055200,
        },
        {
          field: 'parental_origin',
          value: 'BOTH',
          op: 'in',
          count: 1764751,
        },
        {
          field: 'transmission_mode',
          value: 'autosomal_dominant',
          op: 'in',
          count: 942035,
        },
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 4238849,
        },
        {
          field: 'info_qd',
          value: '20',
          op: '<',
          count: 2170259,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: 4973084,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: 4974267,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: 1500067,
        },
        {
          field: 'genotype_quality',
          value: '50',
          op: '<',
          count: 216676,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 312548,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 4077500,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 4586982,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: 4077500,
          countAnd: 312548,
        },
      },
    },
    cnv: {
      task_id: 1,
      Variant: [
        {
          field: 'type',
          value: 'LOSS',
          op: 'in',
          count: 546,
        },
        {
          field: 'cn',
          value: '100',
          op: '<',
          count: 648,
        },
        {
          field: 'length',
          value: '100000',
          op: '<',
          count: 617,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 56,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'end',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'nb_snv',
          value: '10000',
          op: '<',
          count: 521,
        },
      ],
      Gene: [
        {
          field: 'cytoband',
          value: 'p11.2',
          op: 'in',
          count: 33,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 33,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Retinitis pigmentosa',
          op: 'in',
          count: 3,
        },
        {
          field: 'omim_gene_panel',
          value: 'Albinism, oculocutaneous, type VII',
          op: 'in',
          count: 2,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 2,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'leukaemia',
          op: 'in',
          count: 0,
        },
      ],
      Frequency: [
        {
          field: 'gnomad_sf',
          value: '0.5',
          op: '<',
          count: 153,
        },
        {
          field: 'gnomad_sc',
          value: '10000',
          op: '<',
          count: 66,
        },
      ],
      'Metric QC': [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 138,
        },
        {
          field: 'quality',
          value: '50',
          op: '<',
          count: 432,
        },
        {
          field: 'pe',
          value: '10000',
          op: '<',
          count: 648,
        },
        {
          field: 'sm',
          value: '50',
          op: '<',
          count: 648,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 49,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 553,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 593,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          countOr: 553,
          countAnd: 49,
        },
      },
    },
    somatic: {
      case_id: 1008,
      seq_id: 1011,
      task_id: 1018,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: 92154,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: 86479,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 12627,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 132,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: 68769,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: 37823,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: 45647,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: 11670,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 13061,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: 490,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: 154,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 278,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: 32,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: 51,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: 177823,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: 297,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: 360,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: 43,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: 364,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: 168,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: 243,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: 360,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: 92,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: 228,
        },
      ],
      Frequency: [
        {
          field: 'somatic_pf_tn_wgs',
          value: '0.5',
          op: '<',
          count: 173213,
        },
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: 175409,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: 175192,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: 173962,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: 128314,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: 114921,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: 621,
        },
      ],
      Occurrence: [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 4954,
        },
        {
          field: 'info_qd',
          value: '0',
          op: '>',
          count: 0,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: 178045,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: 178045,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: 176878,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 5414,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 99367,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 165418,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: 99367,
          countAnd: 5414,
        },
      },
    },
  },
};

function getGlobalData() {
  return globalData;
}

export default {
  getGlobalData,
  globalData,
};
