const globalData = {
  Authorization: {
    token: null, // Will be set by initializeGlobalData
  },
  BatchesId: {
    patientSuccess: '2c9ccf0e-cbc9-45b1-9eab-87d023bffd00',
    patientNotFound: '00000000-0000-0000-0000-000000000000',
  },
  Count: {
    //occurrences/germline/snv/{case_id}/{seq_id}/{task_id}/count
    case_id: 1,
    seq_id: 1,
    snv: {
      task_id: 63,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: 1788543,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: 1284490,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 180279,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 527,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: 1022619,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: 592244,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: 650415,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: 184517,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 205892,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: 8510,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: 3210,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 4142,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: 941,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: 20309,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: 2247886,
        },
        {
          field: 'exomiser_gene_combined_score',
          value: '2.5',
          op: '<',
          count: 7695,
        },
        {
          field: 'exomiser_acmg_classification',
          value: 'uncertain_significance',
          op: 'in',
          count: 5690,
        },
        {
          field: 'exomiser_acmg_evidence',
          value: 'BP4',
          op: 'in',
          count: 3492,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: 4930,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: 5153,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: 1556,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: 4059,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: 3101,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: 3630,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: 4565,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: 1526,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: 3823,
        },
      ],
      Frequency: [
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: 799537,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: 766493,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: 696564,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: 1236881,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: 1251982,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: 22531,
        },
      ],
      Occurrence: [
        {
          field: 'zygosity',
          value: 'HET',
          op: 'in',
          count: 1377932,
        },
        {
          field: 'mother_zygosity',
          value: 'HET',
          op: 'in',
          count: 930873,
        },
        {
          field: 'father_zygosity',
          value: 'HET',
          op: 'in',
          count: 897293,
        },
        {
          field: 'parental_origin',
          value: 'BOTH',
          op: 'in',
          count: 858860,
        },
        {
          field: 'transmission_mode',
          value: 'autosomal_dominant',
          op: 'in',
          count: 430501,
        },
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 2113132,
        },
        {
          field: 'info_qd',
          value: '20',
          op: '<',
          count: 913493,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: 2250429,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: 2250729,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: 610863,
        },
        {
          field: 'genotype_quality',
          value: '50',
          op: '<',
          count: 69319,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 143634,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 1825188,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 2070822,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: 1825188,
          countAnd: 143634,
        },
      },
    },
    cnv: {
      task_id: 1,
      Variant: [
        {
          field: 'type',
          value: 'LOSS',
          op: 'in',
          count: 546,
        },
        {
          field: 'cn',
          value: '100',
          op: '<',
          count: 648,
        },
        {
          field: 'length',
          value: '100000',
          op: '<',
          count: 617,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 56,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'end',
          value: '100000',
          op: '<',
          count: 2,
        },
        {
          field: 'nb_snv',
          value: '10000',
          op: '<',
          count: 521,
        },
      ],
      Gene: [
        {
          field: 'cytoband',
          value: 'p11.2',
          op: 'in',
          count: 33,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 33,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Retinitis pigmentosa',
          op: 'in',
          count: 3,
        },
        {
          field: 'omim_gene_panel',
          value: 'Albinism, oculocutaneous, type VII',
          op: 'in',
          count: 2,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 2,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'leukaemia',
          op: 'in',
          count: 0,
        },
      ],
      Frequency: [
        {
          field: 'gnomad_sf',
          value: '0.5',
          op: '<',
          count: 153,
        },
        {
          field: 'gnomad_sc',
          value: '10000',
          op: '<',
          count: 66,
        },
      ],
      'Metric QC': [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 138,
        },
        {
          field: 'quality',
          value: '50',
          op: '<',
          count: 432,
        },
        {
          field: 'pe',
          value: '10000',
          op: '<',
          count: 648,
        },
        {
          field: 'sm',
          value: '50',
          op: '<',
          count: 648,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 49,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          count: 553,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 593,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'type',
          value2: 'LOSS',
          op2: 'in',
          countOr: 553,
          countAnd: 49,
        },
      },
    },
    somatic: {
      case_id: 1008,
      seq_id: 1011,
      task_id: 1018,
      Variant: [
        {
          field: 'variant_class',
          value: 'SNV',
          op: 'in',
          count: 2714,
        },
        {
          field: 'consequence',
          value: 'intron_variant',
          op: 'in',
          count: 6829,
        },
        {
          field: 'chromosome',
          value: '2',
          op: 'in',
          count: 972,
        },
        {
          field: 'start',
          value: '100000',
          op: '<',
          count: 3,
        },
      ],
      Gene: [
        {
          field: 'biotype',
          value: 'protein_coding',
          op: 'in',
          count: 5348,
        },
        {
          field: 'gnomad_pli',
          value: '0.5',
          op: '<',
          count: 2940,
        },
        {
          field: 'gnomad_loeuf',
          value: '1',
          op: '<',
          count: 3520,
        },
        {
          field: 'omim_inheritance',
          value: 'Autosomal recessive',
          op: 'in',
          count: 938,
        },
        {
          field: 'hpo_gene_panel',
          value: 'Autosomal recessive inheritance(HP:0000007)',
          op: 'in',
          count: 1039,
        },
        {
          field: 'orphanet_gene_panel',
          value: 'Autosomal recessive non-syndromic sensorineural deafness type DFNB',
          op: 'in',
          count: 40,
        },
        {
          field: 'omim_gene_panel',
          value: 'Colorectal cancer, somatic',
          op: 'in',
          count: 12,
        },
        {
          field: 'ddd_gene_panel',
          value: 'AUTOSOMAL RECESSIVE INTELLECTUAL DEVELOPMENTAL DISORDER',
          op: 'in',
          count: 18,
        },
        {
          field: 'cosmic_gene_panel',
          value: 'neuroblastoma',
          op: 'in',
          count: 1,
        },
      ],
      Pathogenicity: [
        {
          field: 'clinvar',
          value: 'Benign',
          op: 'in',
          count: 22,
        },
        {
          field: 'vep_impact',
          value: 'MODIFIER',
          op: 'in',
          count: 11901,
        },
        {
          field: 'cadd_score',
          value: '0.5',
          op: '<',
          count: 7,
        },
        {
          field: 'cadd_phred',
          value: '25',
          op: '<',
          count: 11,
        },
        {
          field: 'dann_score',
          value: '0.5',
          op: '<',
          count: 2,
        },
        {
          field: 'fathmm_pred',
          value: 'T',
          op: 'in',
          count: 9,
        },
        {
          field: 'lrt_pred',
          value: 'N',
          op: 'in',
          count: 4,
        },
        {
          field: 'polyphen2_hvar_pred',
          value: 'B',
          op: 'in',
          count: 6,
        },
        {
          field: 'revel_score',
          value: '0.5',
          op: '<',
          count: 8,
        },
        {
          field: 'spliceai_ds',
          value: '0.5',
          op: '<',
          count: 2,
        },
        {
          field: 'sift_pred',
          value: 'T',
          op: 'in',
          count: 5,
        },
      ],
      Frequency: [
        {
          field: 'somatic_pf_tn_wgs',
          value: '0.5',
          op: '<',
          count: 9508,
        },
        {
          field: 'germline_pf_wgs',
          value: '0.5',
          op: '<',
          count: 10577,
        },
        {
          field: 'germline_pf_wgs_affected',
          value: '0.5',
          op: '<',
          count: 10458,
        },
        {
          field: 'germline_pf_wgs_not_affected',
          value: '0.5',
          op: '<',
          count: 9846,
        },
        {
          field: 'gnomad_v3_af',
          value: '0.5',
          op: '<',
          count: 9833,
        },
        {
          field: 'topmed_af',
          value: '0.5',
          op: '<',
          count: 9762,
        },
        {
          field: 'thousand_genome_af',
          value: '0.5',
          op: '<',
          count: 43,
        },
      ],
      Occurrence: [
        {
          field: 'filter',
          value: 'PASS',
          op: 'in',
          count: 2401,
        },
        {
          field: 'info_qd',
          value: '0',
          op: '>',
          count: 0,
        },
        {
          field: 'ad_alt',
          value: '3500',
          op: '<',
          count: 11909,
        },
        {
          field: 'ad_total',
          value: '3500',
          op: '<',
          count: 11909,
        },
        {
          field: 'ad_ratio',
          value: '0.5',
          op: '<',
          count: 11730,
        },
      ],
      Complex: {
        twoPillsAnd: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 207,
        },
        twoPillsOr: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          count: 3479,
        },
        notIn: {
          field1: 'chromosome',
          value1: '2',
          op1: 'not-in',
          count: 10937,
        },
        combined: {
          field1: 'chromosome',
          value1: '2',
          op1: 'in',
          field2: 'variant_class',
          value2: 'SNV',
          op2: 'in',
          countOr: 3479,
          countAnd: 207,
        },
      },
    },
  },
};

function getGlobalData() {
  return globalData;
}

export default {
  getGlobalData,
  globalData,
};
