INSERT INTO analysis_catalog (code, name, tenant_code) VALUES
    ('MMG',    'Maladies musculaires globales',                                                              'qlin'),
    ('DYSM',   'Dystrophies musculaires',                                                                    'qlin'),
    ('RHAB',   'Rhabdomyolyse',                                                                              'qlin'),
    ('MITN',   'Mitochondriopathies nucléaires',                                                             'qlin'),
    ('MYOC',   'Myopathies congénitales',                                                                    'qlin'),
    ('MYAC',   'Myasthénies congénitales',                                                                   'qlin'),
    ('HYPM',   'Hyperthermie maligne',                                                                       'qlin'),
    ('RGDI',   'Retard global de développement / Déficience intellectuelle (Trio)',                          'qlin'),
    ('POLYM',  'Polymalformation contexte postnatal',                                                        'qlin'),
    ('TRATU',  'Transcriptome tumoral',                                                                      'qlin'),
    ('TUHEM',  'Prédisposition hémopathies malignes',                                                        'qlin'),
    ('TUPED',  'Prédisposition cancers pédiatriques',                                                        'qlin'),
    ('EXTUM',  'Analyse tumorale',                                                                           'qlin'),
    ('SHEMA',  'Leucémie (somatique)',                                                                       'qlin'),
    ('SCID',   'Déficit immunitaire combiné sévère',                                                         'qlin'),
    ('STMO',   'Sarcome des tissus mous et osseux',                                                          'qlin'),
    ('FEAN',   'Anomalies fœtales',                                                                          'qlin'),
    ('DPSO',   'Défaut de production de superoxyde',                                                         'qlin'),
    ('EIDC',   'Erreurs innées du complément',                                                               'qlin'),
    ('EIDI',   'Erreurs innées de l''immunité',                                                              'qlin'),
    ('EIII',   'Erreurs innées de l''immunité intrinsèque',                                                  'qlin'),
    ('EPIL',   'Epilepsie sans déficience intellectuelle',                                                   'qlin'),
    ('RAPIDE', 'Exome rapide : diagnostic monogénique et orientation thérapeutique',                         'qlin'),
    ('HDIP',   'Hypogammaglobulinémie et dysrégulation immunitaire primitive',                               'qlin'),
    ('HLEB',   'Hémophagocytose lymphohistiocytaire et à l''infection chronique active au virus Epstein Barr', 'qlin'),
    ('HLH',    'Hémophagocytose lymphohistiocytaire',                                                        'qlin'),
    ('MAI',    'Maladies auto-inflammatoires',                                                               'qlin'),
    ('MSMD',   'Syndrome de prédisposition mendélienne aux infections mycobactériennes (MSMD)',              'qlin'),
    ('NPC',    'Neutropénie congénitale',                                                                    'qlin'),
    ('RETINO', 'Rétinopathies',                                                                              'qlin'),
    ('SHIGE',  'Syndrome d''hyper-IgE',                                                                      'qlin'),
    ('SLA',    'Sclérose latérale amyotrophique',                                                            'qlin'),
    ('SURD',   'Surdité',                                                                                    'qlin'),
    ('VEOIB',  'Maladie inflammatoire de l''intestin très précoce',                                          'qlin'),
    ('GENOR',  'Séquençage du génome entier - non spécifique',                                               'qlin'),
    ('NEUTP',  'Neutropénie congénitale',                                                                    'qlin'),
    ('CONCO',  'Prédisposition aux tumeurs solides de l''adulte',                                            'qlin')
ON CONFLICT (code, tenant_code) DO NOTHING;
