INSERT INTO exam (code, name_en, name_fr, tenant_code) VALUES
    ('acyl',  'Acylcarnitines', 'Acylcarnitines', 'qlin'),
    ('bmet',  'Metabolic Work-Up', 'Bilan métabolique', 'qlin'),
    ('bmus',  'Muscle Biopsy', 'Biopsie musculaire', 'qlin'),
    ('caap',  'Plasma Amino Acid Chromatography', 'Chromatographie acides aminés plasmatiques', 'qlin'),
    ('cgh',   'Comparative Genomic Hybridization', 'Hybridation génomique comparative', 'qlin'),
    ('ckin',  'Serum Creatine Kinase', 'Créatine kinase sérique', 'qlin'),
    ('cnvpg', 'Genomic CNV analysis', 'Analyse CNV pan-génomique', 'qlin'),
    ('ctgr',  'CTG Repeat Testing (Steinert Disease)', 'Test répétitions CTG (maladie de Steinert)', 'qlin'),
    ('eabd',  'Abdominal Ultrasound', 'Échographie abdominale', 'qlin'),
    ('ecar',  'Cardiac Ultrasound', 'Échographie cardiaque', 'qlin'),
    ('eeg',   'Electroencephalogram (EEG)', 'Électroencéphalogramme (EEG)', 'qlin'),
    ('emg',   'Electromyography (EMG)', 'Electromyographie (EMG)', 'qlin'),
    ('gcnr',  'GCN Repeat Testing (Oculopharyngeal Muscular Dystrophy)', 'Test répétitions GCN (dystrophie musculaire oculopharyngée)', 'qlin'),
    ('irmc',  'Cerebral MRI', 'IRM cérébrale', 'qlin'),
    ('irmm',  'Muscle MRI', 'IRM musculaire', 'qlin'),
    ('lp',    'Lymphocyte Phenotyping', 'Phénotypage lymphocytaire', 'qlin'),
    ('lpwgs', 'CNV (Microarray/LP-WGS)', 'CNV (micropuce/LP-WGS)', 'qlin'),
    ('opht',  'Ophthalmological Examination', 'Examen ophtalmologique', 'qlin'),
    ('pg',    'Gene Panel', 'Panel de gènes', 'qlin'),
    ('qfpcr', 'Rapid detection of fetal aneuploidies (QF-PCR)', 'Détection rapide des aneuploïdies (QF-PCR)', 'qlin'),
    ('srmn',  'NMR Spectroscopy', 'Spectroscopie RMN', 'qlin'),
    ('tgdd',  'Deletions and Duplications Testing (Duchenne and Becker Dystrophies)', 'Test délétions et duplication (dystrophies Duchenne et Becker)', 'qlin'),
    ('tsxf',  'Fragile X Syndrome Testing', 'Test syndrome de X fragile', 'qlin'),
    ('other', 'Other', 'Autre', 'qlin')
ON CONFLICT (code, tenant_code) DO NOTHING;
