# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.beacon_pagination import BeaconPagination
from radiant_python.models.beacon_schema_reference import BeaconSchemaReference
from typing import Optional, Set
from typing_extensions import Self

class BeaconReceivedRequestSummary(BaseModel):
    """
    BeaconReceivedRequestSummary
    """ # noqa: E501
    api_version: Optional[StrictStr] = Field(default=None, alias="apiVersion")
    filters: Optional[List[StrictStr]] = None
    include_resultset_responses: Optional[StrictStr] = Field(default=None, alias="includeResultsetResponses")
    pagination: Optional[BeaconPagination] = None
    request_parameters: Optional[Dict[str, Any]] = Field(default=None, alias="requestParameters")
    requested_granularity: Optional[StrictStr] = Field(default=None, alias="requestedGranularity")
    requested_schemas: Optional[List[BeaconSchemaReference]] = Field(default=None, alias="requestedSchemas")
    test_mode: Optional[StrictBool] = Field(default=None, alias="testMode")
    __properties: ClassVar[List[str]] = ["apiVersion", "filters", "includeResultsetResponses", "pagination", "requestParameters", "requestedGranularity", "requestedSchemas", "testMode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BeaconReceivedRequestSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in requested_schemas (list)
        _items = []
        if self.requested_schemas:
            for _item_requested_schemas in self.requested_schemas:
                if _item_requested_schemas:
                    _items.append(_item_requested_schemas.to_dict())
            _dict['requestedSchemas'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BeaconReceivedRequestSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "filters": obj.get("filters"),
            "includeResultsetResponses": obj.get("includeResultsetResponses"),
            "pagination": BeaconPagination.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None,
            "requestParameters": obj.get("requestParameters"),
            "requestedGranularity": obj.get("requestedGranularity"),
            "requestedSchemas": [BeaconSchemaReference.from_dict(_item) for _item in obj["requestedSchemas"]] if obj.get("requestedSchemas") is not None else None,
            "testMode": obj.get("testMode")
        })
        return _obj


