# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.beacon_received_request_summary import BeaconReceivedRequestSummary
from radiant_python.models.beacon_schema_reference import BeaconSchemaReference
from typing import Optional, Set
from typing_extensions import Self

class BeaconMeta(BaseModel):
    """
    BeaconMeta
    """ # noqa: E501
    api_version: Optional[StrictStr] = Field(default=None, alias="apiVersion")
    beacon_id: Optional[StrictStr] = Field(default=None, alias="beaconId")
    received_request_summary: Optional[BeaconReceivedRequestSummary] = Field(default=None, alias="receivedRequestSummary")
    returned_granularity: Optional[StrictStr] = Field(default=None, alias="returnedGranularity")
    returned_schemas: Optional[List[BeaconSchemaReference]] = Field(default=None, alias="returnedSchemas")
    __properties: ClassVar[List[str]] = ["apiVersion", "beaconId", "receivedRequestSummary", "returnedGranularity", "returnedSchemas"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BeaconMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of received_request_summary
        if self.received_request_summary:
            _dict['receivedRequestSummary'] = self.received_request_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in returned_schemas (list)
        _items = []
        if self.returned_schemas:
            for _item_returned_schemas in self.returned_schemas:
                if _item_returned_schemas:
                    _items.append(_item_returned_schemas.to_dict())
            _dict['returnedSchemas'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BeaconMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "beaconId": obj.get("beaconId"),
            "receivedRequestSummary": BeaconReceivedRequestSummary.from_dict(obj["receivedRequestSummary"]) if obj.get("receivedRequestSummary") is not None else None,
            "returnedGranularity": obj.get("returnedGranularity"),
            "returnedSchemas": [BeaconSchemaReference.from_dict(_item) for _item in obj["returnedSchemas"]] if obj.get("returnedSchemas") is not None else None
        })
        return _obj


