# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.aggregation import Aggregation
from typing import Optional, Set
from typing_extensions import Self

class DocumentFilters(BaseModel):
    """
    DocumentFilters
    """ # noqa: E501
    data_type: List[Aggregation]
    diagnosis_lab: Optional[List[Aggregation]] = None
    format: List[Aggregation]
    project: Optional[List[Aggregation]] = None
    relationship_to_proband: List[Aggregation]
    __properties: ClassVar[List[str]] = ["data_type", "diagnosis_lab", "format", "project", "relationship_to_proband"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_type (list)
        _items = []
        if self.data_type:
            for _item_data_type in self.data_type:
                if _item_data_type:
                    _items.append(_item_data_type.to_dict())
            _dict['data_type'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in diagnosis_lab (list)
        _items = []
        if self.diagnosis_lab:
            for _item_diagnosis_lab in self.diagnosis_lab:
                if _item_diagnosis_lab:
                    _items.append(_item_diagnosis_lab.to_dict())
            _dict['diagnosis_lab'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in format (list)
        _items = []
        if self.format:
            for _item_format in self.format:
                if _item_format:
                    _items.append(_item_format.to_dict())
            _dict['format'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in project (list)
        _items = []
        if self.project:
            for _item_project in self.project:
                if _item_project:
                    _items.append(_item_project.to_dict())
            _dict['project'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in relationship_to_proband (list)
        _items = []
        if self.relationship_to_proband:
            for _item_relationship_to_proband in self.relationship_to_proband:
                if _item_relationship_to_proband:
                    _items.append(_item_relationship_to_proband.to_dict())
            _dict['relationship_to_proband'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_type": [Aggregation.from_dict(_item) for _item in obj["data_type"]] if obj.get("data_type") is not None else None,
            "diagnosis_lab": [Aggregation.from_dict(_item) for _item in obj["diagnosis_lab"]] if obj.get("diagnosis_lab") is not None else None,
            "format": [Aggregation.from_dict(_item) for _item in obj["format"]] if obj.get("format") is not None else None,
            "project": [Aggregation.from_dict(_item) for _item in obj["project"]] if obj.get("project") is not None else None,
            "relationship_to_proband": [Aggregation.from_dict(_item) for _item in obj["relationship_to_proband"]] if obj.get("relationship_to_proband") is not None else None
        })
        return _obj


