# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from radiant_python.models.omim_gene_panel import OmimGenePanel
from radiant_python.models.vep_impact import VepImpact
from typing import Optional, Set
from typing_extensions import Self

class ExpandedSomaticSNVOccurrence(BaseModel):
    """
    ExpandedSomaticSNVOccurrence
    """ # noqa: E501
    aa_change: Optional[StrictStr] = None
    ad_alt: Optional[StrictInt] = None
    ad_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    ad_total: Optional[StrictInt] = None
    aq: Optional[Union[StrictFloat, StrictInt]] = None
    cadd_phred: Optional[Union[StrictFloat, StrictInt]] = None
    cadd_score: Optional[Union[StrictFloat, StrictInt]] = None
    chromosome: StrictStr
    clinvar: Optional[List[StrictStr]] = None
    cmc_mutation_url: Optional[StrictStr] = None
    cmc_sample_mutated: Optional[StrictInt] = None
    cmc_sample_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    cmc_tier: Optional[StrictStr] = None
    dann_score: Optional[Union[StrictFloat, StrictInt]] = None
    dna_change: Optional[StrictStr] = None
    end: StrictInt
    ensembl_gene_id: Optional[StrictStr] = None
    exon_rank: Optional[StrictInt] = None
    exon_total: Optional[StrictInt] = None
    fathmm_pred: Optional[StrictStr] = None
    fathmm_score: Optional[Union[StrictFloat, StrictInt]] = None
    filter: Optional[StrictStr] = None
    germline_af_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wgs_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wgs_not_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs_not_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_hom_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wgs_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wgs_not_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs_not_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_pc_wgs: Optional[StrictInt] = None
    germline_pc_wgs_affected: Optional[StrictInt] = None
    germline_pc_wgs_not_affected: Optional[StrictInt] = None
    germline_pc_wxs: Optional[StrictInt] = None
    germline_pc_wxs_affected: Optional[StrictInt] = None
    germline_pc_wxs_not_affected: Optional[StrictInt] = None
    germline_pf_wgs: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wgs_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wgs_not_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs_not_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pn_wgs: Optional[StrictInt] = None
    germline_pn_wgs_affected: Optional[StrictInt] = None
    germline_pn_wgs_not_affected: Optional[StrictInt] = None
    germline_pn_wxs: Optional[StrictInt] = None
    germline_pn_wxs_affected: Optional[StrictInt] = None
    germline_pn_wxs_not_affected: Optional[StrictInt] = None
    gnomad_loeuf: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_pli: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_v3_af: Optional[Union[StrictFloat, StrictInt]] = None
    hgvsg: StrictStr
    interpretation_classification_counts: Optional[Dict[str, StrictInt]] = None
    is_canonical: Optional[StrictBool] = None
    is_mane_plus: Optional[StrictBool] = None
    is_mane_select: Optional[StrictBool] = None
    locus: StrictStr
    locus_id: StrictStr
    lrt_pred: Optional[StrictStr] = None
    lrt_score: Optional[Union[StrictFloat, StrictInt]] = None
    omim_conditions: Optional[List[OmimGenePanel]] = None
    picked_consequences: Optional[List[StrictStr]] = None
    polyphen2_hvar_pred: Optional[StrictStr] = None
    polyphen2_hvar_score: Optional[Union[StrictFloat, StrictInt]] = None
    qd: Optional[Union[StrictFloat, StrictInt]] = None
    revel_score: Optional[Union[StrictFloat, StrictInt]] = None
    rsnumber: Optional[StrictStr] = None
    sift_pred: Optional[StrictStr] = None
    sift_score: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_af_tn_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_tn_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_to_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_to_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_hom_tn_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_tn_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_to_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_to_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_pc_tn_wgs: Optional[StrictInt] = None
    somatic_pc_tn_wxs: Optional[StrictInt] = None
    somatic_pc_to_wgs: Optional[StrictInt] = None
    somatic_pc_to_wxs: Optional[StrictInt] = None
    somatic_pf_tn_wgs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pf_tn_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pf_to_wgs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pf_to_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pn_tn_wgs: Optional[StrictInt] = None
    somatic_pn_tn_wxs: Optional[StrictInt] = None
    somatic_pn_to_wgs: Optional[StrictInt] = None
    somatic_pn_to_wxs: Optional[StrictInt] = None
    spliceai_ds: Optional[Union[StrictFloat, StrictInt]] = None
    spliceai_type: Optional[List[StrictStr]] = None
    sq: Optional[Union[StrictFloat, StrictInt]] = None
    start: StrictInt
    symbol: Optional[StrictStr] = None
    transcript_id: Optional[StrictStr] = None
    vep_impact: Optional[VepImpact] = None
    __properties: ClassVar[List[str]] = ["aa_change", "ad_alt", "ad_ratio", "ad_total", "aq", "cadd_phred", "cadd_score", "chromosome", "clinvar", "cmc_mutation_url", "cmc_sample_mutated", "cmc_sample_ratio", "cmc_tier", "dann_score", "dna_change", "end", "ensembl_gene_id", "exon_rank", "exon_total", "fathmm_pred", "fathmm_score", "filter", "germline_af_wgs", "germline_af_wgs_affected", "germline_af_wgs_not_affected", "germline_af_wxs", "germline_af_wxs_affected", "germline_af_wxs_not_affected", "germline_hom_wgs", "germline_hom_wgs_affected", "germline_hom_wgs_not_affected", "germline_hom_wxs", "germline_hom_wxs_affected", "germline_hom_wxs_not_affected", "germline_pc_wgs", "germline_pc_wgs_affected", "germline_pc_wgs_not_affected", "germline_pc_wxs", "germline_pc_wxs_affected", "germline_pc_wxs_not_affected", "germline_pf_wgs", "germline_pf_wgs_affected", "germline_pf_wgs_not_affected", "germline_pf_wxs", "germline_pf_wxs_affected", "germline_pf_wxs_not_affected", "germline_pn_wgs", "germline_pn_wgs_affected", "germline_pn_wgs_not_affected", "germline_pn_wxs", "germline_pn_wxs_affected", "germline_pn_wxs_not_affected", "gnomad_loeuf", "gnomad_pli", "gnomad_v3_af", "hgvsg", "interpretation_classification_counts", "is_canonical", "is_mane_plus", "is_mane_select", "locus", "locus_id", "lrt_pred", "lrt_score", "omim_conditions", "picked_consequences", "polyphen2_hvar_pred", "polyphen2_hvar_score", "qd", "revel_score", "rsnumber", "sift_pred", "sift_score", "somatic_af_tn_wgs", "somatic_af_tn_wxs", "somatic_af_to_wgs", "somatic_af_to_wxs", "somatic_hom_tn_wgs", "somatic_hom_tn_wxs", "somatic_hom_to_wgs", "somatic_hom_to_wxs", "somatic_pc_tn_wgs", "somatic_pc_tn_wxs", "somatic_pc_to_wgs", "somatic_pc_to_wxs", "somatic_pf_tn_wgs", "somatic_pf_tn_wxs", "somatic_pf_to_wgs", "somatic_pf_to_wxs", "somatic_pn_tn_wgs", "somatic_pn_tn_wxs", "somatic_pn_to_wgs", "somatic_pn_to_wxs", "spliceai_ds", "spliceai_type", "sq", "start", "symbol", "transcript_id", "vep_impact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExpandedSomaticSNVOccurrence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in omim_conditions (list)
        _items = []
        if self.omim_conditions:
            for _item_omim_conditions in self.omim_conditions:
                if _item_omim_conditions:
                    _items.append(_item_omim_conditions.to_dict())
            _dict['omim_conditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExpandedSomaticSNVOccurrence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aa_change": obj.get("aa_change"),
            "ad_alt": obj.get("ad_alt"),
            "ad_ratio": obj.get("ad_ratio"),
            "ad_total": obj.get("ad_total"),
            "aq": obj.get("aq"),
            "cadd_phred": obj.get("cadd_phred"),
            "cadd_score": obj.get("cadd_score"),
            "chromosome": obj.get("chromosome"),
            "clinvar": obj.get("clinvar"),
            "cmc_mutation_url": obj.get("cmc_mutation_url"),
            "cmc_sample_mutated": obj.get("cmc_sample_mutated"),
            "cmc_sample_ratio": obj.get("cmc_sample_ratio"),
            "cmc_tier": obj.get("cmc_tier"),
            "dann_score": obj.get("dann_score"),
            "dna_change": obj.get("dna_change"),
            "end": obj.get("end"),
            "ensembl_gene_id": obj.get("ensembl_gene_id"),
            "exon_rank": obj.get("exon_rank"),
            "exon_total": obj.get("exon_total"),
            "fathmm_pred": obj.get("fathmm_pred"),
            "fathmm_score": obj.get("fathmm_score"),
            "filter": obj.get("filter"),
            "germline_af_wgs": obj.get("germline_af_wgs"),
            "germline_af_wgs_affected": obj.get("germline_af_wgs_affected"),
            "germline_af_wgs_not_affected": obj.get("germline_af_wgs_not_affected"),
            "germline_af_wxs": obj.get("germline_af_wxs"),
            "germline_af_wxs_affected": obj.get("germline_af_wxs_affected"),
            "germline_af_wxs_not_affected": obj.get("germline_af_wxs_not_affected"),
            "germline_hom_wgs": obj.get("germline_hom_wgs"),
            "germline_hom_wgs_affected": obj.get("germline_hom_wgs_affected"),
            "germline_hom_wgs_not_affected": obj.get("germline_hom_wgs_not_affected"),
            "germline_hom_wxs": obj.get("germline_hom_wxs"),
            "germline_hom_wxs_affected": obj.get("germline_hom_wxs_affected"),
            "germline_hom_wxs_not_affected": obj.get("germline_hom_wxs_not_affected"),
            "germline_pc_wgs": obj.get("germline_pc_wgs"),
            "germline_pc_wgs_affected": obj.get("germline_pc_wgs_affected"),
            "germline_pc_wgs_not_affected": obj.get("germline_pc_wgs_not_affected"),
            "germline_pc_wxs": obj.get("germline_pc_wxs"),
            "germline_pc_wxs_affected": obj.get("germline_pc_wxs_affected"),
            "germline_pc_wxs_not_affected": obj.get("germline_pc_wxs_not_affected"),
            "germline_pf_wgs": obj.get("germline_pf_wgs"),
            "germline_pf_wgs_affected": obj.get("germline_pf_wgs_affected"),
            "germline_pf_wgs_not_affected": obj.get("germline_pf_wgs_not_affected"),
            "germline_pf_wxs": obj.get("germline_pf_wxs"),
            "germline_pf_wxs_affected": obj.get("germline_pf_wxs_affected"),
            "germline_pf_wxs_not_affected": obj.get("germline_pf_wxs_not_affected"),
            "germline_pn_wgs": obj.get("germline_pn_wgs"),
            "germline_pn_wgs_affected": obj.get("germline_pn_wgs_affected"),
            "germline_pn_wgs_not_affected": obj.get("germline_pn_wgs_not_affected"),
            "germline_pn_wxs": obj.get("germline_pn_wxs"),
            "germline_pn_wxs_affected": obj.get("germline_pn_wxs_affected"),
            "germline_pn_wxs_not_affected": obj.get("germline_pn_wxs_not_affected"),
            "gnomad_loeuf": obj.get("gnomad_loeuf"),
            "gnomad_pli": obj.get("gnomad_pli"),
            "gnomad_v3_af": obj.get("gnomad_v3_af"),
            "hgvsg": obj.get("hgvsg"),
            "interpretation_classification_counts": obj.get("interpretation_classification_counts"),
            "is_canonical": obj.get("is_canonical"),
            "is_mane_plus": obj.get("is_mane_plus"),
            "is_mane_select": obj.get("is_mane_select"),
            "locus": obj.get("locus"),
            "locus_id": obj.get("locus_id"),
            "lrt_pred": obj.get("lrt_pred"),
            "lrt_score": obj.get("lrt_score"),
            "omim_conditions": [OmimGenePanel.from_dict(_item) for _item in obj["omim_conditions"]] if obj.get("omim_conditions") is not None else None,
            "picked_consequences": obj.get("picked_consequences"),
            "polyphen2_hvar_pred": obj.get("polyphen2_hvar_pred"),
            "polyphen2_hvar_score": obj.get("polyphen2_hvar_score"),
            "qd": obj.get("qd"),
            "revel_score": obj.get("revel_score"),
            "rsnumber": obj.get("rsnumber"),
            "sift_pred": obj.get("sift_pred"),
            "sift_score": obj.get("sift_score"),
            "somatic_af_tn_wgs": obj.get("somatic_af_tn_wgs"),
            "somatic_af_tn_wxs": obj.get("somatic_af_tn_wxs"),
            "somatic_af_to_wgs": obj.get("somatic_af_to_wgs"),
            "somatic_af_to_wxs": obj.get("somatic_af_to_wxs"),
            "somatic_hom_tn_wgs": obj.get("somatic_hom_tn_wgs"),
            "somatic_hom_tn_wxs": obj.get("somatic_hom_tn_wxs"),
            "somatic_hom_to_wgs": obj.get("somatic_hom_to_wgs"),
            "somatic_hom_to_wxs": obj.get("somatic_hom_to_wxs"),
            "somatic_pc_tn_wgs": obj.get("somatic_pc_tn_wgs"),
            "somatic_pc_tn_wxs": obj.get("somatic_pc_tn_wxs"),
            "somatic_pc_to_wgs": obj.get("somatic_pc_to_wgs"),
            "somatic_pc_to_wxs": obj.get("somatic_pc_to_wxs"),
            "somatic_pf_tn_wgs": obj.get("somatic_pf_tn_wgs"),
            "somatic_pf_tn_wxs": obj.get("somatic_pf_tn_wxs"),
            "somatic_pf_to_wgs": obj.get("somatic_pf_to_wgs"),
            "somatic_pf_to_wxs": obj.get("somatic_pf_to_wxs"),
            "somatic_pn_tn_wgs": obj.get("somatic_pn_tn_wgs"),
            "somatic_pn_tn_wxs": obj.get("somatic_pn_tn_wxs"),
            "somatic_pn_to_wgs": obj.get("somatic_pn_to_wgs"),
            "somatic_pn_to_wxs": obj.get("somatic_pn_to_wxs"),
            "spliceai_ds": obj.get("spliceai_ds"),
            "spliceai_type": obj.get("spliceai_type"),
            "sq": obj.get("sq"),
            "start": obj.get("start"),
            "symbol": obj.get("symbol"),
            "transcript_id": obj.get("transcript_id"),
            "vep_impact": obj.get("vep_impact")
        })
        return _obj


