# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GermlineCNVOccurrence(BaseModel):
    """
    GermlineCNVOccurrence represents a germline CNV occurrence
    """ # noqa: E501
    aliquot: Optional[StrictStr] = None
    bc: Optional[StrictInt] = None
    calls: Optional[List[StrictInt]] = None
    chromosome: StrictStr
    ciend: Optional[List[StrictInt]] = None
    cipos: Optional[List[StrictInt]] = None
    cn: Optional[StrictInt] = None
    cnv_id: StrictStr
    cytoband: Optional[List[StrictStr]] = None
    end: StrictInt
    filter: Optional[StrictStr] = None
    gnomad_sc: Optional[StrictInt] = None
    gnomad_sf: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_sn: Optional[StrictInt] = None
    length: StrictInt
    name: StrictStr
    nb_genes: Optional[StrictInt] = None
    nb_snv: Optional[StrictInt] = None
    pe: Optional[List[StrictInt]] = None
    quality: Optional[Union[StrictFloat, StrictInt]] = None
    reflen: Optional[StrictInt] = None
    seq_id: StrictInt
    sm: Optional[Union[StrictFloat, StrictInt]] = None
    start: StrictInt
    svlen: Optional[StrictInt] = None
    svtype: Optional[StrictStr] = None
    symbol: Optional[List[StrictStr]] = None
    type: StrictStr
    __properties: ClassVar[List[str]] = ["aliquot", "bc", "calls", "chromosome", "ciend", "cipos", "cn", "cnv_id", "cytoband", "end", "filter", "gnomad_sc", "gnomad_sf", "gnomad_sn", "length", "name", "nb_genes", "nb_snv", "pe", "quality", "reflen", "seq_id", "sm", "start", "svlen", "svtype", "symbol", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GermlineCNVOccurrence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GermlineCNVOccurrence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aliquot": obj.get("aliquot"),
            "bc": obj.get("bc"),
            "calls": obj.get("calls"),
            "chromosome": obj.get("chromosome"),
            "ciend": obj.get("ciend"),
            "cipos": obj.get("cipos"),
            "cn": obj.get("cn"),
            "cnv_id": obj.get("cnv_id"),
            "cytoband": obj.get("cytoband"),
            "end": obj.get("end"),
            "filter": obj.get("filter"),
            "gnomad_sc": obj.get("gnomad_sc"),
            "gnomad_sf": obj.get("gnomad_sf"),
            "gnomad_sn": obj.get("gnomad_sn"),
            "length": obj.get("length"),
            "name": obj.get("name"),
            "nb_genes": obj.get("nb_genes"),
            "nb_snv": obj.get("nb_snv"),
            "pe": obj.get("pe"),
            "quality": obj.get("quality"),
            "reflen": obj.get("reflen"),
            "seq_id": obj.get("seq_id"),
            "sm": obj.get("sm"),
            "start": obj.get("start"),
            "svlen": obj.get("svlen"),
            "svtype": obj.get("svtype"),
            "symbol": obj.get("symbol"),
            "type": obj.get("type")
        })
        return _obj


