# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.search_criterion import SearchCriterion
from radiant_python.models.sort_body import SortBody
from typing import Optional, Set
from typing_extensions import Self

class ListBodyWithCriteria(BaseModel):
    """
    Body of a list request with search criteria
    """ # noqa: E501
    additional_fields: Optional[List[StrictStr]] = None
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    page_index: Optional[StrictInt] = None
    search_criteria: Optional[List[SearchCriterion]] = None
    sort: Optional[List[SortBody]] = None
    __properties: ClassVar[List[str]] = ["additional_fields", "limit", "offset", "page_index", "search_criteria", "sort"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListBodyWithCriteria from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in search_criteria (list)
        _items = []
        if self.search_criteria:
            for _item_search_criteria in self.search_criteria:
                if _item_search_criteria:
                    _items.append(_item_search_criteria.to_dict())
            _dict['search_criteria'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sort (list)
        _items = []
        if self.sort:
            for _item_sort in self.sort:
                if _item_sort:
                    _items.append(_item_sort.to_dict())
            _dict['sort'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListBodyWithCriteria from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additional_fields": obj.get("additional_fields"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "page_index": obj.get("page_index"),
            "search_criteria": [SearchCriterion.from_dict(_item) for _item in obj["search_criteria"]] if obj.get("search_criteria") is not None else None,
            "sort": [SortBody.from_dict(_item) for _item in obj["sort"]] if obj.get("sort") is not None else None
        })
        return _obj


