# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PatientListItem(BaseModel):
    """
    A PCX patient in the patient list
    """ # noqa: E501
    age_at_initial_dx_days: Optional[StrictInt] = None
    age_at_vital_status_days: Optional[StrictInt] = None
    birth_year: Optional[StrictInt] = None
    can_read_phi: StrictBool
    case_count: StrictInt = Field(description="Portal cases, 0 outside the portal")
    cns_integrated_diagnosis: Optional[StrictStr] = Field(default=None, description="From the initial event")
    family_name: StrictStr = Field(description="Placeholder when can_read_phi is false")
    gender: StrictStr
    given_name: StrictStr = Field(description="Placeholder when can_read_phi is false")
    has_imaging: StrictBool
    organization_code: StrictStr
    organization_name: StrictStr
    patient_id: StrictStr
    patient_id_type: StrictStr
    patient_key: StrictStr = Field(description="Opaque key for the patient page URL, the same for every user")
    radiant_patient_id: Optional[StrictInt] = Field(default=None, description="Portal patient id, null outside the portal")
    survival_days: Optional[StrictInt] = Field(default=None, description="Vital status day minus initial diagnosis day")
    vital_status: StrictStr
    __properties: ClassVar[List[str]] = ["age_at_initial_dx_days", "age_at_vital_status_days", "birth_year", "can_read_phi", "case_count", "cns_integrated_diagnosis", "family_name", "gender", "given_name", "has_imaging", "organization_code", "organization_name", "patient_id", "patient_id_type", "patient_key", "radiant_patient_id", "survival_days", "vital_status"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['female', 'male', 'unknown']):
            raise ValueError("must be one of enum values ('female', 'male', 'unknown')")
        return value

    @field_validator('patient_id_type')
    def patient_id_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['mrn', 'research_id']):
            raise ValueError("must be one of enum values ('mrn', 'research_id')")
        return value

    @field_validator('vital_status')
    def vital_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['alive', 'deceased']):
            raise ValueError("must be one of enum values ('alive', 'deceased')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatientListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatientListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age_at_initial_dx_days": obj.get("age_at_initial_dx_days"),
            "age_at_vital_status_days": obj.get("age_at_vital_status_days"),
            "birth_year": obj.get("birth_year"),
            "can_read_phi": obj.get("can_read_phi"),
            "case_count": obj.get("case_count"),
            "cns_integrated_diagnosis": obj.get("cns_integrated_diagnosis"),
            "family_name": obj.get("family_name"),
            "gender": obj.get("gender"),
            "given_name": obj.get("given_name"),
            "has_imaging": obj.get("has_imaging"),
            "organization_code": obj.get("organization_code"),
            "organization_name": obj.get("organization_name"),
            "patient_id": obj.get("patient_id"),
            "patient_id_type": obj.get("patient_id_type"),
            "patient_key": obj.get("patient_key"),
            "radiant_patient_id": obj.get("radiant_patient_id"),
            "survival_days": obj.get("survival_days"),
            "vital_status": obj.get("vital_status")
        })
        return _obj


