# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.patient_case import PatientCase
from radiant_python.models.patient_day_date import PatientDayDate
from radiant_python.models.patient_event import PatientEvent
from radiant_python.models.patient_imaging_session import PatientImagingSession
from radiant_python.models.patient_key_dates import PatientKeyDates
from radiant_python.models.patient_radiation import PatientRadiation
from radiant_python.models.patient_surgery import PatientSurgery
from radiant_python.models.patient_therapy import PatientTherapy
from radiant_python.models.patient_treatment_summary import PatientTreatmentSummary
from typing import Optional, Set
from typing_extensions import Self

class PatientEntity(BaseModel):
    """
    Data of the patient page
    """ # noqa: E501
    age_at_initial_dx_days: Optional[StrictInt] = None
    age_at_vital_status_days: Optional[StrictInt] = None
    birth_date: Optional[date] = None
    birth_year: Optional[StrictInt] = None
    can_read_phi: StrictBool
    case_count: StrictInt = Field(description="Portal cases, 0 outside the portal")
    cases: List[PatientCase]
    cns_integrated_diagnosis: Optional[StrictStr] = Field(default=None, description="From the initial event")
    cns_integrated_diagnosis_source: Optional[StrictStr] = Field(default=None, description="Dataset of the diagnosis, e.g. CBTN or OpenPedCan")
    data_type_cohort: Optional[StrictStr] = None
    diagnosis_type_cohort: Optional[StrictStr] = None
    ethnicity: Optional[StrictStr] = None
    events: List[PatientEvent]
    family_name: StrictStr = Field(description="Placeholder when can_read_phi is false")
    gender: StrictStr
    given_name: StrictStr = Field(description="Placeholder when can_read_phi is false")
    has_imaging: StrictBool
    imaging: List[PatientImagingSession]
    initial_diagnosis_evidence_url: Optional[StrictStr] = Field(default=None, description="BRIM link, format to be defined")
    key_dates: PatientKeyDates
    organization_code: StrictStr
    organization_name: StrictStr
    patient_id: StrictStr
    patient_id_type: StrictStr
    patient_key: StrictStr = Field(description="Opaque key for the patient page URL, the same for every user")
    postal_code: Optional[StrictStr] = Field(default=None, description="Full with PHI access, 3 digits + XX otherwise")
    race: Optional[StrictStr] = None
    radiant_patient_id: Optional[StrictInt] = Field(default=None, description="Portal patient id, null outside the portal")
    radiations: List[PatientRadiation]
    surgeries: List[PatientSurgery]
    survival_days: Optional[StrictInt] = Field(default=None, description="Vital status day minus initial diagnosis day")
    therapies: List[PatientTherapy]
    treatment_summary: Optional[PatientTreatmentSummary] = None
    vital_status: StrictStr
    vital_status_at: PatientDayDate
    __properties: ClassVar[List[str]] = ["age_at_initial_dx_days", "age_at_vital_status_days", "birth_date", "birth_year", "can_read_phi", "case_count", "cases", "cns_integrated_diagnosis", "cns_integrated_diagnosis_source", "data_type_cohort", "diagnosis_type_cohort", "ethnicity", "events", "family_name", "gender", "given_name", "has_imaging", "imaging", "initial_diagnosis_evidence_url", "key_dates", "organization_code", "organization_name", "patient_id", "patient_id_type", "patient_key", "postal_code", "race", "radiant_patient_id", "radiations", "surgeries", "survival_days", "therapies", "treatment_summary", "vital_status", "vital_status_at"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['female', 'male', 'unknown']):
            raise ValueError("must be one of enum values ('female', 'male', 'unknown')")
        return value

    @field_validator('patient_id_type')
    def patient_id_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['mrn', 'research_id']):
            raise ValueError("must be one of enum values ('mrn', 'research_id')")
        return value

    @field_validator('vital_status')
    def vital_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['alive', 'deceased']):
            raise ValueError("must be one of enum values ('alive', 'deceased')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatientEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cases (list)
        _items = []
        if self.cases:
            for _item_cases in self.cases:
                if _item_cases:
                    _items.append(_item_cases.to_dict())
            _dict['cases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in imaging (list)
        _items = []
        if self.imaging:
            for _item_imaging in self.imaging:
                if _item_imaging:
                    _items.append(_item_imaging.to_dict())
            _dict['imaging'] = _items
        # override the default output from pydantic by calling `to_dict()` of key_dates
        if self.key_dates:
            _dict['key_dates'] = self.key_dates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in radiations (list)
        _items = []
        if self.radiations:
            for _item_radiations in self.radiations:
                if _item_radiations:
                    _items.append(_item_radiations.to_dict())
            _dict['radiations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in surgeries (list)
        _items = []
        if self.surgeries:
            for _item_surgeries in self.surgeries:
                if _item_surgeries:
                    _items.append(_item_surgeries.to_dict())
            _dict['surgeries'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in therapies (list)
        _items = []
        if self.therapies:
            for _item_therapies in self.therapies:
                if _item_therapies:
                    _items.append(_item_therapies.to_dict())
            _dict['therapies'] = _items
        # override the default output from pydantic by calling `to_dict()` of treatment_summary
        if self.treatment_summary:
            _dict['treatment_summary'] = self.treatment_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vital_status_at
        if self.vital_status_at:
            _dict['vital_status_at'] = self.vital_status_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatientEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age_at_initial_dx_days": obj.get("age_at_initial_dx_days"),
            "age_at_vital_status_days": obj.get("age_at_vital_status_days"),
            "birth_date": obj.get("birth_date"),
            "birth_year": obj.get("birth_year"),
            "can_read_phi": obj.get("can_read_phi"),
            "case_count": obj.get("case_count"),
            "cases": [PatientCase.from_dict(_item) for _item in obj["cases"]] if obj.get("cases") is not None else None,
            "cns_integrated_diagnosis": obj.get("cns_integrated_diagnosis"),
            "cns_integrated_diagnosis_source": obj.get("cns_integrated_diagnosis_source"),
            "data_type_cohort": obj.get("data_type_cohort"),
            "diagnosis_type_cohort": obj.get("diagnosis_type_cohort"),
            "ethnicity": obj.get("ethnicity"),
            "events": [PatientEvent.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "family_name": obj.get("family_name"),
            "gender": obj.get("gender"),
            "given_name": obj.get("given_name"),
            "has_imaging": obj.get("has_imaging"),
            "imaging": [PatientImagingSession.from_dict(_item) for _item in obj["imaging"]] if obj.get("imaging") is not None else None,
            "initial_diagnosis_evidence_url": obj.get("initial_diagnosis_evidence_url"),
            "key_dates": PatientKeyDates.from_dict(obj["key_dates"]) if obj.get("key_dates") is not None else None,
            "organization_code": obj.get("organization_code"),
            "organization_name": obj.get("organization_name"),
            "patient_id": obj.get("patient_id"),
            "patient_id_type": obj.get("patient_id_type"),
            "patient_key": obj.get("patient_key"),
            "postal_code": obj.get("postal_code"),
            "race": obj.get("race"),
            "radiant_patient_id": obj.get("radiant_patient_id"),
            "radiations": [PatientRadiation.from_dict(_item) for _item in obj["radiations"]] if obj.get("radiations") is not None else None,
            "surgeries": [PatientSurgery.from_dict(_item) for _item in obj["surgeries"]] if obj.get("surgeries") is not None else None,
            "survival_days": obj.get("survival_days"),
            "therapies": [PatientTherapy.from_dict(_item) for _item in obj["therapies"]] if obj.get("therapies") is not None else None,
            "treatment_summary": PatientTreatmentSummary.from_dict(obj["treatment_summary"]) if obj.get("treatment_summary") is not None else None,
            "vital_status": obj.get("vital_status"),
            "vital_status_at": PatientDayDate.from_dict(obj["vital_status_at"]) if obj.get("vital_status_at") is not None else None
        })
        return _obj


