# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.patient_day_date import PatientDayDate
from typing import Optional, Set
from typing_extensions import Self

class PatientTherapy(BaseModel):
    """
    Medical therapy of a patient
    """ # noqa: E501
    chemotherapy_agents: List[StrictStr]
    chemotherapy_type: Optional[StrictStr] = None
    is_initial_treatment: Optional[StrictBool] = Field(default=None, description="null when Not Reported")
    protocol_name_and_arm: Optional[StrictStr] = None
    start: PatientDayDate
    stop: PatientDayDate
    __properties: ClassVar[List[str]] = ["chemotherapy_agents", "chemotherapy_type", "is_initial_treatment", "protocol_name_and_arm", "start", "stop"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatientTherapy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of start
        if self.start:
            _dict['start'] = self.start.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop
        if self.stop:
            _dict['stop'] = self.stop.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatientTherapy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chemotherapy_agents": obj.get("chemotherapy_agents"),
            "chemotherapy_type": obj.get("chemotherapy_type"),
            "is_initial_treatment": obj.get("is_initial_treatment"),
            "protocol_name_and_arm": obj.get("protocol_name_and_arm"),
            "start": PatientDayDate.from_dict(obj["start"]) if obj.get("start") is not None else None,
            "stop": PatientDayDate.from_dict(obj["stop"]) if obj.get("stop") is not None else None
        })
        return _obj


