# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.patient_day_date import PatientDayDate
from typing import Optional, Set
from typing_extensions import Self

class PatientTreatmentSummary(BaseModel):
    """
    Initial treatment summary of a patient
    """ # noqa: E501
    first_event: PatientDayDate
    first_methotrexate: PatientDayDate
    first_radiation: PatientDayDate
    had_initial_methotrexate: StrictBool
    had_initial_radiation: StrictBool
    initial_dx: PatientDayDate
    initial_treatment_order: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["first_event", "first_methotrexate", "first_radiation", "had_initial_methotrexate", "had_initial_radiation", "initial_dx", "initial_treatment_order"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatientTreatmentSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of first_event
        if self.first_event:
            _dict['first_event'] = self.first_event.to_dict()
        # override the default output from pydantic by calling `to_dict()` of first_methotrexate
        if self.first_methotrexate:
            _dict['first_methotrexate'] = self.first_methotrexate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of first_radiation
        if self.first_radiation:
            _dict['first_radiation'] = self.first_radiation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of initial_dx
        if self.initial_dx:
            _dict['initial_dx'] = self.initial_dx.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatientTreatmentSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "first_event": PatientDayDate.from_dict(obj["first_event"]) if obj.get("first_event") is not None else None,
            "first_methotrexate": PatientDayDate.from_dict(obj["first_methotrexate"]) if obj.get("first_methotrexate") is not None else None,
            "first_radiation": PatientDayDate.from_dict(obj["first_radiation"]) if obj.get("first_radiation") is not None else None,
            "had_initial_methotrexate": obj.get("had_initial_methotrexate"),
            "had_initial_radiation": obj.get("had_initial_radiation"),
            "initial_dx": PatientDayDate.from_dict(obj["initial_dx"]) if obj.get("initial_dx") is not None else None,
            "initial_treatment_order": obj.get("initial_treatment_order")
        })
        return _obj


