# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Sequencing(BaseModel):
    """
    Sequencing represents a sequencing
    """ # noqa: E501
    affected_status: Optional[StrictStr] = None
    analysis_type: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    experimental_strategy: Optional[StrictStr] = None
    family_role: Optional[StrictStr] = None
    part: Optional[StrictInt] = None
    patient_id: Optional[StrictInt] = None
    request_priority: Optional[StrictStr] = None
    sample_id: Optional[StrictInt] = None
    seq_id: Optional[StrictInt] = None
    sex: Optional[StrictStr] = None
    task_id: Optional[StrictInt] = None
    updated_at: Optional[StrictStr] = None
    vcf_filepath: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["affected_status", "analysis_type", "created_at", "experimental_strategy", "family_role", "part", "patient_id", "request_priority", "sample_id", "seq_id", "sex", "task_id", "updated_at", "vcf_filepath"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sequencing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sequencing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "affected_status": obj.get("affected_status"),
            "analysis_type": obj.get("analysis_type"),
            "created_at": obj.get("created_at"),
            "experimental_strategy": obj.get("experimental_strategy"),
            "family_role": obj.get("family_role"),
            "part": obj.get("part"),
            "patient_id": obj.get("patient_id"),
            "request_priority": obj.get("request_priority"),
            "sample_id": obj.get("sample_id"),
            "seq_id": obj.get("seq_id"),
            "sex": obj.get("sex"),
            "task_id": obj.get("task_id"),
            "updated_at": obj.get("updated_at"),
            "vcf_filepath": obj.get("vcf_filepath")
        })
        return _obj


