# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from radiant_python.models.occurrence_flag_type import OccurrenceFlagType
from radiant_python.models.vep_impact import VepImpact
from typing import Optional, Set
from typing_extensions import Self

class SomaticSNVOccurrence(BaseModel):
    """
    SomaticSNVOccurrence
    """ # noqa: E501
    aa_change: StrictStr
    ad_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    alternate: StrictStr
    aq: Optional[Union[StrictFloat, StrictInt]] = None
    chromosome: StrictStr
    clinvar: List[StrictStr]
    cmc_mutation_url: Optional[StrictStr] = None
    cmc_sample_mutated: Optional[StrictInt] = None
    cmc_sample_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    cmc_tier: Optional[StrictStr] = None
    end: StrictInt
    flag_type: Optional[OccurrenceFlagType] = None
    germline_af_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wgs_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wgs_not_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_af_wxs_not_affected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM.")
    germline_hom_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wgs_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wgs_not_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_hom_wxs_not_affected: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM call")
    germline_pc_wgs: StrictInt
    germline_pc_wgs_affected: Optional[StrictInt] = None
    germline_pc_wgs_not_affected: Optional[StrictInt] = None
    germline_pc_wxs: Optional[StrictInt] = None
    germline_pc_wxs_affected: Optional[StrictInt] = None
    germline_pc_wxs_not_affected: Optional[StrictInt] = None
    germline_pf_wgs: Union[StrictFloat, StrictInt]
    germline_pf_wgs_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wgs_not_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pf_wxs_not_affected: Optional[Union[StrictFloat, StrictInt]] = None
    germline_pn_wgs: Optional[StrictInt] = None
    germline_pn_wgs_affected: Optional[StrictInt] = None
    germline_pn_wgs_not_affected: Optional[StrictInt] = None
    germline_pn_wxs: Optional[StrictInt] = None
    germline_pn_wxs_affected: Optional[StrictInt] = None
    germline_pn_wxs_not_affected: Optional[StrictInt] = None
    gnomad_v3_af: Union[StrictFloat, StrictInt]
    has_interpretation: StrictBool
    has_note: StrictBool
    hgvsg: StrictStr
    hotspot: StrictBool
    is_canonical: StrictBool
    is_mane_plus: StrictBool
    is_mane_select: StrictBool
    locus_id: StrictStr
    omim_inheritance_code: List[StrictStr]
    picked_consequences: List[StrictStr]
    reference: StrictStr
    rsnumber: StrictStr
    seq_id: StrictInt
    somatic_af_tn_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_tn_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_to_wgs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_af_to_wxs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate allele frequency, (pc + hom) / (2 * pn). Assumes diploid genotypes; HEM is counted as HOM. Does not account for tumor purity, copy number or loss of heterozygosity.")
    somatic_hom_tn_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_tn_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_to_wgs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_hom_to_wxs: Optional[StrictInt] = Field(default=None, description="Number of patients with a HOM or HEM tumor call")
    somatic_pc_tn_wgs: StrictInt
    somatic_pc_tn_wxs: Optional[StrictInt] = None
    somatic_pc_to_wgs: StrictInt
    somatic_pc_to_wxs: Optional[StrictInt] = None
    somatic_pf_tn_wgs: Union[StrictFloat, StrictInt]
    somatic_pf_tn_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pf_to_wgs: Union[StrictFloat, StrictInt]
    somatic_pf_to_wxs: Optional[Union[StrictFloat, StrictInt]] = None
    somatic_pn_tn_wgs: Optional[StrictInt] = None
    somatic_pn_tn_wxs: Optional[StrictInt] = None
    somatic_pn_to_wgs: Optional[StrictInt] = None
    somatic_pn_to_wxs: Optional[StrictInt] = None
    sq: Optional[Union[StrictFloat, StrictInt]] = None
    start: StrictInt
    symbol: StrictStr
    task_id: StrictInt
    transcript_id: Optional[StrictStr] = None
    variant_class: StrictStr
    vep_impact: VepImpact
    __properties: ClassVar[List[str]] = ["aa_change", "ad_ratio", "alternate", "aq", "chromosome", "clinvar", "cmc_mutation_url", "cmc_sample_mutated", "cmc_sample_ratio", "cmc_tier", "end", "flag_type", "germline_af_wgs", "germline_af_wgs_affected", "germline_af_wgs_not_affected", "germline_af_wxs", "germline_af_wxs_affected", "germline_af_wxs_not_affected", "germline_hom_wgs", "germline_hom_wgs_affected", "germline_hom_wgs_not_affected", "germline_hom_wxs", "germline_hom_wxs_affected", "germline_hom_wxs_not_affected", "germline_pc_wgs", "germline_pc_wgs_affected", "germline_pc_wgs_not_affected", "germline_pc_wxs", "germline_pc_wxs_affected", "germline_pc_wxs_not_affected", "germline_pf_wgs", "germline_pf_wgs_affected", "germline_pf_wgs_not_affected", "germline_pf_wxs", "germline_pf_wxs_affected", "germline_pf_wxs_not_affected", "germline_pn_wgs", "germline_pn_wgs_affected", "germline_pn_wgs_not_affected", "germline_pn_wxs", "germline_pn_wxs_affected", "germline_pn_wxs_not_affected", "gnomad_v3_af", "has_interpretation", "has_note", "hgvsg", "hotspot", "is_canonical", "is_mane_plus", "is_mane_select", "locus_id", "omim_inheritance_code", "picked_consequences", "reference", "rsnumber", "seq_id", "somatic_af_tn_wgs", "somatic_af_tn_wxs", "somatic_af_to_wgs", "somatic_af_to_wxs", "somatic_hom_tn_wgs", "somatic_hom_tn_wxs", "somatic_hom_to_wgs", "somatic_hom_to_wxs", "somatic_pc_tn_wgs", "somatic_pc_tn_wxs", "somatic_pc_to_wgs", "somatic_pc_to_wxs", "somatic_pf_tn_wgs", "somatic_pf_tn_wxs", "somatic_pf_to_wgs", "somatic_pf_to_wxs", "somatic_pn_tn_wgs", "somatic_pn_tn_wxs", "somatic_pn_to_wgs", "somatic_pn_to_wxs", "sq", "start", "symbol", "task_id", "transcript_id", "variant_class", "vep_impact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SomaticSNVOccurrence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SomaticSNVOccurrence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aa_change": obj.get("aa_change"),
            "ad_ratio": obj.get("ad_ratio"),
            "alternate": obj.get("alternate"),
            "aq": obj.get("aq"),
            "chromosome": obj.get("chromosome"),
            "clinvar": obj.get("clinvar"),
            "cmc_mutation_url": obj.get("cmc_mutation_url"),
            "cmc_sample_mutated": obj.get("cmc_sample_mutated"),
            "cmc_sample_ratio": obj.get("cmc_sample_ratio"),
            "cmc_tier": obj.get("cmc_tier"),
            "end": obj.get("end"),
            "flag_type": obj.get("flag_type"),
            "germline_af_wgs": obj.get("germline_af_wgs"),
            "germline_af_wgs_affected": obj.get("germline_af_wgs_affected"),
            "germline_af_wgs_not_affected": obj.get("germline_af_wgs_not_affected"),
            "germline_af_wxs": obj.get("germline_af_wxs"),
            "germline_af_wxs_affected": obj.get("germline_af_wxs_affected"),
            "germline_af_wxs_not_affected": obj.get("germline_af_wxs_not_affected"),
            "germline_hom_wgs": obj.get("germline_hom_wgs"),
            "germline_hom_wgs_affected": obj.get("germline_hom_wgs_affected"),
            "germline_hom_wgs_not_affected": obj.get("germline_hom_wgs_not_affected"),
            "germline_hom_wxs": obj.get("germline_hom_wxs"),
            "germline_hom_wxs_affected": obj.get("germline_hom_wxs_affected"),
            "germline_hom_wxs_not_affected": obj.get("germline_hom_wxs_not_affected"),
            "germline_pc_wgs": obj.get("germline_pc_wgs"),
            "germline_pc_wgs_affected": obj.get("germline_pc_wgs_affected"),
            "germline_pc_wgs_not_affected": obj.get("germline_pc_wgs_not_affected"),
            "germline_pc_wxs": obj.get("germline_pc_wxs"),
            "germline_pc_wxs_affected": obj.get("germline_pc_wxs_affected"),
            "germline_pc_wxs_not_affected": obj.get("germline_pc_wxs_not_affected"),
            "germline_pf_wgs": obj.get("germline_pf_wgs"),
            "germline_pf_wgs_affected": obj.get("germline_pf_wgs_affected"),
            "germline_pf_wgs_not_affected": obj.get("germline_pf_wgs_not_affected"),
            "germline_pf_wxs": obj.get("germline_pf_wxs"),
            "germline_pf_wxs_affected": obj.get("germline_pf_wxs_affected"),
            "germline_pf_wxs_not_affected": obj.get("germline_pf_wxs_not_affected"),
            "germline_pn_wgs": obj.get("germline_pn_wgs"),
            "germline_pn_wgs_affected": obj.get("germline_pn_wgs_affected"),
            "germline_pn_wgs_not_affected": obj.get("germline_pn_wgs_not_affected"),
            "germline_pn_wxs": obj.get("germline_pn_wxs"),
            "germline_pn_wxs_affected": obj.get("germline_pn_wxs_affected"),
            "germline_pn_wxs_not_affected": obj.get("germline_pn_wxs_not_affected"),
            "gnomad_v3_af": obj.get("gnomad_v3_af"),
            "has_interpretation": obj.get("has_interpretation"),
            "has_note": obj.get("has_note"),
            "hgvsg": obj.get("hgvsg"),
            "hotspot": obj.get("hotspot"),
            "is_canonical": obj.get("is_canonical"),
            "is_mane_plus": obj.get("is_mane_plus"),
            "is_mane_select": obj.get("is_mane_select"),
            "locus_id": obj.get("locus_id"),
            "omim_inheritance_code": obj.get("omim_inheritance_code"),
            "picked_consequences": obj.get("picked_consequences"),
            "reference": obj.get("reference"),
            "rsnumber": obj.get("rsnumber"),
            "seq_id": obj.get("seq_id"),
            "somatic_af_tn_wgs": obj.get("somatic_af_tn_wgs"),
            "somatic_af_tn_wxs": obj.get("somatic_af_tn_wxs"),
            "somatic_af_to_wgs": obj.get("somatic_af_to_wgs"),
            "somatic_af_to_wxs": obj.get("somatic_af_to_wxs"),
            "somatic_hom_tn_wgs": obj.get("somatic_hom_tn_wgs"),
            "somatic_hom_tn_wxs": obj.get("somatic_hom_tn_wxs"),
            "somatic_hom_to_wgs": obj.get("somatic_hom_to_wgs"),
            "somatic_hom_to_wxs": obj.get("somatic_hom_to_wxs"),
            "somatic_pc_tn_wgs": obj.get("somatic_pc_tn_wgs"),
            "somatic_pc_tn_wxs": obj.get("somatic_pc_tn_wxs"),
            "somatic_pc_to_wgs": obj.get("somatic_pc_to_wgs"),
            "somatic_pc_to_wxs": obj.get("somatic_pc_to_wxs"),
            "somatic_pf_tn_wgs": obj.get("somatic_pf_tn_wgs"),
            "somatic_pf_tn_wxs": obj.get("somatic_pf_tn_wxs"),
            "somatic_pf_to_wgs": obj.get("somatic_pf_to_wgs"),
            "somatic_pf_to_wxs": obj.get("somatic_pf_to_wxs"),
            "somatic_pn_tn_wgs": obj.get("somatic_pn_tn_wgs"),
            "somatic_pn_tn_wxs": obj.get("somatic_pn_tn_wxs"),
            "somatic_pn_to_wgs": obj.get("somatic_pn_to_wgs"),
            "somatic_pn_to_wxs": obj.get("somatic_pn_to_wxs"),
            "sq": obj.get("sq"),
            "start": obj.get("start"),
            "symbol": obj.get("symbol"),
            "task_id": obj.get("task_id"),
            "transcript_id": obj.get("transcript_id"),
            "variant_class": obj.get("variant_class"),
            "vep_impact": obj.get("vep_impact")
        })
        return _obj


