# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from radiant_python.models.omim_gene_panel import OmimGenePanel
from radiant_python.models.vep_impact import VepImpact
from typing import Optional, Set
from typing_extensions import Self

class VariantOverview(BaseModel):
    """
    VariantOverview
    """ # noqa: E501
    aa_change: Optional[StrictStr] = None
    cadd_phred: Optional[Union[StrictFloat, StrictInt]] = None
    cadd_score: Optional[Union[StrictFloat, StrictInt]] = None
    clinvar: Optional[List[StrictStr]] = None
    clinvar_name: Optional[StrictStr] = None
    dann_score: Optional[Union[StrictFloat, StrictInt]] = None
    dna_change: Optional[StrictStr] = None
    exomiser_acmg_classification_counts: Optional[Dict[str, StrictInt]] = None
    exon_rank: Optional[StrictInt] = None
    exon_total: Optional[StrictInt] = None
    fathmm_pred: Optional[StrictStr] = None
    fathmm_score: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_loeuf: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_pli: Optional[Union[StrictFloat, StrictInt]] = None
    gnomad_v3_af: Union[StrictFloat, StrictInt]
    interpretation_classification_counts: Optional[Dict[str, StrictInt]] = None
    is_canonical: StrictBool
    is_mane_plus: StrictBool
    is_mane_select: StrictBool
    locus: StrictStr
    lrt_pred: Optional[StrictStr] = None
    lrt_score: Optional[Union[StrictFloat, StrictInt]] = None
    omim_conditions: Optional[List[OmimGenePanel]] = None
    pc_wgs: Optional[StrictInt] = None
    pf_wgs: Union[StrictFloat, StrictInt]
    phylo_p17way_primate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="phyloP17way_primate")
    picked_consequences: List[StrictStr]
    pn_wgs: Optional[StrictInt] = None
    polyphen2_hvar_pred: Optional[StrictStr] = None
    polyphen2_hvar_score: Optional[Union[StrictFloat, StrictInt]] = None
    revel_score: Optional[Union[StrictFloat, StrictInt]] = None
    rsnumber: Optional[StrictStr] = None
    sift_pred: Optional[StrictStr] = None
    sift_score: Optional[Union[StrictFloat, StrictInt]] = None
    spliceai_ds: Optional[Union[StrictFloat, StrictInt]] = None
    spliceai_type: Optional[List[StrictStr]] = None
    symbol: Optional[StrictStr] = None
    transcript_id: Optional[StrictStr] = None
    vep_impact: Optional[VepImpact] = None
    __properties: ClassVar[List[str]] = ["aa_change", "cadd_phred", "cadd_score", "clinvar", "clinvar_name", "dann_score", "dna_change", "exomiser_acmg_classification_counts", "exon_rank", "exon_total", "fathmm_pred", "fathmm_score", "gnomad_loeuf", "gnomad_pli", "gnomad_v3_af", "interpretation_classification_counts", "is_canonical", "is_mane_plus", "is_mane_select", "locus", "lrt_pred", "lrt_score", "omim_conditions", "pc_wgs", "pf_wgs", "phyloP17way_primate", "picked_consequences", "pn_wgs", "polyphen2_hvar_pred", "polyphen2_hvar_score", "revel_score", "rsnumber", "sift_pred", "sift_score", "spliceai_ds", "spliceai_type", "symbol", "transcript_id", "vep_impact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariantOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in omim_conditions (list)
        _items = []
        if self.omim_conditions:
            for _item_omim_conditions in self.omim_conditions:
                if _item_omim_conditions:
                    _items.append(_item_omim_conditions.to_dict())
            _dict['omim_conditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariantOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aa_change": obj.get("aa_change"),
            "cadd_phred": obj.get("cadd_phred"),
            "cadd_score": obj.get("cadd_score"),
            "clinvar": obj.get("clinvar"),
            "clinvar_name": obj.get("clinvar_name"),
            "dann_score": obj.get("dann_score"),
            "dna_change": obj.get("dna_change"),
            "exomiser_acmg_classification_counts": obj.get("exomiser_acmg_classification_counts"),
            "exon_rank": obj.get("exon_rank"),
            "exon_total": obj.get("exon_total"),
            "fathmm_pred": obj.get("fathmm_pred"),
            "fathmm_score": obj.get("fathmm_score"),
            "gnomad_loeuf": obj.get("gnomad_loeuf"),
            "gnomad_pli": obj.get("gnomad_pli"),
            "gnomad_v3_af": obj.get("gnomad_v3_af"),
            "interpretation_classification_counts": obj.get("interpretation_classification_counts"),
            "is_canonical": obj.get("is_canonical"),
            "is_mane_plus": obj.get("is_mane_plus"),
            "is_mane_select": obj.get("is_mane_select"),
            "locus": obj.get("locus"),
            "lrt_pred": obj.get("lrt_pred"),
            "lrt_score": obj.get("lrt_score"),
            "omim_conditions": [OmimGenePanel.from_dict(_item) for _item in obj["omim_conditions"]] if obj.get("omim_conditions") is not None else None,
            "pc_wgs": obj.get("pc_wgs"),
            "pf_wgs": obj.get("pf_wgs"),
            "phyloP17way_primate": obj.get("phyloP17way_primate"),
            "picked_consequences": obj.get("picked_consequences"),
            "pn_wgs": obj.get("pn_wgs"),
            "polyphen2_hvar_pred": obj.get("polyphen2_hvar_pred"),
            "polyphen2_hvar_score": obj.get("polyphen2_hvar_score"),
            "revel_score": obj.get("revel_score"),
            "rsnumber": obj.get("rsnumber"),
            "sift_pred": obj.get("sift_pred"),
            "sift_score": obj.get("sift_score"),
            "spliceai_ds": obj.get("spliceai_ds"),
            "spliceai_type": obj.get("spliceai_type"),
            "symbol": obj.get("symbol"),
            "transcript_id": obj.get("transcript_id"),
            "vep_impact": obj.get("vep_impact")
        })
        return _obj


