# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from radiant_python.models.aggregation import Aggregation
from typing import Optional, Set
from typing_extensions import Self

class VariantCasesFilters(BaseModel):
    """
    VariantCasesFilters
    """ # noqa: E501
    case_analysis: List[Aggregation]
    classification: List[Aggregation]
    diagnosis_lab: List[Aggregation]
    __properties: ClassVar[List[str]] = ["case_analysis", "classification", "diagnosis_lab"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariantCasesFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in case_analysis (list)
        _items = []
        if self.case_analysis:
            for _item_case_analysis in self.case_analysis:
                if _item_case_analysis:
                    _items.append(_item_case_analysis.to_dict())
            _dict['case_analysis'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in classification (list)
        _items = []
        if self.classification:
            for _item_classification in self.classification:
                if _item_classification:
                    _items.append(_item_classification.to_dict())
            _dict['classification'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in diagnosis_lab (list)
        _items = []
        if self.diagnosis_lab:
            for _item_diagnosis_lab in self.diagnosis_lab:
                if _item_diagnosis_lab:
                    _items.append(_item_diagnosis_lab.to_dict())
            _dict['diagnosis_lab'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariantCasesFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "case_analysis": [Aggregation.from_dict(_item) for _item in obj["case_analysis"]] if obj.get("case_analysis") is not None else None,
            "classification": [Aggregation.from_dict(_item) for _item in obj["classification"]] if obj.get("classification") is not None else None,
            "diagnosis_lab": [Aggregation.from_dict(_item) for _item in obj["diagnosis_lab"]] if obj.get("diagnosis_lab") is not None else None
        })
        return _obj


