# coding: utf-8

"""
    Radiant API

    This is the API for Radiant data platform.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from radiant_python.models.term import Term
from typing import Optional, Set
from typing_extensions import Self

class VariantUninterpretedCase(BaseModel):
    """
    VariantUninterpretedCase
    """ # noqa: E501
    affected_status: Optional[StrictStr] = None
    analysis_catalog_code: Optional[StrictStr] = None
    analysis_catalog_name: Optional[StrictStr] = None
    case_id: StrictInt
    created_on: StrictStr
    diagnosis_lab_code: Optional[StrictStr] = None
    diagnosis_lab_name: Optional[StrictStr] = None
    exomiser_acmg_classification: Optional[StrictStr] = None
    exomiser_acmg_evidence: Optional[List[StrictStr]] = None
    filter_is_pass: Optional[StrictBool] = None
    observed_phenotypes: Optional[List[Term]] = None
    patient_id: StrictInt
    primary_condition_id: Optional[StrictStr] = None
    primary_condition_name: Optional[StrictStr] = None
    relationship_to_proband: Optional[StrictStr] = None
    seq_id: StrictInt
    status_code: StrictStr
    submitter_sample_id: Optional[StrictStr] = None
    updated_on: StrictStr
    zygosity: StrictStr
    __properties: ClassVar[List[str]] = ["affected_status", "analysis_catalog_code", "analysis_catalog_name", "case_id", "created_on", "diagnosis_lab_code", "diagnosis_lab_name", "exomiser_acmg_classification", "exomiser_acmg_evidence", "filter_is_pass", "observed_phenotypes", "patient_id", "primary_condition_id", "primary_condition_name", "relationship_to_proband", "seq_id", "status_code", "submitter_sample_id", "updated_on", "zygosity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariantUninterpretedCase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in observed_phenotypes (list)
        _items = []
        if self.observed_phenotypes:
            for _item_observed_phenotypes in self.observed_phenotypes:
                if _item_observed_phenotypes:
                    _items.append(_item_observed_phenotypes.to_dict())
            _dict['observed_phenotypes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariantUninterpretedCase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "affected_status": obj.get("affected_status"),
            "analysis_catalog_code": obj.get("analysis_catalog_code"),
            "analysis_catalog_name": obj.get("analysis_catalog_name"),
            "case_id": obj.get("case_id"),
            "created_on": obj.get("created_on"),
            "diagnosis_lab_code": obj.get("diagnosis_lab_code"),
            "diagnosis_lab_name": obj.get("diagnosis_lab_name"),
            "exomiser_acmg_classification": obj.get("exomiser_acmg_classification"),
            "exomiser_acmg_evidence": obj.get("exomiser_acmg_evidence"),
            "filter_is_pass": obj.get("filter_is_pass"),
            "observed_phenotypes": [Term.from_dict(_item) for _item in obj["observed_phenotypes"]] if obj.get("observed_phenotypes") is not None else None,
            "patient_id": obj.get("patient_id"),
            "primary_condition_id": obj.get("primary_condition_id"),
            "primary_condition_name": obj.get("primary_condition_name"),
            "relationship_to_proband": obj.get("relationship_to_proband"),
            "seq_id": obj.get("seq_id"),
            "status_code": obj.get("status_code"),
            "submitter_sample_id": obj.get("submitter_sample_id"),
            "updated_on": obj.get("updated_on"),
            "zygosity": obj.get("zygosity")
        })
        return _obj


