import {
  type FiltersValue,
  type PatientEntity,
  PatientEntityGenderEnum,
  PatientEntityPatientIdTypeEnum,
  PatientEntityVitalStatusEnum,
  PatientEventEventTypeEnum,
  PatientKeyDateSourceEnum,
} from '@/api/api';

// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientSite = 'UCSF' | 'CHOP' | 'Seattle';
// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientSex = 'Female' | 'Male';
// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientVitalStatus = 'alive' | 'deceased';

// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type Patient = {
  patient_id: string;
  name: string;
  mrn: string;
  site: PatientSite;
  organization: string;
  birth_year: number;
  sex: PatientSex;
  cns_integrated_diagnosis: string;
  vital_status: PatientVitalStatus;
  vital_status_day: number | null;
  survival_days: number | null;
};

// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientsSearchResponse = {
  list: Patient[];
  count: number;
};

// Placeholder roster lifted from the v6.2 wireframe (deidentified ATRT cohort
// across CHOP, UCSF, Seattle Children's). Replace with a call to the generated
// patient API client once the backend endpoint lands — response shape here
// mirrors the intended OpenAPI contract.
const PATIENTS_MOCK: Patient[] = [
  {
    patient_id: 'C1010445',
    name: 'Ava Okafor',
    mrn: 'MRN-UCSF-10000',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 756,
    survival_days: 199,
  },
  {
    patient_id: 'C1032093',
    name: 'Kai Ellery',
    mrn: 'MRN-CHOP-10274',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1343,
    survival_days: 524,
  },
  {
    patient_id: 'C1036644',
    name: 'Nora Ibarra',
    mrn: 'MRN-CHOP-10411',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 965,
    survival_days: 254,
  },
  {
    patient_id: 'C104427',
    name: 'Iris Wren',
    mrn: 'MRN-SCH-10548',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2012,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1519,
    survival_days: 1125,
  },
  {
    patient_id: 'C1056939',
    name: 'Jonah Farrow',
    mrn: 'MRN-SCH-10685',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2009,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 4407,
    survival_days: 3766,
  },
  {
    patient_id: 'C1070346',
    name: 'Ruby Mireles',
    mrn: 'MRN-SCH-10822',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1862,
    survival_days: 1199,
  },
  {
    patient_id: 'C1154847',
    name: 'Elena Ueda',
    mrn: 'MRN-SCH-10959',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1663,
    survival_days: 1146,
  },
  {
    patient_id: 'C1248204',
    name: 'Arlo Bello',
    mrn: 'MRN-CHOP-11096',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2012,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 3960,
    survival_days: 1884,
  },
  {
    patient_id: 'C1277601',
    name: 'Clara Ismail',
    mrn: 'MRN-CHOP-11233',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1992,
    survival_days: 1308,
  },
  {
    patient_id: 'C140712',
    name: 'Naomi Castellano',
    mrn: 'MRN-CHOP-11370',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2010,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 2086,
    survival_days: 580,
  },
  {
    patient_id: 'C148215',
    name: 'Talia Sato',
    mrn: 'MRN-SCH-11507',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2007,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 6122,
    survival_days: 5920,
  },
  {
    patient_id: 'C18819',
    name: 'Emil Quintero',
    mrn: 'MRN-CHOP-11644',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2008,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1000,
    survival_days: 117,
  },
  {
    patient_id: 'C196554',
    name: 'Nico Petrov',
    mrn: 'MRN-CHOP-11781',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2013,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 840,
    survival_days: 495,
  },
  {
    patient_id: 'C20049',
    name: 'Rafi Baptiste',
    mrn: 'MRN-CHOP-11918',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2003,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 3165,
    survival_days: 2569,
  },
  {
    patient_id: 'C21894',
    name: 'Levi Iversen',
    mrn: 'MRN-CHOP-12055',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2005,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 6344,
    survival_days: 4608,
  },
  {
    patient_id: 'C226074',
    name: 'Amos Pashkov',
    mrn: 'MRN-SCH-12192',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2012,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2393,
    survival_days: 2246,
  },
  {
    patient_id: 'C227058',
    name: 'Esme Xu',
    mrn: 'MRN-CHOP-12329',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2013,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1203,
    survival_days: 697,
  },
  {
    patient_id: 'C2322117',
    name: 'Cyrus Escobar',
    mrn: 'MRN-CHOP-12466',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2018,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2565,
    survival_days: 2437,
  },
  {
    patient_id: 'C2333310',
    name: 'Elian Lund',
    mrn: 'MRN-SCH-12603',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2016,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 806,
    survival_days: 316,
  },
  {
    patient_id: 'C2442411',
    name: 'Nadia Fenwick',
    mrn: 'MRN-CHOP-12740',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1703,
    survival_days: 499,
  },
  {
    patient_id: 'C2457171',
    name: 'Rosa Marchetti',
    mrn: 'MRN-UCSF-12877',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 1989,
    sex: 'Female',
    cns_integrated_diagnosis: 'Not Reported',
    vital_status: 'deceased',
    vital_status_day: null,
    survival_days: null,
  },
  {
    patient_id: 'C2461968',
    name: 'Jasper Thorne',
    mrn: 'MRN-UCSF-13014',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 2006,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 484,
    survival_days: 159,
  },
  {
    patient_id: 'C2536998',
    name: 'Sena Vasquez',
    mrn: 'MRN-CHOP-13151',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2014,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 3480,
    survival_days: 2338,
  },
  {
    patient_id: 'C2554956',
    name: 'Lars Eriksen',
    mrn: 'MRN-CHOP-13288',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 1997,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 5553,
    survival_days: 4112,
  },
  {
    patient_id: 'C2571192',
    name: 'Odette Lomax',
    mrn: 'MRN-SCH-13425',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1248,
    survival_days: 446,
  },
  {
    patient_id: 'C2698005',
    name: 'Wren Tavares',
    mrn: 'MRN-CHOP-13562',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2018,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2616,
    survival_days: 2268,
  },
  {
    patient_id: 'C2714610',
    name: 'Ines Amara',
    mrn: 'MRN-SCH-13699',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2010,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 836,
    survival_days: 0,
  },
  {
    patient_id: 'C2848188',
    name: 'Marta Hurtado',
    mrn: 'MRN-CHOP-13836',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2019,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 284,
    survival_days: 65,
  },
  {
    patient_id: 'C3422106',
    name: 'Quinn Moreau',
    mrn: 'MRN-CHOP-13973',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2020,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 861,
    survival_days: 836,
  },
  {
    patient_id: 'C3559497',
    name: 'Rowan Brennan',
    mrn: 'MRN-CHOP-14110',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2017,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2940,
    survival_days: 1417,
  },
  {
    patient_id: 'C374412',
    name: 'Bianca Novak',
    mrn: 'MRN-CHOP-14247',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2014,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 713,
    survival_days: 523,
  },
  {
    patient_id: 'C3816813',
    name: 'Tobias Mensah',
    mrn: 'MRN-CHOP-14384',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2020,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2020,
    survival_days: 1383,
  },
  {
    patient_id: 'C396306',
    name: 'Yusuf Zimmer',
    mrn: 'MRN-CHOP-14521',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2013,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2426,
    survival_days: 1864,
  },
  {
    patient_id: 'C4031571',
    name: 'Zane Haddad',
    mrn: 'MRN-SCH-14658',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2018,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 2015,
    survival_days: 828,
  },
  {
    patient_id: 'C4034646',
    name: 'Ava Oyelaran',
    mrn: 'MRN-SCH-14795',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1785,
    survival_days: 0,
  },
  {
    patient_id: 'C406761',
    name: 'Theo Whitfield',
    mrn: 'MRN-CHOP-14932',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2012,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1471,
    survival_days: 433,
  },
  {
    patient_id: 'C4174251',
    name: 'Zoe Dinh',
    mrn: 'MRN-CHOP-15069',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2010,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 4590,
    survival_days: 244,
  },
  {
    patient_id: 'C4261089',
    name: 'Nora Keita',
    mrn: 'MRN-CHOP-15206',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2010,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT-MYC',
    vital_status: 'alive',
    vital_status_day: 4396,
    survival_days: 245,
  },
  {
    patient_id: 'C4483473',
    name: 'Otis Abadi',
    mrn: 'MRN-CHOP-15343',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2020,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1200,
    survival_days: 183,
  },
  {
    patient_id: 'C466293',
    name: 'Jonah Vance',
    mrn: 'MRN-CHOP-15480',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2014,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 2460,
    survival_days: 2077,
  },
  {
    patient_id: 'C4964157',
    name: 'Ravi Rivas',
    mrn: 'MRN-CHOP-15617',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2019,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1967,
    survival_days: 727,
  },
  {
    patient_id: 'C5254437',
    name: 'Elena Underwood',
    mrn: 'MRN-SCH-15754',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2019,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT-MYC',
    vital_status: 'deceased',
    vital_status_day: 2176,
    survival_days: 695,
  },
  {
    patient_id: 'C5489736',
    name: 'Sofia Duval',
    mrn: 'MRN-CHOP-15891',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2023,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT-SHH',
    vital_status: 'deceased',
    vital_status_day: 513,
    survival_days: 434,
  },
  {
    patient_id: 'C558912',
    name: 'Clara Kaur',
    mrn: 'MRN-SCH-16028',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2012,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1255,
    survival_days: 229,
  },
  {
    patient_id: 'C59655',
    name: 'Naomi Solano',
    mrn: 'MRN-CHOP-16165',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2004,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 6824,
    survival_days: 3842,
  },
  {
    patient_id: 'C603069',
    name: 'Silas Zavala',
    mrn: 'MRN-SCH-16302',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2015,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 626,
    survival_days: 408,
  },
  {
    patient_id: 'C607743',
    name: 'Emil Gallo',
    mrn: 'MRN-CHOP-16439',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2013,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 2050,
    survival_days: 1312,
  },
  {
    patient_id: 'C626070',
    name: 'Freya Lindqvist',
    mrn: 'MRN-CHOP-16576',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 639,
    survival_days: 348,
  },
  {
    patient_id: 'C626193',
    name: 'Willa Hollis',
    mrn: 'MRN-CHOP-16713',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 532,
    survival_days: 362,
  },
  {
    patient_id: 'C6538311',
    name: 'Levi Bhatt',
    mrn: 'MRN-CHOP-16850',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2018,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT-SHH',
    vital_status: 'deceased',
    vital_status_day: 2849,
    survival_days: 2575,
  },
  {
    patient_id: 'C663708',
    name: 'Mira Kowalski',
    mrn: 'MRN-CHOP-16987',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2000,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 6394,
    survival_days: 706,
  },
  {
    patient_id: 'C6958725',
    name: 'Bruno Yates',
    mrn: 'MRN-SCH-17124',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2021,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 1469,
    survival_days: 572,
  },
  {
    patient_id: 'C698640',
    name: 'Cyrus Guzman',
    mrn: 'MRN-CHOP-17261',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2015,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 424,
    survival_days: 74,
  },
  {
    patient_id: 'C7611978',
    name: 'Lila Nasser',
    mrn: 'MRN-SCH-17398',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2021,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT-MYC',
    vital_status: 'alive',
    vital_status_day: 1677,
    survival_days: 230,
  },
  {
    patient_id: 'C7617267',
    name: 'Hugo Volkov',
    mrn: 'MRN-SCH-17535',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2019,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT-SHH',
    vital_status: 'alive',
    vital_status_day: 2204,
    survival_days: 1022,
  },
  {
    patient_id: 'C7768188',
    name: 'Ivan Cortez',
    mrn: 'MRN-UCSF-17672',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 2022,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1071,
    survival_days: 222,
  },
  {
    patient_id: 'C782649',
    name: 'Hana Jansen',
    mrn: 'MRN-SCH-17809',
    site: 'Seattle',
    organization: "Seattle Children's Hospital",
    birth_year: 2005,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 6931,
    survival_days: 2924,
  },
  {
    patient_id: 'C82164',
    name: 'Perla Okonkwo',
    mrn: 'MRN-CHOP-18083',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2008,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 4942,
    survival_days: 3019,
  },
  {
    patient_id: 'C85854',
    name: 'Omar Chandra',
    mrn: 'MRN-CHOP-18494',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2011,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1098,
    survival_days: 272,
  },
  {
    patient_id: 'C876375',
    name: 'Marta Jelani',
    mrn: 'MRN-CHOP-18631',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 266,
    survival_days: 261,
  },
  {
    patient_id: 'C880803',
    name: 'Yara Radich',
    mrn: 'MRN-CHOP-18768',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 531,
    survival_days: 188,
  },
  {
    patient_id: 'C886092',
    name: 'Delia Yoruba',
    mrn: 'MRN-UCSF-18905',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 2016,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1943,
    survival_days: 1581,
  },
  {
    patient_id: 'C921639',
    name: 'Bianca Fontaine',
    mrn: 'MRN-UCSF-19042',
    site: 'UCSF',
    organization: "UCSF Benioff Children's Hospital",
    birth_year: 2012,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 1990,
    survival_days: 639,
  },
  {
    patient_id: 'C964566',
    name: 'Tobias Okafor',
    mrn: 'MRN-CHOP-19179',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2009,
    sex: 'Male',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'alive',
    vital_status_day: 3983,
    survival_days: 1142,
  },
  {
    patient_id: 'C974652',
    name: 'Selma Delgado',
    mrn: 'MRN-CHOP-19316',
    site: 'CHOP',
    organization: "The Children's Hospital of Philadelphia",
    birth_year: 2008,
    sex: 'Female',
    cns_integrated_diagnosis: 'ATRT, NOS or NEC',
    vital_status: 'deceased',
    vital_status_day: 3562,
    survival_days: 1998,
  },
];

const MOCK_LATENCY_MS = 300;

export async function fetchPatientsList(): Promise<PatientsSearchResponse> {
  await new Promise(resolve => setTimeout(resolve, MOCK_LATENCY_MS));
  return {
    list: PATIENTS_MOCK,
    count: PATIENTS_MOCK.length,
  };
}

// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientFilters = {
  vital_status: FiltersValue[];
  organization_name: FiltersValue[];
  cns_integrated_diagnosis: FiltersValue[];
  age_at_initial_dx_days: FiltersValue[];
  had_initial_methotrexate: FiltersValue[];
  diagnosis_type_cohort: FiltersValue[];
};

// TODO: remove once the backend implements the patient filters endpoint
const PATIENT_FILTERS_MOCK: PatientFilters = {
  vital_status: [
    { key: 'alive', label: 'Alive' },
    { key: 'deceased', label: 'Deceased' },
  ],
  organization_name: [
    { key: 'CHOP', label: 'CHOP' },
    { key: 'Seattle', label: "Seattle Children's" },
    { key: 'UCSF', label: 'UCSF' },
  ],
  cns_integrated_diagnosis: [
    { key: 'ATRT-SHH', label: 'ATRT-SHH' },
    { key: 'ATRT-MYC', label: 'ATRT-MYC' },
    { key: 'ATRT, NOS or NEC', label: 'ATRT, NOS or NEC' },
    { key: 'Not Reported', label: 'Not Reported' },
  ],
  age_at_initial_dx_days: [
    { key: 'lt_36_months', label: '< 36 months' },
    { key: 'gte_36_months', label: '≥ 36 months' },
  ],
  had_initial_methotrexate: [
    { key: 'with_methotrexate', label: '+ Methotrexate' },
    { key: 'without_methotrexate', label: '− Methotrexate' },
  ],
  diagnosis_type_cohort: [
    { key: 'atrt', label: 'ATRT' },
    { key: 'medulloblastoma', label: 'Medulloblastoma' },
  ],
};

// TODO: replace with a call to the generated patient API client; fall back to the mock only on 404
export async function fetchPatientFilters(): Promise<PatientFilters> {
  await new Promise(resolve => setTimeout(resolve, MOCK_LATENCY_MS));
  return PATIENT_FILTERS_MOCK;
}

// TODO: replace with generated type from frontend/api/ once backend endpoint exists
export type PatientExternalRecords = {
  organization: string;
  linked: boolean;
  connected: boolean;
};

// Same placeholder for every patient, lifted from the v6.2 wireframe (Kai Ellery).
// TODO: replace once the backend provides external records
export const PATIENT_EXTERNAL_RECORDS_MOCK: PatientExternalRecords = {
  organization: "The Children's Hospital of Philadelphia",
  linked: true,
  connected: true,
};

// TODO: replace with generated type from frontend/api/ once backend endpoint exists.
// Not in the SJRA-1998 PatientEntity contract — lower priority for November (Build readiness)
// and cancer-specific per the Generalising section of the Patient View analysis.
// Wireframe enum: Rhabdoid tumour (SMARCB1) · Li-Fraumeni (TP53) · NF1 / NF2 · MMR · CMMRD · Lynch syndrome.
export type PatientCancerPredispositions = {
  cancer_predisposition?: string[];
};

// Placeholder lifted from the v6.2 wireframe (Kai Ellery, ATRT-SHH).
const PATIENT_CANCER_PREDISPOSITIONS_MOCK: PatientCancerPredispositions = {
  cancer_predisposition: ['SMARCB1 rhabdoid'],
};

// TODO: replace with a call to the generated patient API client once the backend endpoint lands
export async function fetchPatientCancerPredispositions(_patientId: string): Promise<PatientCancerPredispositions> {
  await new Promise(resolve => setTimeout(resolve, MOCK_LATENCY_MS));
  return PATIENT_CANCER_PREDISPOSITIONS_MOCK;
}

const NOT_APPLICABLE_DOSE = { value: 'Not Applicable', unit: 'Not Applicable' };

// Same placeholder for every patient, lifted from the v6.2 wireframe (Kai Ellery).
// Treatments include the duplicate craniospinal rows flagged in the analysis.
// TODO: remove once the backend implements the patient entity endpoint
export const PATIENT_ENTITY_MOCK: PatientEntity = {
  patient_key: 'C1032093',
  patient_id: 'C1032093',
  patient_id_type: PatientEntityPatientIdTypeEnum.ResearchId,
  given_name: 'Kai',
  family_name: 'Ellery',
  gender: PatientEntityGenderEnum.Male,
  birth_year: 2015,
  race: 'White',
  ethnicity: 'Not Hispanic or Latino',
  postal_code: '19104',
  cns_integrated_diagnosis: 'ATRT-SHH',
  organization_code: 'CHOP',
  organization_name: "The Children's Hospital of Philadelphia",
  vital_status: PatientEntityVitalStatusEnum.Deceased,
  vital_status_at: { day: 1343 },
  age_at_vital_status_days: 1343,
  age_at_initial_dx_days: 819,
  survival_days: 524,
  can_read_phi: false,
  has_imaging: false,
  case_count: 0,
  cases: [],
  events: [
    {
      event_type: PatientEventEventTypeEnum.InitialCnsTumor,
      day: 819,
      cns_diagnosis_category: 'Embryonal tumor',
      cns_integrated_diagnosis: 'ATRT-SHH',
      tumor_locations: ['Cerebellum'],
      metastasis_locations: [],
    },
    {
      event_type: PatientEventEventTypeEnum.Progressive,
      day: 1026,
      tumor_locations: ['Cerebellum'],
      metastasis: 'Yes',
      metastasis_locations: ['Leptomeningeal'],
    },
  ],
  imaging: [],
  key_dates: {
    initial_diagnosis: { day: 819, source: PatientKeyDateSourceEnum.Clinical },
    latest_encounter: { day: 1343, source: PatientKeyDateSourceEnum.Registry },
  },
  surgeries: [
    { day: 1564, extent_of_tumor_resection: 'Gross/Near total resection' },
    { day: 3289, extent_of_tumor_resection: 'Gross/Near total resection' },
  ],
  radiations: [
    {
      start: { day: 1026 },
      stop: { day: 1070 },
      site: 'Craniospinal with focal boost',
      type: 'Protons',
      craniospinal_dose: { value: '3600', unit: 'CGE' },
      focal_boost_dose: { value: '1800', unit: 'CGE' },
      total_primary_dose: { value: '5400', unit: 'CGE' },
    },
    {
      start: { day: 1026 },
      stop: { day: 1070 },
      site: 'Craniospinal with focal boost',
      type: 'Protons',
      craniospinal_dose: { value: '36', unit: 'CGE' },
      focal_boost_dose: { value: '18', unit: 'CGE' },
      total_primary_dose: { value: '54', unit: 'CGE' },
    },
    {
      start: { day: 1743 },
      stop: { day: 1785 },
      site: 'Focal/Tumor bed',
      type: 'Protons',
      craniospinal_dose: NOT_APPLICABLE_DOSE,
      total_primary_dose: { value: '5400', unit: 'cGy' },
    },
    {
      start: { day: 2344 },
      stop: {},
      site: 'Focal/Tumor bed',
      type: 'Photons',
      craniospinal_dose: NOT_APPLICABLE_DOSE,
      total_primary_dose: { value: '3000 ', unit: 'cGy' },
    },
    {
      start: { day: 2780 },
      stop: {},
      site: 'Focal/Tumor bed',
      type: 'Photons',
      craniospinal_dose: { value: 'Not Reported', unit: 'Not Reported' },
      total_primary_dose: { value: '35', unit: 'Gy' },
    },
  ],
  therapies: [
    {
      start: { day: 1606 },
      stop: {},
      chemotherapy_agents: [
        'cisplatin',
        'cyclophosphamide',
        'cytarabine',
        'dactinomycin',
        'doxorubicin',
        'etoposide',
        'methotrexate',
        'temozolomide',
        'vincristine',
      ],
    },
    { start: {}, stop: {}, chemotherapy_agents: ['temozolomide'] },
    { start: {}, stop: {}, chemotherapy_agents: ['etoposide'] },
  ],
};
