/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  theme: {
    extend: {
      borderColor: ({ theme }) => ({
        ...theme('colors'),
        DEFAULT: theme('colors.border'),
      }),
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          50: 'hsl(var(--primary-1))',
          100: 'hsl(var(--primary-2))',
          200: 'hsl(var(--primary-3))',
          300: 'hsl(var(--primary-4))',
          400: 'hsl(var(--primary-5))',
          500: 'hsl(var(--primary-6))',
          600: 'hsl(var(--primary-7))',
          700: 'hsl(var(--primary-8))',
          800: 'hsl(var(--primary-9))',
          900: 'hsl(var(--primary-10))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        blue: {
          50: 'hsl(var(--blue-1))',
          100: 'hsl(var(--blue-2))',
          200: 'hsl(var(--blue-3))',
          300: 'hsl(var(--blue-4))',
          400: 'hsl(var(--blue-5))',
          500: 'hsl(var(--blue-6))',
          600: 'hsl(var(--blue-7))',
          700: 'hsl(var(--blue-8))',
          800: 'hsl(var(--blue-9))',
          900: 'hsl(var(--blue-10))',
        },
        gray: {
          50: 'hsl(var(--gray-1))',
          100: 'hsl(var(--gray-2))',
          200: 'hsl(var(--gray-3))',
          300: 'hsl(var(--gray-4))',
          400: 'hsl(var(--gray-5))',
          500: 'hsl(var(--gray-6))',
          600: 'hsl(var(--gray-7))',
          700: 'hsl(var(--gray-8))',
          800: 'hsl(var(--gray-9))',
          900: 'hsl(var(--gray-10))',
        },
        red: {
          50: 'hsl(var(--red-1))',
          100: 'hsl(var(--red-2))',
          200: 'hsl(var(--red-3))',
          300: 'hsl(var(--red-4))',
          400: 'hsl(var(--red-5))',
          500: 'hsl(var(--red-6))',
          600: 'hsl(var(--red-7))',
          700: 'hsl(var(--red-8))',
          800: 'hsl(var(--red-9))',
          900: 'hsl(var(--red-10))',
        },
        volcano: {
          50: 'hsl(var(--volcano-1))',
          100: 'hsl(var(--volcano-2))',
          200: 'hsl(var(--volcano-3))',
          300: 'hsl(var(--volcano-4))',
          400: 'hsl(var(--volcano-5))',
          500: 'hsl(var(--volcano-6))',
          600: 'hsl(var(--volcano-7))',
          700: 'hsl(var(--volcano-8))',
          800: 'hsl(var(--volcano-9))',
          900: 'hsl(var(--volcano-10))',
        },
        orange: {
          50: 'hsl(var(--orange-1))',
          100: 'hsl(var(--orange-2))',
          200: 'hsl(var(--orange-3))',
          300: 'hsl(var(--orange-4))',
          400: 'hsl(var(--orange-5))',
          500: 'hsl(var(--orange-6))',
          600: 'hsl(var(--orange-7))',
          700: 'hsl(var(--orange-8))',
          800: 'hsl(var(--orange-9))',
          900: 'hsl(var(--orange-10))',
        },
        gold: {
          50: 'hsl(var(--gold-1))',
          100: 'hsl(var(--gold-2))',
          200: 'hsl(var(--gold-3))',
          300: 'hsl(var(--gold-4))',
          400: 'hsl(var(--gold-5))',
          500: 'hsl(var(--gold-6))',
          600: 'hsl(var(--gold-7))',
          700: 'hsl(var(--gold-8))',
          800: 'hsl(var(--gold-9))',
          900: 'hsl(var(--gold-10))',
        },
        yellow: {
          50: 'hsl(var(--yellow-1))',
          100: 'hsl(var(--yellow-2))',
          200: 'hsl(var(--yellow-3))',
          300: 'hsl(var(--yellow-4))',
          400: 'hsl(var(--yellow-5))',
          500: 'hsl(var(--yellow-6))',
          600: 'hsl(var(--yellow-7))',
          700: 'hsl(var(--yellow-8))',
          800: 'hsl(var(--yellow-9))',
          900: 'hsl(var(--yellow-10))',
        },
        lime: {
          50: 'hsl(var(--lime-1))',
          100: 'hsl(var(--lime-2))',
          200: 'hsl(var(--lime-3))',
          300: 'hsl(var(--lime-4))',
          400: 'hsl(var(--lime-5))',
          500: 'hsl(var(--lime-6))',
          600: 'hsl(var(--lime-7))',
          700: 'hsl(var(--lime-8))',
          800: 'hsl(var(--lime-9))',
          900: 'hsl(var(--lime-10))',
        },
        green: {
          50: 'hsl(var(--green-1))',
          100: 'hsl(var(--green-2))',
          200: 'hsl(var(--green-3))',
          300: 'hsl(var(--green-4))',
          400: 'hsl(var(--green-5))',
          500: 'hsl(var(--green-6))',
          600: 'hsl(var(--green-7))',
          700: 'hsl(var(--green-8))',
          800: 'hsl(var(--green-9))',
          900: 'hsl(var(--green-10))',
        },
        cyan: {
          50: 'hsl(var(--cyan-1))',
          100: 'hsl(var(--cyan-2))',
          200: 'hsl(var(--cyan-3))',
          300: 'hsl(var(--cyan-4))',
          400: 'hsl(var(--cyan-5))',
          500: 'hsl(var(--cyan-6))',
          600: 'hsl(var(--cyan-7))',
          700: 'hsl(var(--cyan-8))',
          800: 'hsl(var(--cyan-9))',
          900: 'hsl(var(--cyan-10))',
        },
        geekblue: {
          50: 'hsl(var(--geekblue-1))',
          100: 'hsl(var(--geekblue-2))',
          200: 'hsl(var(--geekblue-3))',
          300: 'hsl(var(--geekblue-4))',
          400: 'hsl(var(--geekblue-5))',
          500: 'hsl(var(--geekblue-6))',
          600: 'hsl(var(--geekblue-7))',
          700: 'hsl(var(--geekblue-8))',
          800: 'hsl(var(--geekblue-9))',
          900: 'hsl(var(--geekblue-10))',
        },
        purple: {
          50: 'hsl(var(--purple-1))',
          100: 'hsl(var(--purple-2))',
          200: 'hsl(var(--purple-3))',
          300: 'hsl(var(--purple-4))',
          400: 'hsl(var(--purple-5))',
          500: 'hsl(var(--purple-6))',
          600: 'hsl(var(--purple-7))',
          700: 'hsl(var(--purple-8))',
          800: 'hsl(var(--purple-9))',
          900: 'hsl(var(--purple-10))',
        },
        magenta: {
          50: 'hsl(var(--magenta-1))',
          100: 'hsl(var(--magenta-2))',
          200: 'hsl(var(--magenta-3))',
          300: 'hsl(var(--magenta-4))',
          400: 'hsl(var(--magenta-5))',
          500: 'hsl(var(--magenta-6))',
          600: 'hsl(var(--magenta-7))',
          700: 'hsl(var(--magenta-8))',
          800: 'hsl(var(--magenta-9))',
          900: 'hsl(var(--magenta-10))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
