ALTER TABLE "observation" DROP COLUMN "category";

DROP TABLE IF EXISTS "observation_category";

INSERT INTO observation (code, name_en)
VALUES ('note', 'Clinical Note'),
       ('ancestry', 'Ancestry'),
       ('consanguinity', 'Consanguinity')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE observation_coding RENAME TO obs_categorical;

ALTER TABLE obs_categorical ALTER COLUMN onset_code DROP NOT NULL;

UPDATE obs_categorical SET observation_code = 'ancestry' WHERE observation_code = 'ethnicity';

DELETE FROM observation WHERE code = 'ethnicity';

CREATE TABLE IF NOT EXISTS "obs_string"
(
    "id"                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"              INTEGER                                    NOT NULL REFERENCES "cases" ("id"),
    "patient_id"           INTEGER                                    NOT NULL REFERENCES "patient" ("id"),
    "observation_code"     TEXT REFERENCES "observation" ("code")   NOT NULL,
    "value"                TEXT                                    NOT NULL
);

CREATE TABLE IF NOT EXISTS "family_history"
(
    "id"                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"              INTEGER                                    NOT NULL REFERENCES "cases" ("id"),
    "patient_id"           INTEGER                                    NOT NULL REFERENCES "patient" ("id"),
    "family_member_code"   TEXT NOT NULL,
    "condition"            TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "consanguinity"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

INSERT INTO consanguinity (code, name_en)
VALUES ('unknown', 'Unknown'),
       ('consanguinity', 'Consanguinity in family'),
       ('no_consanguinity', 'No consanguinity in family')
ON CONFLICT (code) DO NOTHING;