-- CREATE panel tables
CREATE TABLE IF NOT EXISTS "panel_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

INSERT INTO "panel_type" ("code", "name_en")
VALUES ('virtual', 'Virtual'),
       ('physical', 'Physical')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS "panel"
(
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"      TEXT NOT NULL UNIQUE,
    "name"      TEXT NOT NULL,
    "type_code" TEXT NOT NULL REFERENCES "panel_type" ("code")
);

CREATE TABLE "panel_has_genes"
(
    "panel_id"   INTEGER NOT NULL REFERENCES "panel" ("id"),
    "ensembl_id" TEXT    NOT NULL,
    "symbol"     TEXT    NOT NULL,
    PRIMARY KEY ("panel_id", "ensembl_id")
);

-- Do sequencing_experiment changes
CREATE TABLE "experiment"
(
    "id"                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"                       TEXT NOT NULL UNIQUE,
    "name"                       TEXT NOT NULL,
    "experimental_strategy_code" TEXT NOT NULL REFERENCES "experimental_strategy" ("code"),
    "platform_code"              TEXT NOT NULL REFERENCES "platform" ("code"),
    "description"                TEXT
);

INSERT INTO "experiment" (id, code, name, experimental_strategy_code, platform_code, description)
VALUES (1, 'WXS', 'Whole Exome Sequencing', 'wxs', 'illumina', 'A description'),
       (2, 'WGS_SR', 'Short Read Whole Genome Sequencing', 'wgs', 'illumina', 'A description'),
       (3, 'WTS', 'Whole Transcriptome Sequencing', 'wts', 'illumina', 'A description'),
       (4, 'WGS_LR', 'Long Read Whole Genome Sequencing', 'wgs', 'pacbio', 'A description')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "sequencing_experiment"
    ADD COLUMN "experiment_id" INTEGER REFERENCES "experiment" ("id");
UPDATE "sequencing_experiment"
SET experiment_id = (SELECT id FROM experiment WHERE experiment.code = sequencing_experiment.experimental_strategy_code)
WHERE experimental_strategy_code IS NOT NULL;
ALTER TABLE "sequencing_experiment"
    ALTER COLUMN "experiment_id" SET NOT NULL;

ALTER TABLE sequencing_experiment
    DROP COLUMN "experimental_strategy_code";
ALTER TABLE sequencing_experiment
    DROP COLUMN "platform_code";

-- Do case changes
CREATE TABLE IF NOT EXISTS "case_analysis_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

INSERT INTO "case_analysis_type" ("code", "name_en")
VALUES ('germline', 'Germline'),
       ('somatic', 'Somatic')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS "case_analysis"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"        TEXT NOT NULL UNIQUE,
    "name"        TEXT NOT NULL,
    "type_code"   TEXT NOT NULL REFERENCES "case_analysis_type" ("code"),
    "panel_id"    INTEGER REFERENCES "panel" ("id"),
    "description" TEXT
);

INSERT INTO "case_analysis" (id, code, name, type_code, panel_id, description)
VALUES (1, 'WGA', 'Whole Genome Analysis', 'germline', NULL, 'A description of this analysis'),
       (2, 'IDGD', 'Intellectual Deficiency and Global Developmental Delay', 'germline', NULL,
        'A description of this analysis'),
       (3, 'MYOC', 'Congenital Myopathies', 'germline', NULL, 'A description of this analysis'),
       (4, 'HYPM', 'Malignant Hyperthermia', 'germline', NULL, 'A description of this analysis')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "case"
    ADD COLUMN "case_analysis_id" INTEGER REFERENCES "case_analysis" ("id");

UPDATE "case"
SET case_analysis_id = 2
WHERE type_code IS NOT NULL;
ALTER TABLE "case"
    ALTER COLUMN "case_analysis_id" SET NOT NULL;

ALTER TABLE "case"
    DROP COLUMN "type_code";
ALTER TABLE "case"
    DROP COLUMN "panel_id";

DROP TABLE case_type;

-- Do request changes
ALTER TABLE "request"
    DROP COLUMN "status_code";
ALTER TABLE "request"
    DROP COLUMN "request_code";
ALTER TABLE "request"
    DROP COLUMN "created_on";
ALTER TABLE "request"
    DROP COLUMN "updated_on";

-- Do sample changes
ALTER TABLE "sample"
    RENAME COLUMN "submitter_id" TO "submitter_sample_id";