CREATE TABLE public.fetus (
    id integer NOT NULL,
    mother_id integer NOT NULL REFERENCES public.patient(id),
    life_status_code text NOT NULL REFERENCES public.life_status(code),
    sex_code text NOT NULL REFERENCES public.sex(code),
    last_menstrual_period date,
    estimated_due_date date,
    tenant_code text NOT NULL REFERENCES public.tenant(code)
);

ALTER TABLE public.fetus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fetus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.fetus
    ADD CONSTRAINT fetus_pkey PRIMARY KEY (id);

CREATE INDEX ix_fetus_tenant_code ON public.fetus (tenant_code);
CREATE INDEX ix_fetus_mother_id ON public.fetus (mother_id);

INSERT INTO public.family_relationship (code, name_en) VALUES
    ('fetus', 'Fetus');

-- obs_categorical / obs_string / family: a clinical row now belongs to exactly one subject,
-- the mother (patient_id / family_member_id) XOR one of her fetuses (fetus_id). The CHECK
-- constraints are the safety net; the worker should enforces the same rule in code before insert.
ALTER TABLE public.obs_categorical
    ALTER COLUMN patient_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT obs_categorical_subject_xor
        CHECK ((patient_id IS NOT NULL) != (fetus_id IS NOT NULL));

ALTER TABLE public.obs_string
    ALTER COLUMN patient_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT obs_string_subject_xor
        CHECK ((patient_id IS NOT NULL) != (fetus_id IS NOT NULL));

ALTER TABLE public.family
    ALTER COLUMN family_member_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT family_member_subject_xor
        CHECK ((family_member_id IS NOT NULL) != (fetus_id IS NOT NULL));
