ALTER TABLE task_has_sequencing_experiments RENAME TO task_has_sequencing_experiment;
ALTER TABLE task_has_related_tasks RENAME TO task_has_related_task;
ALTER TABLE task_has_documents RENAME TO task_has_document;
ALTER TABLE document_has_patients RENAME TO document_has_patient;
