CREATE TABLE public.fetus (
    id integer NOT NULL,
    -- The submitter's own identifier, mirroring patient.submitter_patient_id: it is what makes a
    -- fetus addressable across batches, so an update can resolve and modify one in place instead of
    -- deleting and recreating it (which sample.fetus_id, having no ON DELETE CASCADE, would block).
    -- Scoped to the mother rather than an organization: a fetus has none of its own.
    submitter_fetus_id text NOT NULL,
    mother_id integer NOT NULL REFERENCES public.patient(id),
    life_status_code text NOT NULL REFERENCES public.life_status(code),
    sex_code text NOT NULL REFERENCES public.sex(code),
    last_menstrual_period date,
    estimated_due_date date,
    tenant_code text NOT NULL REFERENCES public.tenant(code)
);

ALTER TABLE public.fetus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fetus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.fetus
    ADD CONSTRAINT fetus_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fetus
    ADD CONSTRAINT fetus_mother_submitter_id_key UNIQUE (mother_id, submitter_fetus_id);

CREATE INDEX ix_fetus_tenant_code ON public.fetus (tenant_code);
CREATE INDEX ix_fetus_mother_id ON public.fetus (mother_id);

INSERT INTO public.family_relationship (code, name_en) VALUES
    ('fetus', 'Fetus');

-- A clinical row belongs to exactly one subject: the mother XOR one of her fetuses. The CHECK
-- is the safety net; the worker enforces the same rule before insert.
ALTER TABLE public.obs_categorical
    ALTER COLUMN patient_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT obs_categorical_subject_xor
        CHECK ((patient_id IS NOT NULL) != (fetus_id IS NOT NULL));

ALTER TABLE public.obs_string
    ALTER COLUMN patient_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT obs_string_subject_xor
        CHECK ((patient_id IS NOT NULL) != (fetus_id IS NOT NULL));

ALTER TABLE public.family
    ALTER COLUMN family_member_id DROP NOT NULL,
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id),
    ADD CONSTRAINT family_member_subject_xor
        CHECK ((family_member_id IS NOT NULL) != (fetus_id IS NOT NULL));

-- Unlike the tables above, patient_id and fetus_id are NOT mutually exclusive: the sample is
-- physically drawn from the mother, but its sequencing data is the fetus's genome. patient_id
-- stays NOT NULL, fetus_id is a pure addition.
ALTER TABLE public.sample
    ADD COLUMN fetus_id integer REFERENCES public.fetus(id);
