ALTER TABLE "organization" RENAME COLUMN "category_code" TO "category";
ALTER TABLE "patient" RENAME COLUMN "sex_code" TO "sex";
ALTER TABLE "patient" RENAME COLUMN "date_of_birth" TO "dob";
ALTER TABLE "request" RENAME COLUMN "status_code" TO "status";
ALTER TABLE "request" RENAME COLUMN "priority_code" TO "priority";
ALTER TABLE "request" RENAME COLUMN "ordering_organization_id" TO "ordering_organisation_id";
ALTER TABLE "case" RENAME COLUMN "type_code" TO "type";
ALTER TABLE "case" RENAME COLUMN "status_code" TO "status";
ALTER TABLE "family" RENAME COLUMN "relationship_to_proband_code" TO "relationship_to_proband";
ALTER TABLE "family" RENAME COLUMN "affected_status_code" TO "affected_status";
ALTER TABLE "observation_coding" RENAME COLUMN "interpretation_code" TO "interpretation";
ALTER TABLE "sample" RENAME COLUMN "category_code" TO "category";
ALTER TABLE "sample" RENAME COLUMN "type_code" TO "type";
ALTER TABLE "sample" RENAME COLUMN "histology_code" TO "histology";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "experimental_strategy_code" TO "experimental_strategy";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "status_code" TO "status";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "platform_code" TO "platform";
ALTER TABLE "task" RENAME COLUMN "type_code" TO "type";
ALTER TABLE "document" RENAME COLUMN "data_category_code" TO "data_category";
ALTER TABLE "document" RENAME COLUMN "data_type_code" TO "data_type";
ALTER TABLE "document" RENAME COLUMN "format_code" TO "format";
ALTER TABLE "request" DROP CONSTRAINT "request_status_code_fkey";
ALTER TABLE "request" ADD CONSTRAINT "request_status_fkey" FOREIGN KEY ("status_code") REFERENCES "status";
