ALTER TABLE "organization" RENAME COLUMN "category" TO "category_code";
ALTER TABLE "patient" RENAME COLUMN "sex" TO "sex_code";
ALTER TABLE "patient" RENAME COLUMN "dob" TO "date_of_birth";
ALTER TABLE "request" RENAME COLUMN "status" TO "status_code";
ALTER TABLE "request" RENAME COLUMN "priority" TO "priority_code";
ALTER TABLE "request" RENAME COLUMN "ordering_organisation_id" TO "ordering_organization_id";
ALTER TABLE "case" RENAME COLUMN "type" TO "type_code";
ALTER TABLE "case" RENAME COLUMN "status" TO "status_code";
ALTER TABLE "family" RENAME COLUMN "relationship_to_proband" TO "relationship_to_proband_code";
ALTER TABLE "family" RENAME COLUMN "affected_status" TO "affected_status_code";
ALTER TABLE "observation_coding" RENAME COLUMN "interpretation" TO "interpretation_code";
ALTER TABLE "sample" RENAME COLUMN "category" TO "category_code";
ALTER TABLE "sample" RENAME COLUMN "type" TO "type_code";
ALTER TABLE "sample" RENAME COLUMN "histology" TO "histology_code";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "experimental_strategy" TO "experimental_strategy_code";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "status" TO "status_code";
ALTER TABLE "sequencing_experiment" RENAME COLUMN "platform" TO "platform_code";
ALTER TABLE "task" RENAME COLUMN "type" TO "type_code";
ALTER TABLE "document" RENAME COLUMN "data_category" TO "data_category_code";
ALTER TABLE "document" RENAME COLUMN "data_type" TO "data_type_code";
ALTER TABLE "document" RENAME COLUMN "format" TO "format_code";
ALTER TABLE "request" DROP CONSTRAINT "request_status_fkey";
ALTER TABLE "request" ADD CONSTRAINT "request_status_code_fkey" FOREIGN KEY ("status_code") REFERENCES "status"("code");
