-- A case group is a named set of cases, the unit the pipeline notifies laboratories about (one per
-- post-processing run). The name is the business key (unique per tenant); the integer id only keys
-- the membership rows. Membership is a plain junction so a case can belong to several groups
-- (re-analysis runs) and deleting a case or a group cleans it up. Not federated to StarRocks.
CREATE TABLE public.case_group (
    id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code varchar(50) NOT NULL REFERENCES public.tenant(code),
    name        text        NOT NULL,
    created_on  timestamptz NOT NULL DEFAULT now(),
    created_by  text,
    UNIQUE (tenant_code, name)
);

CREATE TABLE public.case_group_case (
    case_group_id integer NOT NULL REFERENCES public.case_group(id) ON DELETE CASCADE,
    case_id       integer NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
    PRIMARY KEY (case_group_id, case_id)
);
CREATE INDEX case_group_case_case_id_idx ON public.case_group_case (case_id);
