-- =============================================================================
-- sequencing_request: the moment a sequencing service is ordered, before the
-- sample is drawn and before the lab has produced anything.
--
-- sequencing_experiment cannot absorb this: sample_id, aliquot,
-- experimental_strategy_code, sequencing_read_technology_code and platform_code
-- are all NOT NULL, and the upsert key is (sample_id, aliquot) — a placeholder row
-- would invent a sample and an aliquot that then collide with the real row at
-- delivery.
--
-- Decisions:
--   * case_id is NOT NULL: a request is always ordered in a case context, and the
--     case is the only access path (no orphan-request endpoint, no unattached view).
--   * The natural key is UNIQUE (case_id, submitter_sequencing_request_id), fed from
--     SR_sequencing.id. Without it the second post of the same batch — the normal
--     case, since update_case resends the whole payload — duplicates the request.
--     Tenant isolation follows transitively from case_id (cases is tenant-scoped),
--     so tenant_code stays out of the key; that also lets two QLIN sites reuse a
--     submitter id. It does not catch the same id posted under a different case:
--     accepted, QLIN does not reparent requests.
--   * patient_id is a direct FK to patient, not family, so a pending request can be
--     shown on the right family member — the role sample.patient_id plays for a
--     delivered experiment.
--   * No requester / supervisor / requester_organization_code: reachable by join
--     through the mandatory case_id, and copies would be two versions of one fact.
--   * tenant_code NOT NULL + index, no DEFAULT (000013 convention).
--   * No `type` column on status. Its codes are one shared pool — cases.status_code
--     and sequencing_experiment.status_code are both plain FKs to status(code) — so
--     one type per row could not express "used by both". QLIN only writes draft /
--     on-hold / revoked / completed to a sequencing ServiceRequest and its own
--     egress mapper already translates those to draft / submitted / revoke /
--     completed, all of which exist here already.
-- =============================================================================

CREATE TABLE public.sequencing_request (
    id integer NOT NULL,
    service_id integer NOT NULL,
    case_id integer NOT NULL,
    patient_id integer NOT NULL,
    status_code text NOT NULL,
    submitter_sequencing_request_id text NOT NULL,
    tenant_code varchar(50) NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone NOT NULL
);

ALTER TABLE public.sequencing_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sequencing_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_submitter_id_key UNIQUE (case_id, submitter_sequencing_request_id);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_service_fkey FOREIGN KEY (service_id) REFERENCES public.service_catalog(id);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_case_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patient(id);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_status_fkey FOREIGN KEY (status_code) REFERENCES public.status(code);

ALTER TABLE ONLY public.sequencing_request
    ADD CONSTRAINT sequencing_request_tenant_fkey FOREIGN KEY (tenant_code) REFERENCES public.tenant(code);

CREATE INDEX ix_sequencing_request_tenant_code ON public.sequencing_request (tenant_code);
CREATE INDEX ix_sequencing_request_case_id ON public.sequencing_request (case_id);

-- Nullable: CHOP delivers experiments with no prior request, and every existing row
-- predates this table.
ALTER TABLE public.sequencing_experiment ADD COLUMN sequencing_request_id integer;
ALTER TABLE ONLY public.sequencing_experiment
    ADD CONSTRAINT sequencing_experiment_sequencing_request_fkey
        FOREIGN KEY (sequencing_request_id) REFERENCES public.sequencing_request(id);

-- =============================================================================
-- Sequencing service codes for the default tenant.
--
-- These are the four concepts of the FHIR CodeSystem
-- http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code, which is what
-- ServiceRequest.code binds to on the cqgc-sequencing-request profile. They are MSSS
-- repertoire numbers, not WGS/WXS mnemonics — so service_code in the batch payload
-- is a numeric string. Note 75020 is exome and 75022 is genome.
--
-- These rows live in a numbered migration rather than scripts/init-sql/qlin/ on
-- purpose: nothing in the repo applies qlin/*.sql (the PostgreSQL entrypoint ignores
-- subdirectories of /docker-entrypoint-initdb.d and `make migrate` only scaffolds),
-- and a missing seed does not fail loudly — it surfaces as every sequencing request
-- failing validation on an unknown service code. golang-migrate is the only real
-- runner. Other tenants' rows stay in their own seed file.
-- =============================================================================

-- 000001 inserted its four rows with explicit ids and left the identity sequence at 1, so a
-- plain INSERT here would collide on the primary key — and ON CONFLICT (code, tenant_code)
-- would not swallow that, it only covers the constraint it names.
SELECT setval(pg_get_serial_sequence('public.service_catalog', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.service_catalog));

INSERT INTO public.service_catalog (code, type, name_en, name_fr, tenant_code) VALUES
    ('75020', 'sequencing', 'Normal Exome Sequencing',            'Séquençage d''exome normal',           'radiant'),
    ('75022', 'sequencing', 'Normal Genome Sequencing',           'Séquençage du génome normal',          'radiant'),
    ('65241', 'sequencing', 'Tumoral Exome Sequencing',           'Séquençage d''exome tumoral',          'radiant'),
    ('65240', 'sequencing', 'Tumoral Transcriptome Sequencing',   'Séquençage de transcriptome tumoral',  'radiant')
ON CONFLICT (code, tenant_code) DO NOTHING;
