CREATE TABLE IF NOT EXISTS saved_filter
(
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"    TEXT NOT NULL,
    "name"       TEXT NOT NULL,
    "type"       TEXT NOT NULL,
    "favorite"   BOOLEAN DEFAULT false,
    "queries"    JSONB,
    "created_on" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_on" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_saved_filter UNIQUE (
                                           "name",
                                           "type",
                                           "user_id"
        )
);