/// <reference types="cypress"/>
import { CommonSelectors } from './Selectors';

const CASE_VALUE = '1';
const DIAGLAB_VALUE = 'CQGC';
const PATIENT_VALUE = '3';
const REL_VALUE = 'proband';

export const data = {
  case: {
    case: CASE_VALUE,
    patient: PATIENT_VALUE,
    mrn: 'MRN-283775',
    priority: 'Routine',
    status: 'In Progress',
    type: CommonSelectors.familyIcon,
    analysis: 'WGA',
    primary_condition_name: 'neurodevelopmental disorder',
    primary_condition_id: 'MONDO:0700092',
    req_by: 'CHUSJ',
    project: 'N1',
    created_on: '2021-09-12',
    updated_on: '2021-09-12',
    prescriber: 'Felix Laflamme',
    diagnostic_lab: DIAGLAB_VALUE,
    managing_org: 'CHUSJ',
    has_variants: true,
    search_criteria: `[{"field": "case_id","value": ["${CASE_VALUE}"]}]`,
    seq: {
      seq_id: '1',
      sample_id: 'S13224',
      relationship: REL_VALUE,
      sample_type: 'dna',
      histology: 'normal',
      exp_strat: 'wgs',
      seq_status: 'Completed',
      last_update: '2021-10-12',
    },
  },
  file: {
    name: 'variants.CEPH-1463.snv.vep.vcf.gz',
    format: 'vcf',
    type: 'snv',
    size: '289.79 MB',
    case: CASE_VALUE,
    diag_lab: DIAGLAB_VALUE,
    relationship: REL_VALUE,
    patient: PATIENT_VALUE,
    sample: 'S13224',
    task: '63',
    created_on: '2025-',
    assay: '1',
    hash: '5d41402abc4b2a76b9719d911017c726',
    run: 'A00516_0169',
    search_criteria: '[{"field": "data_type_code","value": ["snv"]},{"field": "format_code","value": ["vcf"]},{"field": "patient_id","value": ["3"]}]',
  },
  variantGermline: {
    locus_id: '-6314429946999603200',
    variant: 'chr10:g.99235506G>A',
    type: 'SNV',
    dbsnp: 'rs72840396',
    gene: 'HPSE2',
    consequence: 'Splice Region Variant',
    aa_change: '-',
    consequenceImpact: CommonSelectors.colorIndicator('emerald'),
    maneC: true,
    maneM: false,
    maneP: false,
    omim: {
      condition: 'Urofacial syndrome 1',
      inheritance: 'AR',
      omim_id: '236730',
    },
    orphanet: {
      condition: 'Ochoa syndrome',
      inheritance: 'AR',
      orphanet_id: '2465',
    },
    hpo: {
      condition: 'Abnormal facial expression',
      inheritance: 'Unspecified',
      hpo_id: 'HP:0005346',
    },
    clinvar: {
      evaluated: '2020-07-07',
      condition: 'HPSE2-related disorder',
      classification: 'LB',
      submission_count: '1',
      status: 0,
      origin: 'Germline',
      rcv_link: 'RCV003916198',
    },
    exomiser: '0.438',
    acmg_exomiser: ['LB'],
    gnomad: '1.66e-3',
    freq: '5.00e-1',
    gq: '99.00',
    zyg: '0/1',
    ad_ratio: '0.46',
    interpreted: {
      case: '1',
      relationship: 'proband',
      date: '2025-12-22',
      condition_mondo: 'adrenocortical insufficiency',
      mondo_id: 'MONDO:0000004',
      classification: 'LP',
      zygosity: 'HET',
      inheritance: '-',
      diag_lab: 'CQGC',
      analysis: 'WGA',
      status: 'In Progress',
    },
    uninterpreted: {
      case: '1',
      relationship: 'mother',
      assay: '2',
      patient: '1',
      sample: 'S13225',
      aff_status: 'Affected',
      hpo: '-',
      zygosity: 'HET',
      diag_lab: 'CQGC',
      analysis: 'WGA',
      date: '2021-09-12',
      status: 'In Progress',
    },
    igv: {
      proband: 'S13224',
      father: 'S13226',
      mother: 'S13225',
    },
    sqon: '{"content":[{"content":{"field":"hgvsg","value":["chr10:g.99235506G>A"]},"op":"in"}],"op":"and"}',
  },
  cnvGermline: {
    genes: 'GUSBP11, GUSBP11',
    cytoband: 'q11.23',
    nb_snv: '15',
    cnv_variant: 'GAIN:chr22:23709618-23720246',
    chromosome: '22',
    start: '23709617',
    end: '23720246',
    type: 'GAIN',
    length: '10629.0 kb',
    cn: '3',
    gnomad: '3.49e-4',
    nb_genes: '2',
    gt: '-11',
    filter: 'PASS',
    quality: '32',
    bc: '9',
    pe: '2836',
    sqon: '{"content":[{"content":{"field":"name","value":["DRAGEN:GAIN:chr22:23709618-23720246"]},"op":"in"}],"op":"and"}',
  },
};
