/// <reference types="cypress"/>
import { CommonSelectors } from './Selectors';

const CASE_GERMLINE_VALUE = '1';
const DIAGLAB_GERMLINE_VALUE = 'CQGC';
const PATIENT_GERMLINE_VALUE = '3';
const CASE_SOMATIC_VALUE = '1008';
const REL_PROBAND_VALUE = 'proband';
const CASE_OTHER_LAB_VALUE = CASE_SOMATIC_VALUE;
const ETL_DATE_VALUE = '2026-09-24';

export const data = {
  case: {
    case: CASE_GERMLINE_VALUE,
    patient: PATIENT_GERMLINE_VALUE,
    mrn: 'MRN-283775',
    priority: 'Routine',
    status: 'In Progress',
    type: CommonSelectors.familyIcon,
    analysis: 'WGA',
    primary_condition_name: 'neurodevelopmental disorder',
    primary_condition_id: 'MONDO:0700092',
    req_by: 'CHUSJ',
    project: 'N1',
    created_on: '2021-09-12',
    updated_on: ETL_DATE_VALUE,
    prescriber: 'Felix Laflamme',
    diagnostic_lab: DIAGLAB_GERMLINE_VALUE,
    managing_org: 'CHUSJ',
    has_variants: true,
    search_criteria: `[{"field": "case_id","value": ["${CASE_GERMLINE_VALUE}"]}]`,
    seq: {
      seq_id: '1',
      sample_id: 'S13224',
      relationship: REL_PROBAND_VALUE,
      sample_type: 'dna',
      histology: 'normal',
      exp_strat: 'wgs',
      seq_status: 'Closed',
      last_update: '2021-10-12',
    },
    task: {
      task_id: /^1$/,
      type: 'Genome Alignment and Germline Variant Calling',
      patient: REL_PROBAND_VALUE,
      created_on: '2021-10-12',
    },
  },
  assignmentCandidates: {
    case: CASE_GERMLINE_VALUE,
    diagnostic_lab: DIAGLAB_GERMLINE_VALUE,
    case_other_lab: CASE_OTHER_LAB_VALUE,
    diagnostic_lab_other: 'LDM-CHUSJ',
    self: {
      first_name: 'Cypress',
      last_name: 'Cypress',
      email: 'cypress@email.me',
    },
    other_lab_only: {
      first_name: 'Allison',
      last_name: 'Heath',
      email: 'allison@chop.edu',
    },
    accented: {
      first_name: 'Jérémy',
      last_name: 'Costanza',
      email: 'jecos@email.me',
      search_unaccented: 'jer',
      search_accented: 'Jér',
    },
    no_result: 'zzz',
  },
  file: {
    name: 'variants.CEPH-1463.snv.vep.vcf.gz',
    format: 'vcf',
    type: 'snv',
    size: '289.79 MB',
    case: CASE_GERMLINE_VALUE,
    diag_lab: DIAGLAB_GERMLINE_VALUE,
    relationship: REL_PROBAND_VALUE,
    patient: PATIENT_GERMLINE_VALUE,
    sample: 'S13224',
    task: '63',
    created_on: '2026-',
    sequencing: '1',
    hash: '5d41402abc4b2a76b9719d911017c726',
    run: 'A00516_0169',
    search_criteria: `[{"field":"format_code","value":["vcf"]},{"field":"data_type_code","value":["snv"]},{"field":"relationship_to_proband_code","value":["${REL_PROBAND_VALUE}"]}]`,
  },
  variantGermline: {
    locus_id: '-6314429946999603200',
    locus: '10-99235506-G-A',
    variant: 'chr10:g.99235506G>A',
    type: 'SNV',
    dbsnp: 'rs72840396',
    gene: 'HPSE2',
    gene_id: 'ENSG00000172987',
    consequence: 'Splice Region',
    aa_change: null,
    consequenceImpact: CommonSelectors.colorIndicator('emerald'),
    maneC: true,
    maneM: false,
    maneP: false,
    patients: '2 (1.43e-1)',
    transcript_id: 'ENST00000370552',
    exon: null,
    dna_change: 'c.290+7C>T',
    omim: {
      condition: 'Urofacial syndrome 1',
      inheritance: 'AR',
      omim_id: '236730',
    },
    orphanet: {
      condition: 'Ochoa syndrome',
      inheritance: 'AR',
      orphanet_id: '2465',
    },
    hpo: {
      condition: 'Abnormal facial expression',
      inheritance: 'Unspecified',
      hpo_id: 'HP:0005346',
    },
    clinvar_classifications: ['Likely_benign', 'Benign'],
    clinvar_evidence: {
      evaluated: /2020-07-0(7|8)/,
      condition: 'HPSE2-related disorder',
      classification: 'LB',
      submission_count: '1',
      status: 0,
      origin: 'Germline',
      rcv_link: 'RCV003916198',
      version: 2,
    },
    clinvar_name: '784210',
    exomiser: '0.438',
    acmg_exomiser: ['Likely_benign'],
    gnomad: '1.66e-3',
    freq: /(1.43e-1|8.33e-2)/,
    gq: '99.00',
    zyg: '0/1',
    ad_ratio: '0.46',
    publicCohorts: {
      cohort: 'TopMed',
      alt: '194',
      alt_ref: '125,568',
      homo: '0',
      freq: '1.54e-3',
    },
    predictionScores: {
      caddphred: null,
      caddraw: null,
      dann: null,
      fathmm: null,
      loeuf: '0.686',
      lrt: null,
      phylop17way: null,
      pli: '1.51e-4',
      polyphen2_hvar: null,
      revel: null,
      sift: null,
      spliceai: 'DG',
    },
    myNetwork: {
      primary_condition_name: 'cerebral ventricle cancer',
      primary_condition_id: 'MONDO:0002682',
      freq_all: '0/1',
      homo_all: '0',
      freq_affected: '0/1',
      homo_affected: '0',
      freq_non_affected: '-',
      homo_non_affected: '-',
    },
    interpreted: {
      case: CASE_GERMLINE_VALUE,
      relationship: REL_PROBAND_VALUE,
      date: '2026-01-09',
      primary_condition_name: 'adrenocortical insufficiency',
      primary_condition_id: 'MONDO:0000004',
      classification: 'Likely_pathogenic',
      zygosity: 'HET',
      inheritance: '-',
      diag_lab: DIAGLAB_GERMLINE_VALUE,
      analysis: 'WGA',
      status: 'In Progress',
    },
    uninterpreted: {
      case: CASE_GERMLINE_VALUE,
      relationship: 'mother',
      sequencing: '2',
      patient: '1',
      sample: 'S13225',
      aff_status: 'Affected',
      hpo: '-',
      zygosity: 'HET',
      diag_lab: DIAGLAB_GERMLINE_VALUE,
      analysis: 'WGA',
      date: ETL_DATE_VALUE,
      status: 'In Progress',
    },
    igv: {
      proband: 'S13224',
      father: 'S13226',
      mother: 'S13225',
    },
    sqon: '{"content":[{"content":{"field":"hgvsg","value":["chr10:g.99235506G>A"]},"op":"in"}],"op":"and"}',
  },
  caseSomatic: {
    case: CASE_SOMATIC_VALUE,
    patient: '1010',
    mrn: 'MRN-283834',
    priority: 'Routine',
    status: 'In Progress',
    analysis: 'WGA',
    primary_condition_name: 'breast cancer',
    primary_condition_id: 'MONDO:0007254',
    req_by: 'CHUSJ',
    project: 'N1',
    has_variants: true,
    seq: {
      seq_id: '1011',
      sample_id: 'SRX1091647',
      relationship: REL_PROBAND_VALUE,
      sample_type: 'dna',
      histology: 'tumoral',
      exp_strat: 'wgs',
      seq_status: 'Closed',
    },
    task: {
      task_id: '1018',
      type: 'RADIANT Somatic Annotation',
    },
  },
  variantSomatic: {
    locus_id: '-8929279848199749632',
    variant: 'chr1:g.21836953C>T',
    type: 'SNV',
    dbsnp: '-',
    gene: 'HSPG2',
    aa_change: 'p.Val3402Met',
    consequence: 'Missense',
    consequenceImpact: CommonSelectors.colorIndicator('amber'),
    maneC: true,
    maneM: false,
    maneP: false,
    omim: {
      codes: ['AR'],
    },
    clinvar: ['Conflicting_classifications_of_pathogenicity', 'Uncertain_significance', 'Likely_benign'],
    gnomad: '1.31e-4',
    hotspot: false,
    freq_to: '1 (1.00e+0)',
    freq_tn: '1 (1.00e+0)',
    freq_g: '0 (0)',
    sq: null,
    aq: null,
    ad_ratio: '0.24',
    sqon: '{"content":[{"content":{"field":"hgvsg","value":["chr1:g.21836953C>T"]},"op":"in"}],"op":"and"}',
  },
  cnvGermline: {
    task_id: '1',
    genes: 'GUSBP11, GUSBP11',
    cytoband: 'q11.23',
    nb_snv: '14',
    cnv_variant: 'GAIN:chr22:23709618-23720246',
    chromosome: '22',
    start: '23,709,617',
    end: '23,720,246',
    type: 'GAIN',
    length: '10.6 kb',
    cn: '3',
    gnomad: '3.49e-4',
    nb_genes: '2',
    gt: '-11',
    filter: 'PASS',
    quality: '32',
    bc: '9',
    pe: '2836',
    sqon: '{"content":[{"content":{"field":"name","value":["DRAGEN:GAIN:chr22:23709618-23720246"]},"op":"in"}],"op":"and"}',
  },
  cnvOverlappingGenes: {
    gene: 'GUSBP11',
    cytoband: 'q11.23',
    length: '57.4 kb',
    nb_overlap_bases: '7.7 kb',
    nb_exons: '4',
    overlapping_gene_percent: '13',
    overlapping_cnv_percent: '72.24',
    overlap_type: 'partial',
  },
};
