/// <reference types="cypress"/>
export const CommonSelectors = {
  actionButton: '[class*="lucide-ellipsis-vertical"]',
  activeTab: '[data-active="true"]',
  anchorIcon: '[class*="lucide-arrow-up-right"]',
  animateIn: '[class*="data-[state=open]:animate-in"]',
  colorIndicator: (color: string) => `[class*="text-indicator-${color}"]`,
  expandIcon: '[class*="lucide-chevron-righ"]',
  familyIcon: '[class*="lucide-users"]',
  gnomadRedIcon: '[class*="text-red-500 bg-red-500"]',
  interpretationIcon: '[class*="lucide-zap"]',
  langButton: 'button[class*="text-muted-foreground px-3 text-base md:text-sm"]',
  link: '[href], a',
  loadIndicator: 'animate-pulse',
  logo: '[alt="Logo"]:visible',
  logoutIcon: '[class*="lucide-log-out"]',
  maneCPath: 'path[d*="0ZM16"]',
  maneMPath: 'path[d*="0ZM8"]',
  manePPath: 'path[d*="0ZM10"]',
  menuItem: (text: string) => `[role="menuitem"]:contains("${text}")`,
  menuPopper: '[data-radix-popper-content-wrapper]',
  modal: '[role="dialog"]',
  pillQueryActive: '[data-query-active="true"] [class="flex items-center py-[2px]"]',
  pinIcon: '[class*="lucide-pin"]',
  pinLeftIcon: '[class*="lucide-pin rotate-90"]',
  pinned: (position: string) => `[class*="sticky"][style*="${position}"]`,
  plusIcon: '[class*="lucide-plus"]',
  querybarSelected: '[class*="QueryBar_selected"]',
  resetButton: 'button:contains("Reset")',
  saveIcon: '[class*="lucide-save"]',
  settingsCheckbox: (value: string) => `[class*="items"]:contains("${value}") [role="checkbox"]`,
  settingsIcon: '[class*="lucide-settings"]',
  settingsPopper: '[class*="radix-dropdown-menu-content"]',
  sortIcon: '[class*="lucide-arrow-up"], [class*="lucide lucide-arrow-down"]',
  starEmptyIcon: '[class*="lucide-star text-bookmark-off"]',
  starFillIcon: '[class*="lucide-star text-bookmark-amber"]',
  statusIcon: (icon: string) => `[class*="lucide-${icon}"]`,
  tableCellData: 'td',
  tableCellHead: 'th',
  tableHead: (id?: string) => `table${id || ''} thead`,
  tableHeadCell: (id?: string) => `table${id || ''} thead th`,
  tableRow: (id?: string) => `table${id || ''} tbody tr`,
  tag: (color: string) => `[class*="bg-${color}/20 text-${color}-foreground"]`,
  tagBlank: '[class*="text-foreground"]',
  tagLevel: (level: string) => `[class*="bg-${level} text-${level}-foreground"]`,
  title: 'h1',
  tooltipPopper: '[class*="radix-tooltip-content"]',
  underlineHeader: '[class*="decoration-dotted"]',
  unpinIcon: '[class*="lucide-pin-off"]',
  userIcon: 'button[aria-haspopup="menu"] [class*="rounded-full bg-cyan/20 text-cyan-foreground"]',
};
