/// <reference types="cypress"/>
export const CommonSelectors = {
  actionButton: '[class*="lucide-ellipsis-vertical"]',
  activeTab: '[data-active="true"]',
  alert: '[role="alertdialog"]',
  anchorIcon: '[class*="lucide-arrow-up-right"]',
  animateIn: '[class*="data-[state=open]:animate-in"]',
  checkIcon: '[class*="lucide-check"]',
  circlePlusIcon: '[class*="lucide-circle-plus"]',
  closeButton: '[data-cy="close-button"]',
  colorIndicator: (color: string) => `[class*="text-indicator-${color}"]`,
  datacy: (field: string) => `[data-cy="${field.replace(/_/g, '-')}"]`,
  deleteFilterConfirmButton: '[data-cy="delete-filter-confirm-button"]',
  deleteIcon: '[class*="lucide-trash"]',
  detailsButton: '[data-cy="details-button"]',
  dirtyClass: 'text-yellow-500',
  duplicateIcon: '[class*="lucide-copy"]',
  editIcon: '[class*="lucide-pen"]',
  editLineIcon: '[class*="lucide-pencil-line"]',
  expandIcon: '[class*="lucide-chevron-righ"]',
  expandCollapseButton: (text: string) => `[data-cy="expand-collapse-button"]:contains("${text}")`,
  facetDictionaryButton: (id: string) => `[data-cy="facet-dictionary-button-${id}"]`,
  facetHeader: (id: string) => (id ? `[data-cy="facet-header-${id}"]` : `[data-cy^="facet-header-"]`),
  facetApplyButton: (id: string) => `[data-cy="facet-apply-button-${id}"]`,
  facetCheckbox: (apiField: string, value: string) => (value ? `[data-cy="facet-checkbox-${apiField}-${value}"]` : `[data-cy^="facet-checkbox-${apiField}-"]`),
  facetMinInput: (field: string) => `[id="${field}_min"]`,
  facetMaxInput: (field: string) => `[id="${field}_max"]`,
  facetOperator: (field: string) => `[id="${field}_operator"]`,
  facetState: (state: string) => `[data-cy="facet-state-${state}"]`,
  facetTooltipTrigger: (id?: string) => (id ? `[data-cy="facet-tooltip-trigger-${id}"]` : `[data-cy^="facet-tooltip-trigger-"]`),
  facetValueInput: (field: string) => `[id="${field}_value"]`,
  familyIcon: '[class*="lucide-users"]',
  gnomadRedIcon: '[class*="text-red-500 bg-red-500"]',
  igvContainer: '[id="igvContainer"]',
  igvIcon: '[class*="lucide-flip-vertical2"]',
  igvError: '[class*="igv-ui-alert-dialog"]:contains("Error")',
  igvTrack: '[class="igv-track-label"]',
  igvWindowSize: '[class="igv-windowsize-panel-container"]',
  igvZoomButtons: '[class*="igv-zoom-widget"] path',
  input: 'input',
  inputValue: (value: string) => `input[value="${value}"]`,
  interpretationIcon: '[class*="lucide-clipboard-list"]',
  langButton: 'button[class*="text-muted-foreground px-3 text-base md:text-sm"]',
  link: '[href], a',
  listItemAction: (name: string) => `li [class*="text-sm font-medium"]:contains("${name}")`,
  loadIndicator: 'animate-pulse',
  logo: '[alt="Logo"]:visible',
  logoutIcon: '[class*="lucide-log-out"]',
  maneCPath: 'path[d*="0ZM16"]',
  maneMPath: 'path[d*="0ZM8"]',
  manePPath: 'path[d*="0ZM10"]',
  menuItem: (text: string) => `[role="menuitem"]:contains("${text}")`,
  menuPopper: '[data-radix-popper-content-wrapper]',
  modal: '[role="dialog"]',
  myFiltersButton: '[data-cy="my-filters-button"]',
  paginationButton: (name: string) => `[data-cy="pagination-button-${name}"]`,
  pillQueryActive: '[data-query-active="true"] [class*="flex items-center"]',
  pinIcon: '[class*="lucide-pin"]',
  pinLeftIcon: '[class*="lucide-pin rotate-90"]',
  pinned: (position: string) => `[class*="sticky"][style*="${position}"]`,
  plusIcon: '[class*="lucide-plus"]',
  querybarSelected: '[class*="QueryBar_selected"]',
  querybuilderHeader: 'h3 [class*="border-b py-0 px-6"]',
  resetButton: 'button:contains("Reset")',
  savedListDropdown: '[data-cy="saved-filter-content"]',
  saveIcon: '[class*="lucide-save"]',
  searchInput: '[data-cy="table-filters-search-input"]',
  settingsCheckbox: (value: string) => `[class*="radix-dropdown-menu-content"] [class*="items"]:contains("${value}") [role="checkbox"]`,
  settingsIcon: '[class*="lucide-settings"]',
  settingsPopper: '[class*="radix-dropdown-menu-content"]',
  sidebarSection: (section: string) => `[data-sidebar="menu-item"]:contains("${section}") svg`,
  shareIcon: '[class*="lucide-share2"]',
  sortIcon: '[class*="lucide-arrow-up"], [class*="lucide lucide-arrow-down"]',
  starEmptyIcon: '[class*="lucide-star text-bookmark-off"]',
  starFillIcon: '[class*="lucide-star text-bookmark-amber"]',
  statusIcon: (icon: string) => `[class*="lucide-${icon}"]`,
  suggestionItem: (field: string, value: string) => `[data-cy="table-filters-search-item-${value}::${field}"]`,
  suggestionList: (filtersId: string) => `[id="${filtersId}"] [role="listbox"]`,
  submitTypeButton: 'button[type="submit"]',
  tableCellData: 'td',
  tableCellHead: 'th',
  tableHead: (id?: string) => `table${id || ''} thead`,
  tableHeadCell: (id?: string) => `table${id || ''} thead th`,
  tableRow: (id?: string) => `table${id || ''} tbody tr`,
  tag: (color: string) => `[class*="bg-${color}/20 text-${color}-foreground"]`,
  tagBlank: '[class*="text-foreground"]',
  tagLevel: (level: string) => `[class*="bg-${level} text-${level}-foreground"]`,
  title: 'h1, h2',
  tooltipPopper: '[class*="radix-tooltip-content"]',
  underlineHeader: '[class*="decoration-dotted"]',
  unpinIcon: '[class*="lucide-pin-off"]',
  userIcon: 'button[aria-haspopup="menu"] [class*="rounded-full bg-cyan/20 text-cyan-foreground"]',
  variantPreview: '[role="dialog"][class*="data-[state=open]:slide-in-from-right"]',
};
