/// <reference types="cypress"/>
export const CommonTexts = {
  en: {
    collapseAll: 'Collapse all',
    expandAll: 'Expand all',
    format: 'Format',
    igvMaxZoom: '40 bp',
    igvTitle: 'Alignment and variant',
    igvTrackReads: (sample: string, relationship: string) => `Reads: ${sample} ${relationship}`,
    igvTrackRefseq: 'Refseq Genes',
    loginContent: ' Sign in to your account ',
    manageFilters: 'Manage filters',
    queryBuilderEmptyState: 'Use the search tools & facets on the left to build a query',
    searchByGeneTooltip: 'Enter a Gene Symbol or Ensembl ID',
    switchLanguage: 'FR',
    uploadPopoverFileFormatsValues: '.txt, .csv, .tsv',
    uploadPopoverIdentifiersValues: 'Gene Symbol, Ensembl ID',
    uploadPopoverSeparatorsValues: 'comma, space, new line',
    uploadPopoverTitle: 'Identifiers and File Formats',
  },
  fr: {
    collapseAll: 'Réduire tout',
    expandAll: 'Développer tout',
    format: 'Format',
    igvMaxZoom: '40 bp',
    igvTitle: 'Alignement et variant',
    igvTrackReads: (sample: string, relationship: string) => `Reads: ${sample} ${relationship}`,
    igvTrackRefseq: 'Refseq Genes',
    loginContent: ' Sign in to your account ',
    manageFilters: 'Gérer les filtres',
    queryBuilderEmptyState: 'Utilisez les outils de recherche et les facettes à gauche pour construire une requête',
    searchByGeneTooltip: 'Recherche par symbole et Ensembl ID',
    switchLanguage: 'EN',
    uploadPopoverFileFormatsValues: '.txt, .csv, .tsv',
    uploadPopoverIdentifiersValues: 'Symbole du gène, Ensembl ID',
    uploadPopoverSeparatorsValues: 'virgule, espace, retour de ligne',
    uploadPopoverTitle: 'Identifiants et formats de fichier',
  },
};
