# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and build backend

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Changed Files 👀
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'

      - name: Set up Go
        if: steps.filter.outputs.backend == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        if: steps.filter.outputs.backend == 'true'
        run: go mod download
        working-directory: ./backend

      - name: Ensure dependencies are up-to-date
        if: steps.filter.outputs.backend == 'true'
        run: go mod tidy
        working-directory: ./backend

      - name: Build
        if: steps.filter.outputs.backend == 'true'
        run: go build -v ./...
        working-directory: ./backend

      - name: Test
        if: steps.filter.outputs.backend == 'true'
        run: go test -v ./...
        working-directory: ./backend
