CREATE TABLE sample
(
    "id"               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category"         TEXT NOT NULL REFERENCES "sample_categories" ("code"),
    "type"             TEXT NOT NULL REFERENCES "sample_types" ("code"),
    "parent_sample_id" INTEGER REFERENCES "sample" ("id"),
    "tissue_site"      TEXT,
    "histology"        TEXT REFERENCES "histology_types" ("code"),
    "submitter_id"     TEXT
);

CREATE INDEX IF NOT EXISTS idx_sample_parent_id ON "sample" ("parent_sample_id");