CREATE TABLE task
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type"        TEXT REFERENCES "task_types" ("code") NOT NULL,
    "pipeline_id" INTEGER REFERENCES "pipeline" ("id")  NOT NULL,
    "created_on"  TIMESTAMP                             NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_task_type ON "task" ("type");